### ISSUE TITLE
Suspend and resume missing from feature

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1042]
![image](https://user-images.githubusercontent.com/1462282/29881222-dd6ca9be-8d5e-11e7-9e09-ff07466d2c94.png)

**Comment by mrlacey** [comment]
FYI. Adding a check for the cause of this as part of #1037

**Comment by crutkas** [comment]
how did a VB item cause a C# item to not show?  this feels like a larger underlying issue then

**Comment by mrlacey** [comment]
**Why the item didn't show up**
The VB Item had the same ID as the C# one but they're supposed to be unique. If there are multiple templates with the same identity none would show up. That's better than breaking when trying to add multiple things at once.

**This won't happen again**
Because I've added this to the template checking tool (and tests) I'm adding for #1037

**Why were both C# and VB templates both in the same folder and loaded at once?**
Now that's the real question. It seems there's something else going on with files not being copied around correctly. If in the C# mode of the wizard the VB templates shouldn't be copied into the folder where the wizard displays things from.
Who's been near the code for copying/loading templates and can say what's changed? 
When I added VB support there was a lot of template file copying that I had to debug and step through as the wizard would take all the templates and only copy the ones for the selected language into the folder it actively works from. This was an underlying cause of much of the impact on testing that supporting multiple languages caused. It seems something has changed in this part of the code logic.

**Comment by crutkas** [comment]
For the "Why the item didn't show up", feels like something we could have a unit test check.

**Comment by mrlacey** [comment]
@crutkas I'm adding the check to make sure there won't be multiple templates with the same identity. 
Are you asking about adding a check that says "given project type X and framework Y we know {these (and only these?)} templates should be shown"?
My initial reaction is that will become a lot to configure and probably be quite fragile. It could be done though...

**Comment by mvegaca** [comment]
Checked on 
Wizard: 0.14.17244.65002
Templates: 0.14.17244.2

Can it be closed?

**Comment by ralarcon** [comment]
@mrlacey Just for clarification: the templates repository is designed as a whole. We do not filter by language to setup the repository. The repository is read by the Template Engine, which is responsible to load it and provide the templates for us. The discovery of the templates is done by the template engine. Once loaded by the templates engine we apply filters (by language, by type, by name...) using extension methods and the tags. When the templates are packaged, all the templates are included and published to the CDN, where the wizard download it.

That said, nothing have changed. The templates are loaded by the template engine and if there is a duplicated id, the template engine override the template definition. That's all. 

The reason to have all the templates copied everytime is to mimic the production behavior. Locally, we previously setup the templates package on the fly copying all the available templates. Then the behavior is like if were downloaded... it is unpackaged and moved to the "ProgramData/WindowsTemplateStudio" folder.

There is a room of improvement for sure, but the first thing we want locally is to be sure that we are using the latest templates. With all we currently know, we can redesign the way the package is created.

Agree to add checks to avoid duplicated identities at the "Templates" level.

**Comment by mvegaca** [comment]
Tested
Wizard: 0.14.17248.65001
Templates: 0.14.17247.1
