### ISSUE TITLE
DeepLinking not available from right click

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#1097]
UriScheme not available from right click

X-Ref: #506

**Comment by mrlacey** [comment]
This should work it just needs enabling and then testing. The manual testing of every variation of this is just a looooong process.

**Comment by ralarcon** [comment]
Yeah, I think it should not have issues... @mrlacey, we can help with the testing. Which test path you have in mind? To be aligned with you. If we found the testing satisfactory we can even enable it for 1.3 (we are just wrapping and making the final test pass)

**Comment by mrlacey** [comment]
It's really just a time-consuming process.

- Generate the project
- [Right-Click] add the extra feature
- change the default generated protocol to avoid testing issues with multiple installed apps supporting the same protocol.
- Run the app to test that it all behaves as it should:
-- launch normally
-- launch from protocol without path
-- launch from protocol with path but not query string
-- launch from protocol with path and query string
-- launch from protocol with non-handled path
-- with app already running on homepage, launch URI with specific path 
-- with app already running and not on homepage, launch URI without specific path


While testing the original implementation of this and similarly complicated features in the past I have found that it is necessary to test every project type/framework combination (M*N) because it is in the minor differences between these that issues are found.

The complexity and time-consuming nature of this have also prompted me to raise #1100 which I've been considering for a while. While it wouldn't help with the Right-Click Add aspect of this it would save time in testing overall.

**Comment by ralarcon** [comment]
@mrlacey, If you agree we can share the testing effort. We can start with the Nav Pane and Code Behind. I'll update this thread when finished and wanted to start with other combination to avoid concurrency issues :D

**Comment by mrlacey** [comment]
Yes, I'm perfectly happy for someone else to test this. I added the notes above to help anyone who wants to do this. 
In my mind (based on testing the original work) it's at least a couple of hours effort and I won't get to it today.

**Comment by ralarcon** [comment]
Don't worry, we are closing and have bandwith to do the testing. We take care.

**Comment by mrlacey** [comment]
And while I was out picking up my kids from school I remembered why this wasn't enabled in the first place.
The templates for this feature use a replacement on `wts.homePageName` but this isn't available when doing a Right-Click>Add.

The SchemeActivationHandler has to handle activation which should just launch the app normally and this means navigating to the home page. When going through the right click process the wizard doesn't know what the name of the original home page was and so ends up doing a replacement with an empty string. In turn, this leads to generated code that doesn't compile. It can't even rely on the default name because this may have been changed.

In order for this feature to be right-click enabled, the wizard must store more information from the original user selection (presumably in the appxmanifest) so that it is available to the Right-Click process.
**Such a change is too big to be incorporated in v1.3 at this time.** 
I suggest that a full review of what else might benefit from being stored from the original generation is done before attempting to implement any such change. Investigation of whether there's another way of doing this and other things like it might also be prudent. Other proposed features and pages (such as AnimatedSplashScreen, Login/Registration, and more) will also depend on such functionality to be right-click enabled. 
Any changes related to this need to be done with a holistic view of all that is likely to be wanted and needed in this area or relates to this.

There's also a bug in one of the MVVMLight templates that I'll fix. Automated testing should also have picked it up so I'll look into why it didn't too.

**Comment by ralarcon** [comment]
Well, we were reviewing what we have found and I was about to write...

Apart from the `wts.homePageName` thing, where you are correct, it is only available at project creation time not right-click time, we have found that the  merge action in the `package.appmanifest` file fails if there is already other extension added. This can be easily fixed by changing the post-action a bit.

For the default activation, to add the home page info to manifest would help but the user might change it and then we could be pointing to the wrong page or even to an unexisting one. Thinking I see some options to fix this:
1. Let the code being generate wrong (fails at build time) and put a `TODO WTS:` comment stating very clear that there should be set the home page. 
2. Comment the whole line and add the `TODO WTS:` to make the user include the home page even when creating the project (worst from my point of view). 
3. Include in the NavigationService a property with the HomePage, populate it at project creation time, and then, use it from here.

For the merge issue, to solve we need:
1. Include in the `package.appmanifest` the `<Extensions>` node (empty)
``` xml
<?xml version="1.0" encoding="utf-8"?>
<Package
xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
xmlns:genTemplate="http://schemas.microsoft.com/appx/developer/windowsTemplateStudio"
IgnorableNamespaces="uap mp genTemplate">

...
<Applications>
   <Application Id="App" Executable="$targetnametoken$.exe" EntryPoint="wts.DefaultProject.App">
...
      <Extensions>
      </Extensions>
   </Application>
</Applications> 
...
```
2. Modify the post action as follows:
``` xml
[‎07/‎09/‎2017 17:32] Martin Vega Caballero (Intl Vendor): 
<Applications>
  <Application Id="App" Executable="$targetnametoken$.exe" EntryPoint="Param_RootNamespace.App">
    <Extensions>
       <!--^^-->
       <!--{[{-->
       <uap:Extension Category="windows.protocol">
       <uap:Protocol Name="wtsapp">
          <uap:Logo>Assets\Icon.png</uap:Logo>
          <uap:DisplayName>Param_RootNamespace</uap:DisplayName>
      </uap:Protocol>
   </uap:Extension>
   <!--}]}-->
   </Extensions>
 </Application>
</Applications> 
```

Then we have thought that the templates "Root_Namespace" parameter could be used to configure the schema protocol name by defautl (this avoid collisions during testing :D)

Thats all. I agree we can punt this for 1.4

**Comment by mrlacey** [comment]
Seems we also need extra generation tests for adding all pages and features at creation time and then again as a right-click action too.

**Comment by ralarcon** [comment]
Yes, we need to think a way to test this automatically...

**Comment by ralarcon** [comment]
@crutkas, @mvegaca, @mrlacey: to solve this improvement in the navigation service is required and not sure if we are in the position to achive this for 1.4. Do you think we can move it to 1.5 with the intention to aford it as soon as possible?

**Comment by mrlacey** [comment]
I see no need for this to be part of 1.4
Especially if delaying this frees up time to complete the required navigation service and shell changes

**Comment by mrlacey** [comment]
Pushing to 1.5 but may also be able to solve this based on the same solution for adding right-click support for feedback hub link. (#196)

**Comment by ralarcon** [comment]
@crutkas, @mrlacey I been reviewing this and I think that a simpler solution may apply.

Instead of waiting to have improvements in the navigation service to have identified the Home Page, we can handle this like we have done in the "[Web To App Link feature](https://github.com/Microsoft/WindowsTemplateStudio/blob/c7e7c782216385f9d77d17f8e097ee7ea5a32702/templates/Features/WebToAppLink/Activation/WebToAppLinkActivationHandler.cs#L27)", that is, adding a "TODO WTS" indicating that is the developer responsibility to navigate the home page.

PROS: 
- Simple common solution which apply to Right-Click and project generation.
- No code differentiation among frameworks, the same generation apply for every framework.
- Avoid framework will need to have a way to navigate to the home page and this must be implemented.
- In other approach, without Navigation service improvements will require meta-data that would become stale or not accurate. 
- No post-action required to handle this.

CONS:
- If the user do not add the navigate to the home page required code, launchs the app, and the Uri does not match the sample, the the app leaves in wierd estate.

I think the new approach have more benefits but like to hear your opinion.

**Comment by crutkas** [comment]
i need to understand this better before i make a call.  I would defer to @mrlacey as he was the original author of this

**Comment by ralarcon** [comment]
Wating for @mrlacely comments.

**Comment by crutkas** [comment]
any reason why this can't be 1.7?

**Comment by ralarcon** [comment]
No. Would be great if @mrlacely can confirm that it is ok to enable this feature for right-click using the same approach than we have used for "Web To App Link", that is, adding a TODO where the user needs to set the home page.

**Comment by mrlacey** [comment]
There's a big difference between the UriScheme and WebToAppLink implementations. The UriScheme one is fully working when generated. The WebToAppLink one isn't.

The benefits of the UriScheme implementation being fully working when generated is that it provides a complete working example and is much easier to test the generated code works as expected/intended.
The downside is that is that it includes some sample code that must be deleted.

To address the lack of right-click support for UriScheme in the way that WebToAppLink does would require one of the following:
- Change UriScheme so it's not complete and working when generated but requires a new TODO.
- Leave the current one without right-click support and add a version that is right-click only that includes the TODO. (Note. that we don't yet have a way to have right-click only templates.)

The underlying issue here is that we don't know what was set as the default/home page at the original time of creation. It would be possible to try and work this out (I've explored this before) with a high level of success and fall back to a TODO if it's not possible.

Another approach (and something I was planning on bringing up in the future) would be to change the way the ActivationService works. At the moment it only ever calls one ActivationHandler and so requires that every handler be able to navigate to the home page if necessary. (This is the issue behind #772.) Things could be made much simpler if a handler could decide to not handle the launch and so fallback to the default handler. By only having the default launch page defined once it would simplify the handler logic and remove duplication. (I suspect this may be increasingly important for #291, #292, & #293)

**So**, what should be done?
I'd rather address the bigger underlying issues than do something just to add Right-Click support for this feature. Especially if it would be a step back from what we have at the moment and we haven't (AFAIK) had anyone request this explicitly. 

The lack of knowledge about options specified during project creation is also why the FeedbackHubLink  doesn't support right-click. Addressing the ability to know/remember/work-out what was specified on original project creation will also be important for #663

**Comment by ralarcon** [comment]
I would like @sibille to join the discussion but she is on hollidays till next week.

By the way, would it make sense to improve the navigation service with a "Home" page property?

**Comment by ralarcon** [comment]
To mention that, initially, to improve the ActivationHandler make sense. Just want to understand the implications if any as this is one of the most core parts...

**Comment by mrlacey** [comment]
> would it make sense to improve the navigation service with a "Home" page property?

This would remove the issues relating specifically to needing to know about the "Home" page but not the wider issues around knowing more about what was specified when the project was created which will need to be known for adding right-click to the feedback hub link (needs to know what the settings page is called) and if we add the ability to make any UWP app right-click enabled.

**Comment by sibille** [comment]
Regarding the question if we should modify the Default Launch Activation Handler or have a method on the NavigationService that allows to navigate to the home page I think both approaches are valid. Including we could provide the two options. 

The only thing is that if we go for the Default Activation Handler, we should rename the DefaultLaunchActivationHandler to DefaultActivationHandler and make it available for all type of ActivationEventArgs (currently it is only used for LaunchActivation)

**Comment by mrlacey** [comment]
Yes, any change would need to come with some renaming.

---

A `NavigateToHomePage()`  method raises more possibilities/questions. Should it Navigate forward to that page or back? What if there are multiple instances of it already on the back stack? Should getting to the home page forcibly clear the back stack?  What if someone wanted to add required parameters to their home page navigation?   
I think the only way to deal with these (and probably more) questions is by providing a number of overloaded methods and configurable options.  
The problem with doing this is that:
- it means we're including code that a lot of people won't ever need.
- we'll need more documentation to explain the different options.
- there's more potential for confusion, and therefore support, if there are multiple options and someone uses the "wrong" one but can't work out why.
- it feels like coming close to creating some sort of general navigation framework. Such a thing is beyond the aims/scope of WTS.

I think I've just convinced myself it's not a good idea to go this route.

**Comment by ralarcon** [comment]
Regarding the Navigation service and the "home page", I was simply thining in having a property in the navigation service pointing to the "HomePage" so, when required, any one can implement the way to navigate to the home page under their preferences...

**Comment by crutkas** [comment]
This has been here for a bit, any chance we can drive a resolution to it?

**Comment by sibille** [comment]
I liked the idea of the Default Activation Handler, that handles activation if no other activation handler handled it. We can study this for 3.0.

**Comment by sibille** [comment]
Looking into DefaultActivationHandler together with #2814 in 3.2

**Comment by mvegaca** [comment]
Working on it on [this branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue1097-activation).

You can see the result of how is going to works on this generated app.

[DeepLinkingWithDefaultActivationHandler.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/3068112/DeepLinkingWithDefaultActivationHandler.zip)

With this change, DeepLinking and also UserActivity (TimeLine) will be available from the  right click :)

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19160.1
Wizard version: 0.20.19160.1
