### ISSUE TITLE
Review Localization Tool

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1123]
Todo: 
- [x] EULA files should be excluded as they are already localized.
- [x] Adapt Extension.vsixlangpack, correct link to license is <License>..\Content\EULA.[language].rtf</License>.
- [x] Maintain the encoding of files when copying.
- [x] Include a way to determine which files are suitable to need localization since a certain date.

**Comment by ralarcon** [comment]
Adding one item more to the TODO list related to #646.

**Comment by mrlacey** [comment]
Just to be clear, tooling for localized files for the VB versions of templates isn't needed as a separate script handles copying of text from the C# equivalents.

**Comment by ralarcon** [comment]
You mean as initial task? I understand that, when ready, localization process will be the same (templates in general)...

**Comment by mrlacey** [comment]
Initially, the VB templates are just a copy of the C# ones with code converted.
Beyond that, some values are changed to be VB specific (such as Identity in the config file) which means they can't just be blindly copied in future.
Because of this, I have a script which will copy localized names and descriptions from the C# templates into their VB equivalents. If there are other properties of JSON files which need adding this can be done too.
Because the VB versions of templates will be versions of the C# ones there should be no need to translate the same text multiple times. 
As the C# templates are translated and updated, the changes can automatically be applied to their VB equivalents by running the script.
This allows for less text to be translated and no special work to be done to support VB other than creating and running this script.

I also chose this approach as the way the management of localized files will be managed isn't yet clear. Doing it this way means that whatever approach is chosen for C# doesn't matter for VB.

**Comment by ralarcon** [comment]
Verified
