### ISSUE TITLE
Add the ability to test right-click add functionality against projects created with older versions of the templates (& wizard)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1165]
Need a way to test that any changes to existing templates don't break the ability to do right-click add of a page or feature to a project created with an older version of the templates.

Will also need a way to generate reference apps from old [releases](https://github.com/Microsoft/WindowsTemplateStudio/releases) to use as a reference.

The general approach to authoring new templates is that they should be rightClickEnabled and that they should be compatible with projects generated with older versions of the templates.

If there are genuine cases where backward compatibility must be broken, this should be documented as an exception in the tests and not cause an unhandled exception in the wizard. The wizard should just treat it like a merge failure.

Specific details to be confirmed.

**Comment by sibille** [comment]
Approach here will be creating an empty project with the last published template version (for this milestone 1.3.17255.01) for each projectType and framework and then adding all pages/features per right click using the current template version. 
There will be an option to exclude templates from this tests, like webview in this milestone, because it requires Creator Update as min version. 

I'll add in a ManualOnly test also, that creates a project with all pages and features from the last published template version for manual tests.

**Comment by mrlacey** [comment]
@sibille Are these tests manual only for any particular reason?

**Comment by sibille** [comment]
@mrlacey I put manualOnly on that one, because what the test is doing is setting up projects for further manual tests. I generates legacy projects with all pages and features. The actual test will have to be done manually to see if warnings and errors shown are understandable. 
Maybe ManualLegacyTestSetup or sth like that would have been a better ExecutionSet, should I change it?

**Comment by mrlacey** [comment]
A rename or a comment explaining what they're for or that they're not actually for would probably be helpful.

For the VB work, I need to add some tests that should only ever be manually run as there are lots of scenarios where they will report false negatives. (i.e. they fail but that's ok.)
I was going to mark them as "manual only" but didn't want to make sure of the intention behind that execution set. 
If we keep the "ManualOnly" set for anything that needs human interpretation then that will be fine. We just need to ensure that any such tests are commented so that anyone looking at them knows why they're for manual execution only and what to do with the output.
