### ISSUE TITLE
"Cannot deserialize XBF metadata type list as 'ViewModelLocator' was not found in namespace 'App1.ViewModels'. [Line: 0 Position: 0]"

### ISSUE THREAD

**Issue by IngoBleile** [Microsoft/WindowsTemplateStudio#1181]
As soon as I add a reference to a very simple .NET Standard 2.0 class library, I am getting this error.

**Comment by mrlacey** [comment]
@IngoBleile what's the library you're adding? What options did you choose when creating the project? Have you changed anything else since creating the project?

**Comment by IngoBleile** [comment]
(I am using VS 2017 Preview 15.4, .NET core 2.0.2 preview, Windows 10 SDK Preview Build 16288)

- I changed the UWP app's "Target version" and "Min Version" to "Windows 10 Fall Creators Update 10.0 Build 16288). It works fine without the reference to another project.
- After referencing my .NET Standard 2.0 class library with an "public enum" declaration, the error occurs. When I remove the enum declaration or just the "public" keyword, it works.

**Comment by crutkas** [comment]
can you provide a repro?  Does this same behavior happen with a file-> new?

**Comment by IngoBleile** [comment]
I am giving up. Never ever did I experience so many crazy and unpredictable errors. I am too old to taking part in preview programs. I prefer making my customers wait another half a year in order to proceed development. Anyway, thanks crutkas!

**Comment by IngoBleile** [comment]
Closed by frustration.

**Comment by crutkas** [comment]
We treat stuff like this very serious but we need a way to hook a debugger into it / reproduce it. If you can provide step by step or a WTS project with the issue, we can start poking into it

**Comment by IngoBleile** [comment]
![23-09-_2017_00-44-00](https://user-images.githubusercontent.com/1170322/30766895-79b1085a-9ff8-11e7-8851-3b856a531dd1.png)

[ClassLibrary1.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/1326028/ClassLibrary1.zip)

**Comment by IngoBleile** [comment]
You can connect via Teamviewer at any time, just let me know.

**Comment by IngoBleile** [comment]
The problems are related to the build configuration but I can't figure out the right one.

**Comment by RavinduL** [comment]
Hiya!
I'm facing a problem very similar to this one. I've written a question about it on Stack Overflow here: https://stackoverflow.com/q/46501682/2466716

**Comment by IngoBleile** [comment]
Even with the most current Win 10 preview (1709 Build 16299.15), VS 2017 15.4 Preview 6 and the most current Windows Template Studio (1.1), I am having the same issues.

1. The generated app >> works fine
2. I add a new project (.NET standard 2.0 class lib) with some model classes >> everything works fine
3. I add a new project (.NET standard 2.0 class lib) with a cs file with some public enums and some public classes >> I am getting the runtime error "Cannot deserialize XBF metadata type list as 'ViewModelLocator' was not found in namespace 'App1.ViewModels'. [Line: 0 Position: 0]" as soon as the app is starting
4. I comment out every class content, even the class declaration itself >> same error
5. As soon as I remove the reference to the lastly added project, I am getting the "Could not copy files ..." error shown above, I cannot build
6. "Clean", "rebuild all" doesn't help

Very frustrating.

**Comment by ralarcon** [comment]
The latest version published version from [Windows Template Studio is 1.3](https://marketplace.visualstudio.com/items?itemName=WASTeamAccount.WindowsTemplateStudio). I'm going to try to make a repro with that version and with the current pre-release (1.4 will be published soon)

**Comment by crutkas** [comment]
Can someone provide a repro so we can throw a debugger against it and see diffs between generated code and modifications made

**Comment by IngoBleile** [comment]
It's quite easy, takes just one minute.

1.  Create a new app with "Pivot and Tabs" & MVVM Light & all the features from the "Select pages and features" page.
2. Change the project properties to Target a current Win 10 Fall Creator's Update's release (e. g. Build 16299), Target Version & Min Version. Start the app >> works perfectly.
2. Create a new .NET standard 2.0 class library project.
3. Change the created class like that:

using System;

namespace ClassLibrary1
{
    public enum MessageType
    {
        Info,
        Warning,
        Error
    }
}

4. Reference the class library from the UWP app.

>> The error occurs when the execution leaves the App() constructor.

**Comment by ralarcon** [comment]
Hi,

I been able to reproduce this behavior using the v1.3 of Windows Template Studio.

I've verified that the issue is not constrained to MVVM Light. If you chose the combination Blank + Code Behind you'll have the same behavior. I've found a couple of references related to this, [one](https://developercommunity.visualstudio.com/content/problem/106652/cannot-resolve-assembly-or-windows-metadata-file-t.html) which explictly mention that this is not a bug.

The root cause is related to a version inconsistence with NET Standard libraries used by the UWP app (created with WTS) and the NET Standard class library. 

If you are using the v1.3 of WTS and the latest win SDK (16299), you can get rid of this issue by changing the Microsoft.NETCore.UniversalWindowsPlatform reference from 5.2.3 to 6.0.1 in the .csproj file
_Before:_
![image](https://user-images.githubusercontent.com/2638875/31547486-ce9f8c58-b027-11e7-9ee1-1c2efcc8c5ac.png)

_After:_
![image](https://user-images.githubusercontent.com/2638875/31547516-ed82e732-b027-11e7-8590-4d339b28b969.png)

Or you can take advantage of the recently launched pre-release version of Windows Template Studio where we released recently and now targets the latest 16299 sdk and 6.0.1. ([v0.9.17286.1 or higher](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio)).

Hope this helps.

**Comment by IngoBleile** [comment]
That's good news, I'll try it later. Thanks a lot so far.

**Comment by crutkas** [comment]
can this be closed out?

**Comment by ralarcon** [comment]
I think so!
