### ISSUE TITLE
Treeview based on master/detail Page

### ISSUE THREAD

**Issue by crutkas** [microsoft/WindowsTemplateStudio#1246]
A user made a great request.  #1237

We have navview, tabbed, and blank.  A treeview is a common pattern and maybe we should think / come up with a POC of what this may look / act like

**Comment by mrlacey** [comment]
Why a nav option and not a page?
Seems more like a variation on master/detail but with a treeview.
Of course, we may want to wait for the official treeview control to finally ship before doing this.......

**Comment by crutkas** [comment]
I agree actually after thinking about this for a bit.  It feels much more master detail based

**Comment by mvegaca** [comment]
This is a great idea but a treeview need to define navigation items in navigation items groups and to add we will need to think about how user specify those groups and decide what page must been on each group. We could also add only one group and generate all pages on the same group. Or create one group for each page type: Maps, Galleries, etc.

**Comment by mrlacey** [comment]
My comparison to Master/Detail was more to highlight that it feels more appropriate to put this as a page rather than a project type.
"MasterDetail" is a perfectly valid navigation pattern and project type. We don't make this a project type though. However, it would be easy for an app to be developed with WTS that does this. Just create a blank app with a single MasterDetails page.

I am not proposing that any page based on a TreeView control (when it finally ships) should directly mimic the "Master" part of the MasterDetails page/functionality.
If we started building navigation functionality into a page with a TreeView control on it that would be being too specialized.

Let's wait until a final version of the control is released and then we can discuss what is best to include on a page with one.

**Comment by mvegaca** [comment]
Agree

**Comment by mrlacey** [comment]
Needs a new data type in sample data - TBD.
Assuming this control will be in WinUI library to give the version level support we want for including this.

**Comment by mvegaca** [comment]
TreeView Proof of concept is ready for review on [this branch](https://github.com/mvegaca/TreeViewPoC/tree/dev). This is a first approach and we would like to get some feedback from WTS users.

We have added more detailed SampleData to show a hierarchical model (Company / Orders / OrderDetails). These data enhancements will also improve other pages that use sample data like MasterDetial or Data Grid pages.

**Comment by mvegaca** [comment]
TreeView page short and long description proposals:

**Short description (shown in card)**

The tree-view page has a tree view control to show hierarchical content.

**Long description (shown in details page)**

The tree-view page has a tree view control to show hierarchical content. When an item in the tree view is selected, it's details are shown in a details pane. This pattern is frequently used to show hierarchical relationship between items.

More information about the tree-view control can be found [docs.microsoft.com](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/tree-view).

**Comment by mvegaca** [comment]
We're trying to integrate the new TreeView page with data from SQLServerData service.
For the TreeViewPage we've added companies and products data (apart from orders) to the SampleDataService to create 3 levels of tree indentation.
We think we should get the same data from the SQLServerData service, we've added a PoC that connects the new TreeView page with SQL Feature.

[TreeViewSqlSupport.zip](https://github.com/microsoft/WindowsTemplateStudio/files/3350629/TreeViewSqlSupport.zip)
Can you have a look on that @mrlacey?

**Comment by mrlacey** [comment]
Feedback:
- Move the dates of Sample Orders to more recent. Having dates from 1997/8 is weird.
- If changing SampleOrder.OrderId to an `int` rather than a `long`, will need to make changes to WebAPI.
- `SqlServerDataService.AllOrders()` should be called `AllOrdersAsync()`
- `SqlServerDataService.AllCompanies()` should be called `GetDataAsync()` so that it matches what's in the SampleDataService as the comment suggests.
- What does ` // Not  null value` mean in the SqlServerDataService? If it's just to call out a value that isn't nullable is it really needed?

**Comment by sibille** [comment]
Thanks @mrlacey, we'll apply those changes when doing the template adoptions!
Not sure about the first one, we took the dates from the Northwind database, to not run into any compliance issues. Think we should leave them as they are in the datasource.

**Comment by mrlacey** [comment]
The current sample Data was created based upon Northwind but I modified a few things, especially the dates.
Sample orders for >20 years ago seems very strange outside of the context of a 20+ year old sample database.

**Comment by mrlacey** [comment]
Also, for the sample data, it would be good to put back the comments explaining what the symbol codes reference.

Old/current version had comments like this:

```
                    Symbol = (char)57643 // Symbol.Globe
```

**Comment by sibille** [comment]
@mrlacey, I'm looking at how to adapt the Web API Service to return data for the TreeView. 
I've done a mock where I adapted the ItemController to do the CRUD with SampleCompany and added a new endpoint for getting orders. 
[App213.zip](https://github.com/microsoft/WindowsTemplateStudio/files/3359592/App213.zip)

Could you have a look?

**Comment by mrlacey** [comment]
looks fine

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19192.1
Wizard version: 0.20.19192.1
