### ISSUE TITLE
Cant found  option to change MousOver Color fom a Buttom

### ISSUE THREAD

**Issue by harrypotter06** [Microsoft/WindowsTemplateStudio#1247]
Hello,

my Project is created with WTS.
Now i have i issue, if i change the Theme. On Dark Theme the "MouseOver" from a Buttom, i can nothing see from te buttom, if i go with the mousepointer over it.

How can i change it? In VS2017 i didn't found a option to change it.

* **VS Version: 2017
* **Windows Build: 15063

**Comment by crutkas** [comment]
Can you provide a repro and screen shots?

**Comment by harrypotter06** [comment]
At this Moment, i have a other Solution (no color change, if user change the Theme)

**Comment by mrlacey** [comment]
@harrypotter06 we'd still like to know what the cause of the issue was. It's good that you've found a solution but others may need it too and if there's something wrong in the generated code it needs fixing. Similarly, if the generated code is doing something that is preventing you from styling your app the way you want that needs to be addressed also.

**Comment by harrypotter06** [comment]
The Issue:

On XAML i defined Background in white. The "Button" will be change his color, if the Theme of Windows change. Did you use a dark theme, and you go "MouseOver" on the Button, you can't see the Button, because the Background is white.

What i missing, is a Point, how can i change the MouseOver Colors in Visual Studio XAML Designer.
For my solution, we use fixed colors for the Button now ...

**Comment by crutkas** [comment]
@harrypotter06 without actually seeing the xaml, really hard for us to help.  If you're hardcoding colors, that could conflict with the system theme colors

**Comment by mvegaca** [comment]
I've add a PR #1255 with Theme Selection fixes and I think that it can also solve this Issue. Can you can this on next Dev Nightly @harrypotter06 ? The PR add a Control Style to all pages and controls with a definition for BackgroundColor ApplicationPageBackgroundThemeBrush

**Comment by crutkas** [comment]
@mvegaca we need to verify what @harrypotter06 issue actually is under the hood before we claim we fixed something.  I have a theory of what this is

**Comment by harrypotter06** [comment]
@crutkas - missing the option, to configure this. That's all, i think.

**Comment by harrypotter06** [comment]
@mvegaca - this is not a Background issue, this is a issue on "MouseOver"

**Comment by crutkas** [comment]
@harrypotter06. We would really love to help out here but right now we lack enough information to properly validate what the issue is. Without pictures or a movie and something we can throw a debugger against, it is unclear what the issue is. 

I read the issue and sounds like you are having a styling issue and want to do something when an item is hovered over. 

We really need a sample and a bit more information on what you expect to happen VS what is happening.

**Comment by harrypotter06** [comment]
Hi,

sorry, i search only a option to change the "MouseOver" Color on a "Buttom" Object in VS2017
Hope, next time i can send you a movie, where i searching this option in VS :) 
Sorry - joke

Yes, in next time, i will continue in this project and add new buttons, so i can make a movie that show the issue.
