### ISSUE TITLE
Progress Dialog Feature

### ISSUE THREAD

**Issue by pw3107** [Microsoft/WindowsTemplateStudio#1282]
A cross platform progress dialog when the Xamarin version comes out would be nice.

**Comment by mrlacey** [comment]
Can you expand more on what you're after?

Do you just want some generic activity indicator?
Should this be a specific page? And, if so, what else should be on it?
Could this be a popup/overlay on top of another view/page?
How would this integrate with other functionality?
In terms of what gets generated for this, would progress indicated by a timer be sufficient? along with a TODO note that this should be replaced with appropriate, time-consuming code?

**Comment by pw3107** [comment]
Matt,
         Thanks for the reply. I was looking for a progress dialog that blocks the user from doing anything until the activity is finished. Template 10 has a progress type page that shows an activity ring with a message while an activity is running. On completion the dialog would disappear and the user can navigate in the application as normal. My experience of Xamarin is that this is a bit of a pain and I have not found a good cross platform solution.

P.S. Great job on Windows Template Studio. I have been waiting for years for a quality code generator. The internet is full of useful information but when learning to code something like Windows Template Studio is perfect for learning how to code to a pattern correctly and consistently.

Thanks
Paul.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mrlacey** [comment]
I'm reluctant to include such functionality as it's easy to implement from a development perspective but typically provides a sub-par user experience.

It is normally better for the person using the app if they can continue working while work continues in the background rather than have to wait for the app to complete a task before continuing. There are situations where the user must wait but these are normally smaller in number. 
My problem with the above-described functionality is that it often becomes a hammer for developers. It's easy to implement and makes the developer's life easier as they don't have to worry about async callbacks and possible race conditions but it provides a lower quality experience for the people using the app. 
There needs to be a balance between creating things that make life easier for developers as well as providing utilities for making it easier to create a great app experience.

We can consider if there's a large demand for this but it's not a priority.

**Comment by pw3107** [comment]
Matt,
         Thanks for the reply and reasoning. It was just a thought as I liked the one in Template 10.

Regards
Paul.

Sent from my Windows 10 phone

**Comment by crutkas** [comment]
closing this out, we're not at xamarin right now and no one else has requested this.

**Comment by crutkas** [comment]
please reopen if someone feels differently
