### ISSUE TITLE
New feature suggestion: A rate this app dialog

### ISSUE THREAD

**Issue by johanlindfors** [Microsoft/WindowsTemplateStudio#1314]
I would like to suggest adding a "rate this app" service and dialog which can be called similar to the "What's new" dialog. This service would handle making sure the dialog isn't popped to often, also when the user have actually decided to give a rating in Store, the dialog would be dismissed entirely (even though we can't really be certain that a proper rating was provided).

It's super important to be able and to drive users to rate the app when they are in a good mood, meaning that a simple pattern for calling this dialog (as mentioned above) is crucial. I have experience first hand that users is most likely to give a bad rating in the Store when the app have crashed or similar, not as much likely to just head in there and give a good rating, unless we help them when they are motivated.

**Comment by mrlacey** [comment]
I've just added some logic to the [UWP Community Toolkit](https://github.com/Microsoft/UWPCommunityToolkit/issues/1505) to make doing this easier but we won't and can't go all the way and add code that displays the prompt for you.
The reason for this is because we don't know when the best time to show the prompt will be as this varies for each individual app.

When should such a prompt be displayed? It's not the same for every app.

How you ask can also vary. It may be appropriate to display a modal dialog. It may be more appropriate to use another internal notification, include it within the body of the content, or at the end of a flow. It depends on the app.

My big concern, and why we didn't do this with the toolkit, is that if we included something that showed a dialog on the Nth time the app was launched (a crude, common pattern), developers would assume this is what they should do and do that in their app.
Showing the prompt at this time is one of the worst moments to ask (aside from around errors).
- It doesn't account for if they've yet got any value from the app.
- What the number of N should be will vary by app.
- The number of times an app is launched may or may not be indicative of anything. If launched several times but not able to do anything as each time the device was offline, then this isn't helpful.
- The frequency of app launches must also be considered. If launching the app many times in quick succession this may indicate another problem and so not be a good time to ask. If it's the first time the app has been used in a while, that may also be a bad time to ask.
- People don't launch apps to review them, they launch them to get some form of entertainment or value. If you show an extra prompt when launching the app it puts an extra barrier between the person and what they launched the app for. This is unlikely to encourage positive feedback.

The hope is that the new [SystemInformation](https://github.com/Microsoft/UWPCommunityToolkit/blob/master/docs/helpers/SystemInformation.md) functionality that is coming to the toolkit will help developers do what's right for their apps. 
I'm exploring ideas about how best to integrate some of this into WTS but don't have any definite answers on what we should do yet, only what we shouldn't. Suggestions welcome.

**Comment by johanlindfors** [comment]
Thanks for the quick respons, however I still believe the logic and behavior of the rate dialog could be absolutely valid to include in the template. With that said, I totally agree that the choice on WHEN to display the dialog is up to the developer and with proper commenting the code could simply display HOW the call could be made.

The pattern on WHEN is not easily generically implemented.
