### ISSUE TITLE
No PointerOver & Pressed VisualStates visible in Navigation Pane

### ISSUE THREAD

**Issue by ThomasPe** [Microsoft/WindowsTemplateStudio#1327]
### Repro steps

Create a new UWP Project with Navigation Pane and some pages.

### Expected Behavior

When hovering and clicking the menu items in the Navigation Pane the VisualState changes should be visible (different background colors).

### Actual Behavior

No background color changes on PointerOver & Pressed.

This is probably caused by adding an additional background to the ListView Item template.
https://github.com/Microsoft/WindowsTemplateStudio/commit/8ed03b3e95619777362da5f95536fcf90b7558c6#diff-1d7062722815b44e736ce1b0a5ff1e4a

Earlier discussion:
https://github.com/Microsoft/WindowsTemplateStudio/issues/1137#issuecomment-338487421

## System

* **VS Version:15.4.1**
* **WTS Template Version:1.4.17291.5**
* **Windows Build:15063.674**

**Comment by mrlacey** [comment]
It doesn't appear to be the background brush that's the issue, rather than the VisualStates on the data template aren't being triggered.

**Comment by ThomasPe** [comment]
well if I remove the brush they get triggered ;-)

**Comment by mrlacey** [comment]
The way the HamburgerMenu control highlights the selected item doesn't work with the way the WTS generated code works. It makes it possible for items in both the top and bottom lists to be highlighted at once and it also doesn't work properly with the back button such that multiple items can indicate selection at once.

In the data template in the ShellPage, the grid background is set to hide the behavior of the underlying control and we handle indicating the "selected" item separately.
It seems that when switching to the toolkit control from using the SplitView control ourselves, the VSM in the stopped working as it was moved into a datatemplate and this wasn't noticed. 

The challenge is to recreate the highlighting behavior that exists in the underlying control but not bring the incorrect highlighting of the selected item.

**Comment by ThomasPe** [comment]
I see, thanks for the clarification

**Comment by mrlacey** [comment]
I'm not sure the best long-term solution for this but I do have a hacky workaround for the issue. 
This prevents the underlying behavior of the control rather than trying to hide its effect. 

There are two steps, the second of which is framework dependent.

Step 1. Remove the background from the grid in the XAML (and the VisualStateManager code for that grid too as it's not used.)

**Code Behind**
Step 2. At the end of the `Frame_Navigated` method on ShellPage.xaml.cs add

```csharp
    NavigationMenu.SelectedIndex = -1;
    NavigationMenu.SelectedOptionsIndex = -1;
```

**MVVM Basic or MVVM Light**
Step 2. Handle the Navigated event of the Frame in the constructor of the `ShellPage` and use that to reset the selected index and remove the native selected indicator.

```csharp
    public ShellPage()
    {
        InitializeComponent();
        DataContext = ViewModel;
        ViewModel.Initialize(shellFrame);

        // Hacky fix to stop HamburgerMenu showing multiple selected items
        shellFrame.Navigated += (s, e) =>
        {
            NavigationMenu.SelectedIndex = -1;
            NavigationMenu.SelectedOptionsIndex = -1;
        };
    }
```

**Caliburn.Micro**
Step 2. Handle the Navigated event of the Frame in the constructor of the `ShellPage` and use that to reset the selected index and remove the native selected indicator.

```csharp
    public ShellPage()
    {
        InitializeComponent();

        // Hacky fix to stop HamburgerMenu showing multiple selected items
        shellFrame.Navigated += (s, e) =>
        {
            NavigationMenu.SelectedIndex = -1;
            NavigationMenu.SelectedOptionsIndex = -1;
        };
    }
```

I'm not going to submit a PR for this as it feels a bit too crude. There should be a better way of doing this but it'll mean adding another reference of the View to the VM but that seems like more than should be necessary. 
Also, when we fully switch to the NavigationView control in future this workaround should become unnecessary,

**Comment by ralarcon** [comment]
Should we move this to the backlog for future review as we will be moving to the NavigationView as soon as the toolkit do it?

**Comment by ralarcon** [comment]
Moving to backlog waiting NavigationView being integrated.

**Comment by crutkas** [comment]
is this something we need to do for nav view or does it do the correct behavior w/ nav view.  If nav view by default does the correct behavior, we should close this out since with the next update, we'll be on NavView 100%

**Comment by mvegaca** [comment]
I was checking mouse over and mouse pressed visual effects in the new version using Toolkit 2.1.1.
We've added a UseNavigationViewWhenPossible property that allows the app to use NavigationView if the machine is running Fall Creators Update of SplitView if it's running older versions of Windows 10.
It looks great even in NavigationView and SplitView.

**Comment by crutkas** [comment]
@mvegaca so you're saying in 1.6 this isn't an issue anymore?

**Comment by mvegaca** [comment]
I think yes but would be great if @ThomasPe could do a  double check on 1.6 release before closing the Issue.

**Comment by ThomasPe** [comment]
I'll take a look as soon as possible
