### ISSUE TITLE
Spanish translation composition cause grammar error

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1381]
Right click title is currently composed bt two different string resources: "Add new" + ("page" or "feature").
In Spanish translation, it applies a translation genre issue. We need to change that for two different string resources: "Add new page" and "Add new feature".
As a temporary workarround we can add a " : " 
"Add new: page"

![image](https://user-images.githubusercontent.com/5556784/32320849-63552320-bfbf-11e7-9223-e73f6ee0a211.png)

**Comment by ralarcon** [comment]
The issue is that the genre for "Agregar nuevo" (male) is not aligned with "característica" (female). The root cause is that the wizard page title is a composition of "Add new" and the kind of item "page" or "feature". This would happen in other languages but not sure in how many. A workaround for spanish would be to include ":" between the two part, this make the sentence do no require the genre coordination.

**Comment by crutkas** [comment]
can we raise this with the translation company?  Seems like they should have caught this, no?

**Comment by crutkas** [comment]
or is it cause we ourselves broke the grammar into two different items

**Comment by mvegaca** [comment]
Fixed on #1393

**Comment by dgomezc** [comment]
Verified on dev-nightly:
Wizard: 0.14.17310.65001
Templates: 0.14.17310.1
