### ISSUE TITLE
ShellPage is instantiated on BackgroundTask activation while app is terminated

### ISSUE THREAD

**Issue by snrnats** [Microsoft/WindowsTemplateStudio#1533]
### Repro steps

1. Create a new app using **Windows Template Studio**.
2. Choose **Navigation Pane** and add a **Background Task**.
3. Open project properties and check **Do not launch, but debug my code when it starts**  in **Debug tab**
4. Start Debugging the project.
5. Start the app outside the VS and close the app (it will register the background task).
6. Start the background task from **Debug Location Toolbar** (background task must start while the app is terminated)

### Expected Behavior

ShellPage shouldn't be instantiated when the app is started only for background operation.

### Actual Behavior

ShellPage is instantiated in ActivationService constructor. It causes additional overhead for background task. It can get event worse depending on code executed with ShellPage initialization. For example some UI related method can throw an exception (e.g. **DisplayInformation.GetForCurrentView()**) when they are called in background task.

## System

* **VS Version:** 2017
* **WTS Wizard Version:** 1.5.17334.7
* **WTS Template Version:** 1.5.17334.7
* **Windows Build:** Any

**Comment by mvegaca** [comment]
Thank you @snrnats 
We are working on it.

**Comment by mvegaca** [comment]
Adding fix on #1537 Missing Caliburn.Micro framework

**Comment by crutkas** [comment]
is this affecting all frameworks and project types?  do we know how far back it goes?

**Comment by ralarcon** [comment]
If not wrong, this was affecting all frameworks but only navigation pane project type, from the beginning. Now we have a fix which will be available in the next release. 

As it was affecting the project template, the fix will not repair existing projects. @mvegaca will add detailed steps to manually workaround / fix existing projects in this issue.

**Comment by mvegaca** [comment]
It isn't fixed in Prism Framework when the app is closed the container is not configured and even if I try to configure it, configuration crash on base implementation (dll code).
@LeeParrishMSFT could you please have a look on Prism implementation following bug reproduction steps?

**Comment by mvegaca** [comment]
For all users that have already created a Navigation Pane project using background task, here is the changes that you should add to fix this bug.
Shell page should not be created unless the ActivateAsync method in ActivationService class is called from application launching or application activation. When the background task is running code while the app is closed the Shell page should not be created.
We have change the ActivationService constructor to recive a Lazy of UIElement instead of UIElement in shell parameter. With this we add a delay on Shell page creation, the shell creation ocurs exactly when is needed.

**ActivationService.cs**
```csharp
// ActivationService _shell propery definition
//
// Old code
private readonly UIElement _shell;
// New code
private readonly Lazy<UIElement> _shell;
```
__________________________________________________________________
```csharp
// ActivationService Constructor
//
// Old code
public ActivationService(App app, Type defaultNavItem, UIElement shell = null)
{
     _app = app;
     _shell = shell ?? new Frame();
     _defaultNavItem = defaultNavItem;
}
// New Code
public ActivationService(App app, Type defaultNavItem, Lazy<UIElement> shell = null)
{
     _app = app;
     _shell = shell;
     _defaultNavItem = defaultNavItem;
}
```
__________________________________________________________________

```csharp
     // Using _shell property
     //
     // Old code
     Window.Current.Content = _shell;
     // New code
     Window.Current.Content = _shell?.Value ?? new Frame();
```

**App.xaml.cs**

```csharp
// ActivationService Lazy Creation
//
// Old code
private ActivationService CreateActivationService()
{
     return new ActivationService(this, typeof(Views.Param_HomeNamePage), new Views.ShellPage());
}

// New code
private ActivationService CreateActivationService()
{
     return new ActivationService(this, typeof(Views.Param_HomeNamePage), new Lazy<UIElement>(CreateShell));
}

private UIElement CreateShell()
{
     return new Views.ShellPage();
}
```
Detailed list of all changed files [here](https://github.com/Microsoft/WindowsTemplateStudio/pull/1537/files)

**Comment by mvegaca** [comment]
Checked fix on:
Wizard: 0.14.17353.65002
Templates: 0.14.17353.2
