### ISSUE TITLE
StoreNotificationsService doesn't cache initialization

### ISSUE THREAD

**Issue by r2d2rigo** [Microsoft/WindowsTemplateStudio#1544]
### Repro steps

Create a new project that includes the `StoreNotificationsService` component.

### Expected Behavior

The service is initialized once.

### Actual Behavior

The `ActivationService` calls its `ActivateAsync` function whenever the app is activated - be it from first run, file association, etc. This in turn calls `InitializeAsync` which initializes the instances of the services it depends on.

The problem is that the initialization for `StoreNotificationsService` is called again each time, and in some cases it can take 2-3 seconds to execute, blocking the rest of the app. This service should cache if it has been already initialized and if so, skip initialization entirely.

## System

* **VS Version:** 15.4.4
* **WTS Wizard Version:** 1.4.17291.5
* **WTS Template Version:** 1.4.17291.5
* **Windows Build:** 10.0.16299.64

**Comment by mvegaca** [comment]
Thanks, @r2d2rigo for the Issue report.
RegisterNotificationChannelAsync call should not be skipped using cache verification as it's explained in the [documentation](https://docs.microsoft.com/windows/uwp/monetize/configure-your-app-to-receive-dev-center-notifications).

> Get a StoreServicesEngagementManager object and call one of the RegisterNotificationChannelAsync overloads in the startup code you identified earlier. This method should be called **each time that your app is launched.**

That said, what you said is 100% valid. Considering this, we have added a fix in #1546 to Initialize the StoreNotifications within StartupAsync method instead of InitializeAsync in ActivationService. With this change, RegisterNotificationChannelAsync does not lock the UI while initialization.

**Comment by sibille** [comment]
Missing for VB

**Comment by crutkas** [comment]
@sibille should we create a VB dedicated item for this?

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.14.17353.65001
Templates: 0.14.17353.1
