### ISSUE TITLE
Improve multi-view comments / docs page

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1607]
Multi-view needs additional comments / guidance on implementation.  It should be straight forward what a person needs to do from our to-do's versus pointing to just documentation on docs in MSDN where the implementation in WTS differs so an end user would need to tweak stuff.

#241 was where this spawned from

**Comment by touseefbsb** [comment]
@mvegaca  @crutkas   
**Following are the possible scenarios for the developer to use this implementation.**

1. one main window of app is able to open multiple secondary windows and then talk to them i.e : exchange data with them, and any of the secondary windows can be closed at any given time without effecting the main window or other secondary windows. 

2. Also When the main window closes the developer can have the option to close all secondary windows as well, or leave them open. if this is technically possible, then maybe we can have a boolean value to set this behaviour or maybe an enum. Also if the main window is closed and secondary window remains opened, secondary windows can have a button or link which can open the main window once again. I am not sure whether this is possible but this is just a suggestion for better experience for both user and developer.

3. Another important thing to point out is when the secondary window or main window is closed, how can developer free all the resources which that specific window was using, so that it wont cause any exception on closing the window and also app wont use any extra system resources after closing of the window.

**I hope this helps and we can discuss it further and improve the approach to creating better documentation. Thanks**

**Comment by touseefbsb** [comment]
@mvegaca  @crutkas  any update on this?

**Comment by michael-hawker** [comment]
Yeah, I'm not seeing the window handles being cleaned-up after I close a secondary window.  It appears the `WindowManagerService` will keep the reference alive with the `SecondaryViews` collection, no?

**Comment by mvegaca** [comment]
Working on a markdown documentation for multiple views feature. It can be checked [here](https://github.com/mvegaca/WindowsTemplateStudio/blob/Issue1607-multiview-doc/docs/features/multiple-views.md).

**Comment by mvegaca** [comment]
Doc added on #2169
