### ISSUE TITLE
Wizard: Accessibility review

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1674]
Points to review and ensure that it works fine or fix if needed.
- Hight Contrast
- Keyboard accessibility
- Narrator voice accessibility
- Mouse over tooltips

**Comment by mrlacey** [comment]
Documentation for how to do such reviews are also needed.  
An ability to automate some (or all?) of this testing would also be beneficial so as to avoid any future regressions or new additions or extensions to the wizard that may have accessibility issues.

**Comment by ralarcon** [comment]
It is in the [Accesibililty](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/accessibility.md) documen, linked in the [Contributing](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/CONTRIBUTING.md#a-good-pull-request) doc. 
If not wrong, it is shown too in the PR template.

**Comment by dgomezc** [comment]
Finalized accessibility review, I have found and corrected the following errors:

- High contrast: There are some color combinations that do not look correctly in high contrast and we have decided to separate it into another issue (#1887).

- Keyboard accessibility: 
  - From left menu, press tab key and navigating to the first page item, press enter key does not add the page to the user selection. This behavior also occurs when selecting the first project type, design pattern and feature.
  - In the change summary window, when navigating with the tab key, the panel on the right that contains the changed file list takes the focus.
  - When navigating with the tab key and reaching the last focusable element (cancel button), you must press tab key twice to return to the first element (some element takes the focus before returning to the first element).
  - The project types and design patterns comboboxes do not obtain the focus correctly.
  - If we navigate with the tab key to the project type selection combobox, open it by pressing the space key and press esc, the focus returns to the first element of the screen instead of staying in the combobox. This operation is also given in the design pattern selection combobox. It also happens when use enter key to select item.
  - When navigating to the detail hyperlink of a page or feature card, and pressing enter, navigate to the details window but add it to the user's list of pages.
  - The button to delete the pages or features selected by the user is not acciseble when navigating through the keyboard. (#1876).

- Narrator support: The narrator does not read correctly the next elements:
  - Steps items to left panel.
  - Cards (projects types, design patterns, pages and features).
  - Comboboxes items (projects types, design patterns).
  - Selection users items.
  - Change summary file list items.
  - Cards details hyperlink.
  - Detail back button hyperlink.
  - About hyperlink.

- Mouse over tooltips: All the elements that need tooltip have them.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18046.3
Wizard version: 0.16.18046.1
