### ISSUE TITLE
Add native Multi-Instance support

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#1977]
Add support for natively having multiple instances of an app.

Relies on new APIs in RS4

As announced in https://channel9.msdn.com/Events/Ch9Live/Windows-Community-Standup/Kevin-Gallo-February-2018

**Comment by touseefbsb** [comment]
@mrlacey Just had a random question in my mind about this feature as it is still in preview.
will we be able to do adaptive code with this feature? I mean can we have an app which has minimum version as say "Creators Update" and target version as RS4 ( which has multiinstace support )? if yes then for that how will we adapt the app to support multiple sdk versions? the reason I am asking this is because adaptive code in this scenario might be a bit different, as the multi instance chances the way app is launched or initialized, so where exactly will we be needing to put that **if statement** to direct the app towards the older versions ( before RS4 ) or direct it towards rs4 depending upon the users OS version?

**Comment by crutkas** [comment]
For users not on it you would verify they meet the API contract before calling any code that touches multi instance.  Should be pretty straight forward I think (famous last words)

**Comment by touseefbsb** [comment]
yes I know we have to do API contract check I was just wondering, which are those APIs which touch multi instance? in xaml I think there is only one property in project manifest (allowmultiinstancessuport) , so we can put a check there with conditional xaml? but in c# I think the multiinstance template with redirection support does a custom main method, which is very different to traditional Onlaunched stuff hence it will be very different from the **Activation** scenarios currently supported by **WTS** that is why this question popped into my mind, so I wanted to be sure where do we touch the **multiinstance** apis in both cases ( normal multi-instance and redirectional multi-instance ) so when we know them we can simply put an api check on them.

**Comment by touseefbsb** [comment]
@crutkas  as we discused on twitter, hopefully a sister project will be coming for these checks in c# but until that comes, we need to take care of it the old way :)

**Comment by crutkas** [comment]
Multi instance concept is in the 1803 update.  Have you looked at the multi instance samples/docs?

**Comment by touseefbsb** [comment]
yes I have and I know they will be supported in 1803 and right now they are in preview. I'll wait for the official release of redstone 4 and then lets see how wts manages it in the templates.

**Comment by mrlacey** [comment]
@touseefbsb multi-instance support requires making specific entries in the manifest. Becuase the manifest does not support adaptive capabilities oft will not be able to make this an adaptive feature and will only be something we include when "RS4" becomes our minimum target.

**Comment by touseefbsb** [comment]
yes that is exactly why I asked this question because I was worried it wont be adaptive thanks for clarification @mrlacey  :)

**Comment by touseefbsb** [comment]
so basically until release of RS5 , we cant create multi-instace supported apps with wts? because supporting it requires rs4 as minimum? or can we add option in wizard to choose the minimum sdk and give option to make it multiinstance only if user selected rs4 as minimum? or would that be too much work ? @mrlacey  @crutkas 
even if we cant add multi-instace support right now as part of generated project, we still can provide a documentation page of how someone can include this feature themselves in their generated project. because we already have 2 blank template projects for multiinstance support with a VS extension, but integrating that code in wts generated project can be tricky as wts has a specific way of activation and navigation. so just like we have docs for "FileAssosiationService" we can also have docs for "Multi-Instance-Support" and we can let the developer know that after generating the project with wts , they should make the project minimum target to "rs4" and then follow following steps to include multi instance support in their app?

**Comment by crutkas** [comment]
We discussed how we may pull this off for supporting current release items at our team offsite last Thursday. Win UI library will aid in this for new UI elements. 

It wasn’t in out next few month release plan until October. We are prioritizing multi-project work currently since that will be a breaking change.

**Comment by touseefbsb** [comment]
@crutkas Oh ok. so I get it it cant be added in code generation for now, but can we add the docs, or would that also not be possible? Actually I was looking forward to using the feature and I also want to use WTS for all the other features, that is why even a small documentation would be very helpful. also can I get reference to where the multi project feature is being tracked?

**Comment by crutkas** [comment]
@touseefbsb  per before, we aren't not actively investigating this so we won't have docs / guidance.  This is why it is on our backlog and not assigned to a proper release.

docs.microsoft.com does however and the official samples do:  https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp

**Comment by mrlacey** [comment]
_for some reason this comment didn't save yesterday._

Docs exist at https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp
There should be no need for us to create additional docs.
If there's a problem with the docs that exist, provide feedback on the specific doc.
If there's something in a WTS generated project that makes this hard or impossible, then let us know here.

In response to some of your other points above:
- We will not put an SDK version picker in the WTS wizard
- Possible solutions for targetting newer features have been discussed and will be added to the backlog shortly
- Multi-project generation will be tracked in #2252

**Comment by touseefbsb** [comment]
@mrlacey yes the docs exist, but they exist for a blank uwp project not with wts, with wts we have a lot of moving parts with activation and navigation, and multinstance app have multiple features like, activating the same instance or create a new instace etc. also multi instance needs a main method to use to put the logic before all the activation or onlaunched even occur, that main method doesnot exist in wts generated projects.

**Comment by mrlacey** [comment]
Even a blank project doesn't include the `Main` method. 
If you want a template that does include it see https://marketplace.visualstudio.com/items?itemName=AndrewWhitechapelMSFT.MultiInstanceApps
Without having looked at it deeply (and for a few months), everything that happens at the Project.Main level happens before the `App` level code is executed and so there should be little issue. All the `ActivationService` level code in a generated project really only helps to separate code that would otherwise be combined within app.xaml.cs and there should be nothing that fundamentally stops a WTS generated project from having this functionality added.

Again, if the docs are unclear, ask for clarification there. 
If there is something specific in the WTS generated code that prevents the adding of true multi-instancing support we will take a look.

**Comment by mrlacey** [comment]
verified in 
Templates version: 0.20.19269.3
Wizard version: 0.20.19269.3
