### ISSUE TITLE
RequestAccessAsync missing from background task code

### ISSUE THREAD

**Issue by paulio** [Microsoft/WindowsTemplateStudio#1994]
### Repro steps

Request that the resulting project has background task support

### Expected Behavior

There is at least some code to show the use of RequestAccessAsync even if it's commented out

### Actual Behavior

No support for RequestAccessAsync

## System

    <genTemplate:Item Name="wizardVersion" Version="v1.7.18030.1" />
    <genTemplate:Item Name="templatesVersion" Version="v1.7.18037.1" />

**Comment by mrlacey** [comment]
Yes, looking at this code now, what is generated when adding a Background Task feature to a project is incomplete when compared with what's added for other features.

The code generated for this feature does not include enough that the feature works without writing more code.

The generated project should include code to register (and re-register) the background task so that is can run successfully as all projects using background tasks.

That the generated code links to a document that says "all apps must do X" and the code doesn't do X is a bad sign.

**Comment by mvegaca** [comment]
Template Updated on #2026

**Comment by sibille** [comment]
Verified in dev-nightly: 

Templates version: 0.18.18110.2
Wizard version: 0.18.18110.2
