### ISSUE TITLE
What's new dialog shown before theme is set

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1998]
### Repro steps

On machine set to use light theme by default
- Create app with settings page & what's new feature
- Run app, on settings page switch to the dark theme.
- Close app
- In package manifest, increase the version number
- Run the app again.

### Expected Behavior

The dialog is shown in the dark theme

### Actual Behavior

The dialog is shown with the light theme.
The app switches to the dark theme once the dialog is dismissed

**Comment by crutkas** [comment]
this effect all frameworks and nav types?

**Comment by sibille** [comment]
I think it affects all frameworks and nav types. we'll have a look into this and see if we can fix it for 2.0

**Comment by dgomezc** [comment]
WhatsNewDialog is a ContentDialog and RequestedTheme property inherits from the application. The RequestedTheme property from App can only be set when the app is started, not while it’s running ([App RequestTheme info](https://docs.microsoft.com/es-es/uwp/api/windows.ui.xaml.application#Windows_UI_Xaml_Application_RequestedTheme)).

ThemeSelectorService set RequestedTheme property in  Window.Current.Content (is a Frame element) to modify while the application is running, which does not affect contentdialogs RequestedTheme.

To solve the problem there are several options:

1. Update App RequestedTheme in constructor:

```csharp
public sealed partial class App : Application
{
    public App()
    {
        ConfigTheme();
        InitializeComponent();
        ...
    }

    ...
    
    private void ConfigTheme()
    {
        ThemeSelectorService.InitializeAsync().Wait();

        if (ThemeSelectorService.Theme == ElementTheme.Light)
            RequestedTheme = ApplicationTheme.Light;

        else if (ThemeSelectorService.Theme == ElementTheme.Dark)
            RequestedTheme = ApplicationTheme.Dark;
    }
}
```

In App constructor initialize ThemeSelectorService, get theme and set App RequestedTheme property. This code would only be generated if Settings page is added. 

This solves the problem to FirstRunDialog and WhatsNewDialog, but when changing the theme in settings page, App RequestedTheme is not modified and launch any ContentDialog will not show the theme correctly until restart.



2. Update ContentDialog RequestedTheme in constructor: 

```csharp
public sealed partial class WhatsNewDialog : ContentDialog
{
    public WhatsNewDialog()
    {
        RequestedTheme = (Window.Current.Content as FrameworkElement).RequestedTheme;
        InitializeComponent();
         ...		
    }
}	
```
	
In ContentDialog constructor get RequestedTheme from Window.Current.Content and set ContentDialog RequestedTheme property. 

ContentDialogs always show theme correctly since it would be synchronized with Window.Current.Content.

 BUT: There is no way to include this code in the contentdialog only if Settings page is there (for now). So, if the settings page is not included would be unnecessary code.



3. Create comment in ContentDialog suggesting to update the RequestedTheme if necessary.

**Comment by sibille** [comment]
@crutkas, @mrlacey any thoughts on this?

**Comment by mrlacey** [comment]
I have thoughts on this and will document when I have time.

**Comment by mrlacey** [comment]
I don't like the idea of adding a `ConfigTheme` method it introduces a different configuration paradigm when we already have activation services. Fortunately, #2035 makes this redundant. As long as `ThemeSelectorService.SetRequestedTheme();` is called before `await WhatsNewDisplayService.ShowIfAppropriateAsync();` then we don't need another way to set the requested theme.

I don't have a problem with always setting the `RequestedTheme` inside the dialog.
We shouldn't add any comments to the generated code but instead, add an explanation [in the relevant doc](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/features/whats-new-prompt.md).

**Comment by sibille** [comment]
So, we're going for option 2 and adding a comment to the docs

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.17.18068.1
Wizard version: 0.17.18068.1

If we want to add documentation explaining the code I think this shouldn't only be on the WhatsNewDialog docs, but on a new doc explaining theme or dialog support in WTS general.
If you think this is interesting I'll open a new issue.

**Comment by sibille** [comment]
Missing in vb templates

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.17.18074.2
Wizard version: 0.17.18074.2
