### ISSUE TITLE
MvvmCross template

### ISSUE THREAD

**Issue by nickrandolph** [Microsoft/WindowsTemplateStudio#2047]
## For new Features:
Add a template which includes MvvmCross as the mvvm framework

* **Overview:** What you'd think should be added with scenarios
MvvmCross is one of the most extensive Mvvm-base frameworks and allows developers to hit the road running with a great architecture and a great community of support
With v6 soon to be released it would be great to have templates available that use the new version

* **Links:**
https://www.mvvmcross.com/
https://github.com/MvvmCross/MvvmCross

**Comment by mrlacey** [comment]
Adding support for a new framework is a lot of work and we would want the support of the developers behind the framework to go ahead with such work.  
@nickrandolph would you be interested in helping with the work necessary to add this?

**Comment by nickrandolph** [comment]
@mrlacey I would definitely be interested - If you have a high level overview of what's involved, I'll run it past the core team and work out how best to get it done.

**Comment by mrlacey** [comment]
@nickrandolph I'm not ignoring or have forgotten you. There are some big fundamental changes we're discussing about how the templating system works to support some upcoming features. The consequence of this is that any work done in the short term is highly likely to require major rework or duplication in a month or two. I recommend holding on for a few weeks and hopefully, we'll have some answers that will make integrating simpler.

**Comment by nickrandolph** [comment]
No probs. We’re probably a couple of weeks out from a stable v6 release anyhow.
Since there are a couple of us (eg reactive ui) wanting to generate templates it might be worth us all working through the process as a group. This has worked well with multi-targeting where there was quite a bit of cross pollination between OSS projects

**Comment by ghuntley** [comment]
Yo @nickrandolph; we could like pair? I could drop on by your office - you do mvx and I do reactiveui?

**Comment by yanxiaodi** [comment]
I have the same suggestion. We have some Xamarin projects with MvvmCross framework with shared projects between Xamarin.Android and UWP. So it would be helpful to provide a template as the best practice based on MvvmCross.

**Comment by crutkas** [comment]
i think this would be great as an addition but i really think we need to better spec / POR with Xamarin.

**Comment by ghuntley** [comment]
@crutkas ding me and @nickrandolph when you think it's appropriate for us to pickup this task.

**Comment by mrlacey** [comment]
@nickrandolph @ghuntley 
As per the updated [roadmap](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/roadmap.md), we plan to adapt the current UWP templates so that they can create a solution that has a project for the main UWP app and another project (a .net  Standard library) that contains platform-agnostic code and is referenced by the UWP app. This is currently being planned [here](https://github.com/Microsoft/WindowsTemplateStudio/issues/2252) and will be a stepping stone to adding Xamarin.Forms support. (Being tracked [here](https://github.com/Microsoft/WindowsTemplateStudio/issues/2274).)
The multi-project solution work is being done in parallel to the continued enhancement of UWP templates, it will be released as v3.0 and is expected around October (this is in part due to many of the core team taking time off over the summer.)
I originally expected that the switch to the UWP templates creating a multi-project solution would require a big change to the existing UWP templates, but my current feeling/hope is that this won't be the case. I previously advised on waiting to avoid a lot of rework.
If you want to start working on UWP templates now, then that's great. If you want to wait for 3.0, that's great too. Expect a branch for this in the next week or two. Or, if you want to wait for XF support (no dates yet but it's likely to be the next big thing we look at after 3.0 ships), that's understandable too.

Whatever you decide, this is how I'd recommend starting.
- Create an app using an existing framework that includes all pages and features and then convert this to use MvvmCross. This will be a reference for verifying that the created templates produce what they should.
- Create the templates for a single navigation option, a blank page, and a single, simple feature such as SettingsStorage. Documentation is currently limited but start with [this](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-developers.md) and be sure to run the coded-tests related to verifying templates (ExecutionSet:"TemplateValidation") 

Creating these will put you in a good position to start creating templates for the other pages and features.
Let us know if you have any questions or suggestions for improvements to related docs.

**Comment by crutkas** [comment]
Closing due to lack of community asking. Will be happy to kick the conversation up again.

**Comment by nickrandolph** [comment]
Hey @crutkas this actually stalled because you asked us to hold back waiting for an update to the WTS. I'm seeing that there's good support now for multi-project solutions. Perhaps now is the time for us to put some energy back into this. 
What's involved in adding Mvvmcross support into WTS? If we can find someone to do it, what's the process? who do we need to engage with etc? 
This is somewhat the same situation as I recall for ReactiveUI, so perhaps there is a time saving if we can do both at the same time?

**Comment by yanxiaodi** [comment]
@nickrandolph Agree. It is time to reopen it.

**Comment by keithnicholson** [comment]
Any movement on this?
