### ISSUE TITLE
Check impact of new MIDL keywords

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2067]
Based on the new MIDL keywords listed in the breaking changes section on
https://blogs.windows.com/buildingapps/2018/03/13/windows-10-sdk-preview-build-17115-now-available/

We should review any potential impact. 

That we have methods that match some of these names (`get` & `set`) is potentially concerning. We may also need to update the list of banned identifiers when adding a page or feature.

**Comment by sibille** [comment]
I think there should be no impact here. 
- Set- Methods are in uppercase
- Pages add a "Page" -Suffix and most Features do not allow choosing names, BackgroundTask is the only exception I think
- we did not include the original MIDL list. I think the reason was that it would be a rare coincidence that sb calls a BGT enum vs VS error message being very clear about compiler issues.

**Comment by sibille** [comment]
@crutkas, @mrlacey can we close this?

**Comment by mrlacey** [comment]
Ok, to close I just wanted to make sure we checked this.
Not also that VB is not (mostly) case-sensitive. We work around this for now but it would be good to try and avoid needing such workarounds in the future.
