### ISSUE TITLE
docs for comparing MVVM frameworks

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#2094]
can we have a single page docs, or maybe a simple comparison table to compare pros and cons of each MVVM framework ( for uwp apps )  being used in WTS? this will help developers to decide which framework they should use for their own app. Obviously most developers dont know all of the frameworks, so its very hard decision for someone who is a beginer and knows only simple MVVM and not a framework. So if they know proper pros and cons of all they can decide to learn which suits them more and select that framework while creating a wts project as well.
for example, framework A is better for xaml, B is better for c# , framework C is better at navigation stuff, etc. obviously this kind of comparison can be opinion based, but someone who knows all of them can compare them in a better way.

**Comment by mrlacey** [comment]
I thought we had an issue for adding this documentation already but can't find anything so I guess not. 
Yes, we should add something around this.

**Comment by touseefbsb** [comment]
@mrlacey  do u know someone who can do this?

**Comment by mrlacey** [comment]
I'm rethinking whether we should do this.
- We don't want to be responsible for pointing someone to a framework that isn't the best for their needs/requirements.
- Our goal isn't to teach people about the different frameworks. 
- A brief comparison of each is not an adequate substitute for researching each framework fully.
- For many people, they choose one framework over another just because of personal preference with regard the style, conventions, and structure of the framework. There is no "this framework is best for such-and-such a type of app."
- Any pros and cons list would be highly subjective and so not a fair comparison. (Is a framework being highly convention based a pro or a con? It's either depending on your preference.)
- We provide support for multiple frameworks to help the people who want to use them. It's not a case of providing lots of options on the expectation that the same developer will choose different frameworks for different projects. I'd expect a developer to pick the same framework each time they created an app.
- We already have a brief description of each in the docs [here](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/getting-started-endusers.md#design-patterns) and that includes links to the 3rd party frameworks where there are more details. If necessary, we could expand these descriptions.

**Comment by touseefbsb** [comment]
actually the idea was to provide enough information about the frameworks as per uwp platform and then let the user decide wht they want for themselves. I understand a developer will pick same framework each time, but a developer who wants to  step-up from mvvm-basic to a framework, it would be helpful to them. bcz they don't have a framework of choice uptil tht point. and its just another infinite loop of researching and hit and trial to learn wht should they use. I understand it can be opinion based and it would be a hard job to make it as neutral as possible with uwp platform in mind. I myself have been doing some research lately bcz I am a mvvm-basic developer myself and I want to level up to a framework ( if that will help ) see I am not even sure whether I should do that, but then I also have this curiosity tht I might be missing out on some brilliant tech which might make my life a lot easier. so I was looking for some data specific to uwp only which can make my life easier, bcz these frameworks exist on multiple platforms, there is a lot of data out there on web and wpf platforms but very less quality comparisons for uwp specific of these frameworks.

**Comment by crutkas** [comment]
Issue is we don’t want to say one is better than the other. 

We partnered with the top framework makers and made sure we had fantastic reference implementations. 

Picking a framework is a very personal choice. A good thing about trying them out is you can get a reference implementation in a few minutes for each and see what coding pattern works best for you. 

Let’s figure out how maybe we can improve the page Matt referenced but I can’t see us doing what is being asked here

**Comment by mrlacey** [comment]
How much information is enough?

What's the goal of providing this information? 

What do we want people to be able to do as a result of reading this information?

**Comment by touseefbsb** [comment]
@mrlacey  as I said before this information will be for mmv-basic developers who want to make their life easier by selecting anyone of these frameworks. each framework is known to approach the mvvm a specific way, and they themselves on their websites claim wht they r good at, this info should be enough for the developer.

**Comment by mrlacey** [comment]
> this information will be for mmv-basic developers who want to make their life easier by selecting anyone of these frameworks.

That sounds like you want us to provide enough information for them to make a decision on what to use.

> on their websites claim wht they r good at

So do you just want a summary of what's on the website? Why not just point them to the website? How do we manage updating our copy of the information we copy if the website changes?
What if the websites don't provide the information to make the comparison you're looking for?

> this info should be enough for the developer.

And how much information is this? 

Who is an "mmv-basic developer"? How much do they know? What is reasonable for us to assume about them?

**Comment by crutkas** [comment]
@touseefbsb giving guidance for which framework to pick is hard.  Everyone has opinions, including me.  we are proactively trying to stay neutral on "what is the best" or "feature list" cause then we have to stay 100% up-to-date on every new release's change notes and be sure we're positioning everything correctly.  I don't want a flame war of which is the best nor have one of our fantastic framework creators feel offended because we positioned one a certain way versus another.  Another issue is some people like certain frameworks because they "feel" better for them.  That is something we just can't quantify for each person reading that document.  Web frameworks is a great example of this.  Everyone has their favorite and a reason why it is the best thing on earth.

Could we do better here, sure.  how exactly, i don't totally know.  Maybe show a few lines of code per framework in the doc and highly suggest someone runs through a medium size generation of each framework to see what is better for them.

**Comment by touseefbsb** [comment]
yeah tht is exactly wht I am not sure abt either "how to improve it" but I agree with you that web frameworks cause wars bcz of opinions and thts probably not a good idea to do here either.

**Comment by mrlacey** [comment]
I've proposed slightly expanded descriptions of each  3rd party framework [here](https://github.com/Microsoft/WindowsTemplateStudio/pull/2205/files) to try and give a bit more information about them but without making direct comparisons or recommendations.
