### ISSUE TITLE
Bug: Update of nuget packages breaks the application

### ISSUE THREAD

**Issue by twennberg** [Microsoft/WindowsTemplateStudio#2107]
i created a project with the following:
Windows Template Studio version 1.7.18030.1

using
Navigation pane and code behind

set up 4 pages:
man(Blank)
masterdetail
Chart
Settings.

After updating the nugget packages i get the following error when i build the solution:
CS0123	No overload for 'ItemInvoked' matches delegate 'EventHandler<HamburgerMenuItemInvokedEventArgs>'

intelisence also report something wrong in Shellpage.xaml.cs:
private void ItemInvoked(object sender, HamburgetMenuItemInvokedEventArgs e)

this seems to be a spelling issue with the t in "Hamburget"
and the error appear when updating nugget package 
Microsoft.Toolkit.Uwp.UI.Controls
from version 2.1.1 to 2.2.0

**Comment by mrlacey** [comment]
The issue here is that you've updated to a new version of the [UWP Community Toolkit](https://github.com/Microsoft/UWPCommunityToolkit/releases) and the transitions from 2.1.1 to 2.2.0 included a breaking change (even though it was only fixing a typo.)

If you go to **ShellPage.caml.cs** and change the signature of the `ItemInvoked` method from
```
    private void ItemInvoked(object sender, HamburgetMenuItemInvokedEventArgs e)
```
to 
```
    private void ItemInvoked(object sender, HamburgerMenuItemInvokedEventArgs e)
```
(Fixing the spelling of "Hamburger")
This will fix your app.
