### ISSUE TITLE
Revisit breaking changes notification 

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2125]
Breaking change notification introduced in #2086 should be shown in another place as notification hides part of the screen. 
Possible places are:
- Right hand side under about
- Separate child window

Also take into account that in a future there could be more than one breaking change notification.

**Comment by dgomezc** [comment]
We have created two different designs to show the messages and links of the breaking changes:
- Show messages in dialog window.
![breaking_changes_1](https://user-images.githubusercontent.com/12777039/38811750-ae3a4ec2-418a-11e8-858d-ec5cd8fcfffb.PNG)

- Show messages in side panel.
![breaking_changes_2](https://user-images.githubusercontent.com/12777039/38811753-b3a76516-418a-11e8-86b7-03c6ea013d7e.PNG)

We believe that the side panel is more integrated in the wizard design, but we believe that people will pay less attention than if we show the message in a dialog window.

What do you think, @crutkas?

**Comment by mrlacey** [comment]
The side panel works for me but I'd add a background color to help it stand out. 
Will this fall inside or outside of the scrollable area? 

I like the warnign at the bottom of the side panel so it's directly above the but that's clicked to continue. It should make it more obvious.



The messaging needs to also explain what will happen because of this issue.
- Does it prevent continuing? If so it should explain this.
- Does it allow you to continue but will create a backup of the old version?

Also

- Where does the message fit in the flow when using a screen reader? Does it make sense logically? (Don't want to only show this at the end if it means progress is stopped.)
- In addition to the text that says continuing means you accept any licenses, should this be extended to acknowledge that what will be generated will be broken?
- Is the warning message (and especially the link with action instructions) also included in the details shown once the page/feature is added?

**Comment by sibille** [comment]
We added the yellow background and a description text:
![breaking_changes_1 1](https://user-images.githubusercontent.com/24698018/38931740-7b90149e-4314-11e8-8b8c-4adaf6a50ef0.PNG)

Scroll is global, because "Breaking changes" area might grow in future too. 
For now scroll will not show, as there is only one braking change message.

 The alternative would be having two scrolls, but that looks a bit weird. 
![breaking_changes_2 1](https://user-images.githubusercontent.com/24698018/38931843-c4070df4-4314-11e8-958a-c4de276f3cda.PNG)

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.18.18110.2
Wizard version: 0.18.18110.2
