### ISSUE TITLE
Add option to generate code in multiple projects

### ISSUE THREAD

**Issue by ghost** [Microsoft/WindowsTemplateStudio#2223]
**Overview:** 

* Allow the user to split the generated in code in multiple projects (an Universal Windows Project for the GUI and a .Net Standard Class Library for Services, Models & ViewModels)
* Remember user's choice when adding new views/features

Example:

* Foo.Core project (.Net Standard Class Library)
  * Services\
  * Models\
  * Helpers\
  * ...
* Foo.GUI project (Universal Windows)
  * References: Foo.Core
  * Views\

One useful side-effect of moving the Models, ViewModels, etc in a .Net Standard Class Library is that you can further create a console test project for them:

* Foo.Test project (.Net Core console)
  * References: Foo.Core

**Comment by borco** [comment]
It would probably be great to be able to have a single "Services" folder, but I see this is as a "good to have", not "must have".

In my opinion, the most important thing would be to have a .Net Standard Lib that can be referenced by the UI (UWP or Xamarin) and console unit tests (that run much faster than the UI tests, are easier to write, run headless, etc...).

**Comment by harvinders** [comment]
Would these separate assemblies work like a plugin concept? That would be a great help if there are plugins (Optional package), or maybe it is a separate feature. This would allow us to pack selective features all from the wizard.

If it is not going to be plugin type concept, please consider if it can somehow play nice with containers, especially registration of models/viewmodels by convention from these separated out assemblies. As of now I am not able to find a way to do it though (maybe you guys know better/ or something may come up in future versions of UWP or OS). See this link for my [attempts]( https://github.com/dotnet/corert/issues/5758).

**Comment by mrlacey** [comment]
Things like the ability to include test projects will be optional and be features you can add through the wizard.
Whether we continue to support everything in a single project and the ability to put some functionality in a separate (Net Std) library is undecided.

In terms of referencing the shared libraries in the main UWP app, I would do this with direct project references. I'm not familiar with UnityIOC (as per your link) but even if native compilation wasn't an issue I wouldn't look to load references via reflection because of potential perf and design/compile time issues.

**Comment by mrlacey** [comment]
Work relating to this is being tracked in #2252 
Closing this to avoid possible confusion with multiple similar tickets and to keep everything in one place.
