### ISSUE TITLE
Ability to merge official feed and custom feed

### ISSUE THREAD

**Issue by crutkas** [microsoft/WindowsTemplateStudio#234]
A user has highly specialized components for their controls.  They would like to still use our official feed but have one for their controls as well.

**Comment by mrlacey** [comment]
I have a PoC of this and have shown it to Clint & Michael. Will add as a branch next week when I get back from build.
It lets you specify a directory on the local machine and merges in pages and features from there.

**Comment by mrlacey** [comment]
I understand this issue to be about being able to support an additional source of templates from a URL which points to a mstx file.
Probably implemented similar to #919 and using the same config method but different functionality.

**Comment by crutkas** [comment]
was thinking about this and #919 and i think one big thing we need to have is force custom feeds to have a min and target.  If you're past the target / tested version for that feed's author, it could create a bad template.

This feature also should have multiple feeds allowed.

**Comment by mrlacey** [comment]
I would expect any downloaded templates to be versioned in the same way as the official one and have the same compatibility checking applied.

Also, need to consider handling different update checking frequencies for different feeds. Shouldn't be an issue but not something to ignore.

**Comment by mrlacey** [comment]
removing myself as assignee as "Microsoft on point" and don't want to get in the way of progress by holding this up if others can move this forward faster.

**Comment by mrlacey** [comment]
Moving to 2.0 as closely tied to #919 as that's where that is.

**Comment by mrlacey** [comment]
Doing this will require updates to the composition filters of existing templates so that they are not picked up by any new templates. For example, if wanting to add a new project type but with an existing framework, this will pick up lots of composition items which currently only filter on framework because that's sufficient for the current templates.

Also affects #919 and may affect Xamarin (#321 ?) templates too.

(issue discovered while trying to implement #1336)

**Comment by mrlacey** [comment]
closed by mistake

**Comment by mrlacey** [comment]
POC mentioned above is actually for #919

**Comment by mrlacey** [comment]
Highly related to #1478 (which is looking to split up the templates for smaller downloads.)  
If the current templates are split into multiple downloads then the wizard will need to be able to handle "official" or "first-party" templates from different URIs.   
Once able to handle multiple official template sources, extending to include templates published by others as well should only require the ability to specify where the templates _should_ be downloaded from.

**Comment by sibille** [comment]
### Versioning: 
An option would be to load always the latest available version. (Wizard major minor or lower). If there is a breaking change this has to be communicated to ensure the availability of compatible packages by the time the wizard is released. 
We might have to include also a template checking mechanism to check templates from external packages before loading to ensure compatibility to avoid the inclusion of feeds that were not updated. 
### Catalog:
Should remote sources be able to modify the catalog to include new project types and frameworks?
### Dependencies:
Can templates from remote sources establish dependencies on WTS templates? I think this should be possible
### Composition templates:
Should WTS compositions apply to templates from other sources? Should we provide a mechanism to exclude/include compositions?

**Comment by mrlacey** [comment]
For **versioning**, I'm assuming that the downloaded package will include the version number of the wizard it works with. I'm also assuming that a downloaded package can only have templates for a single version.

For compatibility, I'd like to see major version number compatibility. That would mean that every template wouldn't need to be updated (even if just the version number) every time the wizard is updated. Using the major version number to indicate breaking changes will also give warning of advance changes and set expectations about stability.

Part of the reason for creating TemplateValidator as an EXE was to help other template creators verify their templates. (There's probably lots of future extensions to this app that will be needed and can be added in time.)

Don't need to exclude older versions from being downloaded. They just won't be used if for an older version. Then, they will be picked up when updates are available.

Would really like to see support for both `ETag` and `If-Modified-Since` headers to minimize downloads.

For other issues, see [here](https://github.com/Microsoft/WindowsTemplateStudio/issues/919#issuecomment-359012491).

**Comment by mrlacey** [comment]
Other things that will be needed/useful for this (just starting a list that I expect to grow.)

- Ability to specify multiple (or any) language support for a single template.
- Ability to specify "Any" for frameworks
- Ability to specify a group name in a template that doesn't have a localized description.

**Comment by mrlacey** [comment]
Will need improved tooling for template authors to validate templates and create localization files

**Comment by mrlacey** [comment]
Provisionally assigned to 3.4 as that's when I hope to begin looking at this in detail.

Note that may also want to look at #919 at the same time. Even if don't do that yet, **MUST** review comments there as they also overlap with this issue a lot.

**Comment by sibille** [comment]
How are #919 and this different, is it local vs online template package sth else?
Also, running through the comments above a lot has changed since this was opened and some are outdated, lets sync on specs for this and set up an action plan.

**Comment by mrlacey** [comment]
This issue is about having the ability to download templates from multiple remote locations.
#919 is about having a templates in a local folder (or mapped drive) - I had this set up previously on my machine as a quick and easy way to test new templates without needing to mix them with the official template collection. I also see this ability as an easy way for companies to have their own templates for local use without needing to package them up and unpack them within a local network.


Yes, the comments in this and #919 must be reviewed before any work begins.

**Comment by mrlacey** [comment]
Note for expectations: Just doing investigation in the 3.5 timeline

**Comment by mrlacey** [comment]
There are three areas involved in this.

1. Supporting templates from multiple sources.
2. Dividing up currently provided templates. 
3. Helping third parties create their own templates.

These should be approached in this order and each is made up of multiple other tasks.

1. Supporting templates from multiple sources.

- Need UI for specifying the sources. (See below)
- Need to retrieve the template bundles from multiple locations. This needs to include checking for updates, retrying failed attempts, unzipping files if in a bundle, copying from other directories, and more.
- Handle combining templates from multiple folders (on the local machine.) The DotNetTemplating engine supports this but after a brief investigation, I was unable to get this to work from within the existing WTS code base.
- Need to improve error handling and reporting for invalid templates

2. Dividing up currently provided templates. 

- Split up current templates on disk so Prism & Caliburn.Micro templates can be installed separately.
- Split out ore specific templates that shouldn't be in the main bundle. XamlStyleConfig was added on the basis that it would be broken into an "additional" bundle once this capability was added. Having it in a separate bundle on its own probably isn't ideal and so may want to review when this is done or if there are other items that can also be moved out of the main bundle at this time.
- Configure default options in UI.
- Add processes for packaging and distributing multiple templates per platform/language.
- Enable templates from multiple sources to include items from other sources during composition.
- Enable templates from multiple sources to exclude items from other sources during composition.
- Update testing/validation of templates to account for different template locations.

3. Helping third parties create their own templates.

- Improve documentation on how to author templates.
- Add documentation on the packaging and distributing of WinTS compatible templates. This must also include differences from how dotnet-new works with template sources.
- Improve tools to help with testing and validating any created templates. Existing tests and tools are a start but these may need updating and revising to make them easier to use outside of the WinTS source. A tool to help with debugging composition filtering issues may also be helpful. This is an area I regularly encounter issues with and would be very hard to debug without stepping through the code. Forcing people to have to step through the code to debug issues with template composition is probably not something we want. 
- Respond to issues found when people start building their own templates. They'll find things we haven't thought of or have questions our experience prevents us from predicting.


I recommend that items in the above list each become their own separate issues for tracking the progress in this large task.
Some of the above need further detail and clarification but I thought it better to wait until separate issues are added to document them, rather than risk adding distracting complexity here.

-----

Here's how configuration might work. (This is deliberately low fidelity as VS designer involvement will be necessary. All text is for example and not final copy.)

- Add a link to the configuration in the wizard.
 A similar link will also be needed in the AddItem wizard UI.

![Example of adding a link to a new settings/configuration view](https://user-images.githubusercontent.com/189547/66751789-ca16d380-ee87-11e9-8483-004b1fdc258b.png)

Managing the list of template sources within UI provided by the extension allows following current styling which is different from default VS UI.  
Not storing and managing this inside standard VS Options functionality also makes it easier to use this with VSEmulator. 

![image](https://user-images.githubusercontent.com/189547/66753663-34317780-ee8c-11e9-9c3f-90675df4226e.png)

1. The list is based on the wizard entry point and filtered as such (by platform and programming language). This is to avoid making this more complicated by not adding things people aren't using.
2. The default (what is currently included) can't be opted out from inclusion. Included in this list to make it clear that they are part of what will be made available in the UI.
3. Other templates also managed & hosted as part of this project are available and can be included/excluded by checking the option. When first introducing this functionality these should be checked by default.
4.  This can either be a URL to a zip file containing templates, or a file path to a directory containing templates. Empty entries will be removed when leaving the screen.
5. An option at the bottom to add more template sources.

After leaving this screen (navigating back) it will be necessary to refresh the list of available templates (if nothing has changed). This may result in previous selections being lost.

**Comment by mrlacey** [comment]
#3391 #3392 & #3393 created to carry this work forward.
