### ISSUE TITLE
Page with "Page" suffix causes Header in NavigationView not to work

### ISSUE THREAD

**Issue by wind-rider** [Microsoft/WindowsTemplateStudio#2362]
### Repro steps

- Create WTS project of type "NavigationPane" with Prism programming pattern.
- After creation, right click the project project -> `Windows Template Studio` -> `add new page`
-  add new "Blank page" named "LoginPage"

### Expected Behavior

Added page has same behavior as pages added before

### Actual Behavior

- The generated code is named LoginPagePage
- The navigation view header does not show the page title correctly because [`private bool IsMenuItemForPageType(NavigationViewItem menuItem, Type sourcePageType)`](https://github.com/Microsoft/WindowsTemplateStudio/blob/9accafad2b790a8c5c67a205ad000bf9f2947ae3/templates/Uwp/_composition/Prism/Project.SplitView/ViewModels/ShellViewModel.cs#L57) returns `false` when checking the page for which it should return `true`.

## System

* **VS Version:** 15.8 Preview 2
* **WTS Wizard Version:** 2.2.18159.1
* **WTS Template Version:** 2.2.18159.1
* **Windows Build:** 17686

**Comment by wind-rider** [comment]
It would be nice if the wizard would tell you not to use a name ending in "Page".

**Comment by sibille** [comment]
We'll have a look at this. This should work although the generated PageName is LoginPagePage. 
Regarding the wizard enhancements:
I like the idea that the wizard ignores page in LoginPage when generating. Not sure about the View warning though, there could be page names like Overview or SummaryView where this is intentional.

**Comment by mvegaca** [comment]
Issue fixed on #2368

About adding a naming validation for page names that ends with Page suffix I propose to add a new Naming Validator.

```csharp
public override ValidationResult Validate(string suggestedName)
{
    if (suggestedName.EndsWith(PageSufix))
    {
        return new ValidationResult()
        {
            IsValid = false,
            ErrorType = ValidationErrorType.EndsWithPageSufix
        };
    }
    else
    {
        return new ValidationResult()
        {
            IsValid = true,
            ErrorType = ValidationErrorType.None
        };
    }
}
```

Validation error in wizard.

![image](https://user-images.githubusercontent.com/5556784/41537119-cb1b6ab8-7307-11e8-9fad-f61ad57ef3a6.png)


I think removing last Page characters for page name is not a valid solution because it solves _"LoginPage"_ issues but we will still have the same problem with _"LoginPagePage"_ named pages.

What do you think on this @mrlacey?

**Comment by mrlacey** [comment]
ok. This seems like the least effort solution.
If people enter a value 'LoginPagePage' then I hope they have a good reason for it. (If anyone has such a reason I'd like to know it--there may be something cool or important I'm not aware of or overlooking.)
Simply ignoring the situation if someone created every page with 'View' as a suffix, doesn't seem ideal, but I understand that it doesn't break anything and so you'd be reluctant to do anything special here.

**Comment by mvegaca** [comment]
I think we should work with Validators, as we are working with ReservedNames. I think it's better than remove the suffix from configured name, because you can produce the following situation:
 - Configured name: **Main** - ResultingFile: **MainPage.xaml**
 - Configured name: **MainPage** - ResultingFile: **MainPage.xaml**
It looks like a strange behavior.

I think we should include a documentation link in the validation error notification (we are doing it on brakeing changes notifications) explaining the naming patterns for pages and also enumerating the reserved names.

**Comment by sibille** [comment]
I think we should go with the validation approach, the example @mvegaca mentioned would not detect a duplicated page and generation could result in unexpected situations if pages are of different types. Regarding the Views suffix: We could add a warning (not error) pointing to the naming pattern doc if sb names all pages with View suffix.

**Comment by sibille** [comment]
Initial issue is solved, opening a new one for the wizard enhancements. 

Verified in dev-nightly: 
Templates version: 0.18.18178.1
Wizard version: 0.18.18178.1
