### ISSUE TITLE
Add multi-view code support

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#241]
enable that every launch for your app creates a new, separate view (like calc does)

**Comment by mrlacey** [comment]
I propose doing this for Fall Creators Update when platform support for doing this easily becomes available.

**Comment by crutkas** [comment]
could get UWP Community toolkit to do an epic wrapper, then all we need is a NuGet package :)   @nmetulev thoughts?

**Comment by mahoekst** [comment]
no need to wait, multi view and multi instance are 2 separate things. (the latter is just an option in the manifest),  Paul did a nice blog about this with mvvm support https://blogs.msdn.microsoft.com/theuxblog/2016/07/10/multiple-windowsviews-in-a-windows-10-xaml-store-app/ makes sense to add an option to do this.

**Comment by nmetulev** [comment]
Agree with @mahoekst, it's possible right now. Could be a cool helper for the toolkit. I propose adding a UV and an issue in the toolkit repo in order to discuss and agree on implementation.

**Comment by nmetulev** [comment]
Added UV and issue: https://github.com/Microsoft/UWPCommunityToolkit/issues/1163

**Comment by mrlacey** [comment]
I pushed for adding this with the native support in FCU. 
I was aware that multi-instance can be simulated with multi-windows but wanted to opt for the simpler option.
Depending on what gets implemented in the toolkit, need to be aware of the following when adding support here:
- Will need changes to ActivationService
- Will need changes to SuspendAndResume feature (I strongly expect)
- Will need consideration for how ViewModels are referenced. Especially SettingsViewModel and other Singletons.

**Comment by mahoekst** [comment]
This are 2 different things, sure you can mimic multi-instance with multi-views. But multi-views is a feature by itself. Multi instance is just another property in the manifest with the FCU, so wouldnt worry about it right now.

**Comment by mrlacey** [comment]
Added the note on adding the FCU property as we don't yet have a way to support this in post action merging.

**Comment by crutkas** [comment]
I'm going to update this to "Multi-View" as that is what i was thinking.

**Comment by crutkas** [comment]
after much discussion, @nmetulev @gcaughey and @wickste.  We feel that doing this via a template is actually a better approach versus wrapping inside the toolkit.  We can control the comments and work flow for this easier.

**Comment by mrlacey** [comment]
Are we just looking to do the "calculator style multi-views" or (also) an easy way for people to launch specific pages in separate windows?

**Comment by gcaughey** [comment]
If we also do the launch a secondary page in a separate window thing, we might want to keep that a separate Template option. My thinking is the "calculator style multi-view" is just a workaround until we have true multi-instance app support in a later version of Windows.

**Comment by wickste** [comment]
Agreed – those are two separate (and valuable!) requests.

Food for thought: making it easy for apps to launch a page in a secondary view seems more like a Toolkit thing, rather than a Template thing.

**Comment by mrlacey** [comment]
@gcaughey yes, potentially two separate things. 

True multi-instance is coming with FCU, but we'll need to do the fake way until FCU is the lowest version we support.

**Comment by wickste** [comment]
It’s planned for a post-FCU update actually.

**Comment by gcaughey** [comment]
Good point from @wickste about launching secondary view as new window (as opposed to calculator pseudo multi-instance) being interesting for the Toolkit. How should that work? As Helper? Control?

**Comment by wickste** [comment]
Yep, could be a helper that encapsulates the required code, something like:

ViewHelper.ShowAsNewView(Page page)

**Comment by mrlacey** [comment]
Ok, we'll keep this issue about psuedo-multi-view and leave launching specific pages in new windows to the toolkit.

**Comment by crutkas** [comment]
@mvegaca is this possible to get in for 1.5?

**Comment by ralarcon** [comment]
From our side, I think so (we don't have now shouldn't be an issue). 

Anyway lets have a look and design what we need to include / consider.

**Comment by ralarcon** [comment]
After the thread, I have some doubts regarding what functionallity we need to cover with this feature so I want to keep clear that we are looking at this as a Multi View: https://docs.microsoft.com/en-us/windows/uwp/layout/show-multiple-views.

**Comment by crutkas** [comment]
lets punt this to next release and actually do a discussion on this item.

**Comment by ralarcon** [comment]
We have the definition and initial aproximation for multiview (@mvegaca will share it) so we can use the work done as base for discussion future discussion or, if the defined aproximation is fine, we can finally include the feature in 1.5.

**Comment by ralarcon** [comment]
https://github.com/Microsoft/WindowsTemplateStudio/issues/241

**Comment by mvegaca** [comment]
After reviewing documentation and samples, I can work in a WTS feature that provides the infrastructure to work in MultiView.
The feature will add a WindowManagerService that allows users to open a page in a new window, it cloud be opened multiple times or only one time. This service always contains the infrastructure to communicate between different opened windows on a save thread mode.
The feature also provides a ViewLifetimeControl class with new secondary view properties and lifecycle events.
I think that feature could be a start point with the infrastructure to work with multiple views and TODO comments to specify the user where he can start but this feature not should add new generated pages to the project. @crutkas if you want I can upload a PoC or create the feature (only for MVVM) and iterate, comment and improve the feature??

**Comment by crutkas** [comment]
I think a POC is much more useful to iterate on.

**Comment by mvegaca** [comment]
Putting this on hold until we finish the feature for Project Rome #180.
Once finished we will continue working on that

**Comment by michael-hawker** [comment]
Is there a link to the documentation on the new FCU capability added?

**Comment by crutkas** [comment]
@michael-hawker it was master detail was what was the big adjustment.  NavView will be migrated in over time with the UWP Toolkit 2.1.  

Please remember, new issue / question, add a new issue.  Helps keep discussion on the same issue at hand.

**Comment by mvegaca** [comment]
![image](https://user-images.githubusercontent.com/5556784/32571956-76a953d8-c4c9-11e7-8f07-0ce73b10cbec.png)

**Comment by mvegaca** [comment]
PoC added on #1424

**Comment by mvegaca** [comment]
After review all the documentation and samples about MultiView in UWP I’ve created a PoC that with two different complex scenarios that could contain a real App.
 
 **Two-way communication**
 
- The idea of this scenario is having a secondary view that could operate with the main application in a two-way communication.
- Open button opens the secondary view but if it’s already opened active the window instead of open it for twice.
- Update secondary view button is only available if the secondary window is opened.
- Scenario1 update button updates the Scenario1Secondary text.
- Scenario1Secondary update button updates the Scenario1 text.

![image](https://user-images.githubusercontent.com/5556784/32572245-447e5eac-c4ca-11e7-911e-1c4e789e7aec.png)

**Overlay window**

- The idea of this scenario is having a secondary window that can show content in an overlay mode.
- Open secondary view button is only available if the video window is not already opened.
- Once the video window is closed we need to do two different actions:
  - Pause the video because the thread keeps alive till the window is closed.
  - Update the Open button command can execute change.
- This is a complex scenario because las two actions must be done in different threads.
		 
![image](https://user-images.githubusercontent.com/5556784/32572299-6da64cf4-c4ca-11e7-83f4-8a6c3f2412d4.png)

It looks that we could think of two different approaches to create the feature on Windows Template Studio.
 
**Lite Version code feature**
- Adds the WindowManagerService with simple methods to call Windows APIs.
- Add links to the documentation and UWP sample where is the ViewLifecycleControl implemented
 
**Full version code feature**
- Generate the WindowManagerService with methods to call Windows APIs and view tracking of view lifecycle objects.
- Generate the infrastructure around the lifecycle of new secondary views (thread-safe code, event handling, etc.)
- Could add too much complexity to the code.

In one hand, if we add the lite version is just the code described in the documentation and is enough to display a Page in a separate window. It's also a good start point to the user and the code is short and easy to understand.

In the other hand, if we add the full version we will be adding a more powerful feature but it also will be more difficult to understand and even if we add good comments and documentation. With this implementation, the final developer could reach complex scenarios as described above.

PoC added on #1424

**Comment by ralarcon** [comment]
Feedback from Product Group team added. Feature ready in dev (nightly build).

**Comment by touseefbsb** [comment]
@ralarcon where can i see a sample app or proper documentation to use the multi view feature of windows template studio? i created a project with this feature, i can see 2 service classes for the feature but there is no implementation to refer and understand how to use it in our app.

**Comment by crutkas** [comment]
@touseefbsb does the todo not help enough? remember we face a very fine line of doing too much VS not enough.

```
// TODO WTS: See more details about showing multiple views for an app
// https://docs.microsoft.com/windows/uwp/design/layout/show-multiple-views
```

**Comment by touseefbsb** [comment]
microsoft docs explain the basic system of multiple views but templatestudio has made very good wrappers around basic APIs, I was able to create and show a secondary view but exception occurs when I close it. It would be perfect if we can get documentation on the wrapper classes created in templateStudio and how to use them in our app. just a very simple use case of making and then closing one secondary view, thats all whats required in the docs. I can certainly figure it out myself but it would take too much time because I did not write those wrapper classes, so the main purpose of saving time would be lost.

**Comment by crutkas** [comment]
valid 100% point.  if our stuff isn't straight forward, we should make.  We'll work on this for 1.7

**Comment by crutkas** [comment]
@touseefbsb I created #1607 to address this.  Would you be interested in created a docs page / maybe tweaking our todo's?  :)

**Comment by mvegaca** [comment]
I'll work on that

**Comment by touseefbsb** [comment]
@crutkas  I would love to help but as I am no expert in multi window APIs. so I am not sure how to write the todos, but I would love to give you guyx specific scenarios and use cases for the developer on basis of which you guyx can write instructions for the developer to easily use these implementations, would that be helpful? :)
