### ISSUE TITLE
Migrate Tab/Pivot to NavView with TopPane

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#2428]
## For new Features:

* **Overview:** with the introduction of WinUI library and new features in NavigationView allows for it to do tabs as well.  With two properties, we can do tabs with the control

`<NavigationView PaneDisplayMode="Top" SelectionFollowsFocus="Enabled" >`

This will simplify our templates heavily now too.

**Comment by mrlacey** [comment]
What's driving this change?
What makes Tab/Pivot style navigation redundant as an option? Is there a new, official, recommendation to use the NavView with a top pan instead of a Pivot? 
How does this sit with the fact that the different controls/layouts have different recommended use cases due to the way they behave? (X-Ref docs: [use the right control](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-basics#use-the-right-controls))

A NavView with a top pane may look similar to a Pivot with Tabs but there are some important differences.

**Comment by crutkas** [comment]
Literally just got out of a meeting when I was made aware of the pending guidance change.  This is a tracking item for when it win UI goes 1.0

**Comment by mdtauk** [comment]
Interesting @crutkas  Sounds like the NavigationView is going to become the "One" control for handling various Navigation patterns.

When/If Alarms gets updated with it, then we will know it is truly the defacto way to do it.

**Comment by harvinders** [comment]
@crutkas If I am not mistaken `Pivot` control allows navigating using swipe gestures, something that `NavigationView` lacks.

**Comment by crutkas** [comment]
@harvinders. Is that a deal breaker if it doesn’t?  Pivot’s nav system actually causes a lot of quirky behavior.

**Comment by mdtauk** [comment]
NavigationView Tabs, would be emulating the Microsoft Edge - Win 32 - Android Tab pattern for discreet navigation.  

The Pivot control was originally meant to be used to navigate between different views/filters of the same data source.

NavigationView makes sense for implementing Tabs, especially in the absence of a discreet TabBar.  Also if you look at the UWP Tab design, it has the selection indicator, an Icon, and a Label.  Exactly the same elements used for NavigationViewItems in a sidebar.

![navigationviewtabs-breakdown](https://user-images.githubusercontent.com/7389110/42149174-0d18afb4-7dcd-11e8-8a0c-2b521f224cff.png)

**Comment by vitorgrs** [comment]
@crutkas Swiping on Nav View is pretty basic for some type of apps. I believe it would be interesting to put the swipe gesture at least as an option for devs who want it.

**Comment by mdtauk** [comment]
@vitorgrs  If they add a Swipe for switching between NavigationView items, it would need to work for when  the items are listed in a sidebar.  I am not sure that would work well, especially with longer lists that require scrolling, or items listed at the top which have an overflow menu when the window is narrow.

**Comment by touseefbsb** [comment]
totally onboard with this because 1 control dealing with 2 types of navigation without any extra code is a brilliant move, will make the template generation easier for wts as well and will make life easier for developers, dont forget that it also has backward compatibility upto anniversary update which is a big bonus.

**Comment by Javier118** [comment]
I have a problem with paneDisplayMode from NavigationView saying "You don't recognize or can't access the member".

**Comment by michael-hawker** [comment]
@Javier118 make sure you're using the WinUI version from NuGet instead of the inbox NavigationView.

The WCT also now supports [TabView](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview) for WPF or Edge-like tabs, so that's an option.

**Comment by mdtauk** [comment]
The Windows Community Toolkit includes a new TabView Control which displays tabs which work like Edge tabs, and look like the Win32 Tabs that you see in the File properties dialog.

https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview

![image](https://docs.microsoft.com/en-us/windows/communitytoolkit/resources/images/controls/tabview/overview.gif)

**Comment by mvegaca** [comment]
Working on Horizontal NavigationView integration on [this branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue2428-pivot).

You can also check out this generated app with Horizontal Navigation Pane and Code Behind.

[NewHorizontalNavViewApp.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2584958/NewHorizontalNavViewApp.zip)

**Comment by crutkas** [comment]
Can someone quickly test out the new tabbed control from toolkit to see if it works the same way from navview?  If so we could do a true tabbed and top navigation model

**Comment by sibille** [comment]
We'll have a look at it. Are you saying replace HorizontalNavView with the tabbed control or combine HorizontalNavView with the tabbed control?

**Comment by crutkas** [comment]
Have an additional project type, tabbed with toolkit control, top navigation with navigation view, ...

**Comment by sibille** [comment]
We had a look at the tabbed control from the Community Toolkit and it works like the Pivot control, not like NavigationView. 

The cool thing about this control is being able to open and close tabs (+ reorder). 
So from our point of view, more than for primary navigation, it would suit better as a page or secondary navigation control inside a Menubar (or maybe SplitView) project.

**Comment by crutkas** [comment]
So tab has all the quirks as split view then :(

Yeah, transition our tabbed page (new issue should be made) over then.

**Comment by mrlacey** [comment]
> Yeah, transition our tabbed page (new issue should be made) over then. 

You want to get rid of the page using a `Pivot` control and replace it with a page that uses the `TabView`?

To my mind, they're very different controls with different use cases.
Making this change will also prevent anyone that has an app that already uses pivot pages from adding another page (via right-click>Add) of the same type to their existing app?

Why not add a new page option that uses the `TabView`?
The one that uses the `Pivot` can be removed when usage (based on telemetry) drops off.

**Comment by mrlacey** [comment]
When making this change, can we please rename the internal identifiers to not reuse **tabbedpivot** and use something different instead. 
Having a different name will avoid issues with adding to a previously generated project using tab navigation. It will also stop possible confusion in a comparison between old and new versions of templates.
While there is a similarity between the old and the new, reusing identifiers has a high likelihood of causing confusion or accidentally overlooking a difference due to the changes that could cause a non-obvious error.
Forcing anything that previously worked with the old version to be updated to use the new reference will also make it easier to ensure that anything that used or referenced the old version has been updated.

Unless there's a good reason to stick with and reuse the old name?...

I suggest using **tabbedNav** as the new identifier.

**Comment by crutkas** [comment]
Good idea

**Comment by sibille** [comment]
Maintaining the internal identifiers allows legacy projects to use rightclick. 
The idea was to show a breaking change message, to guide people on how to update the project to horizontal NavView.

That said, I also like tabbedNav better as an identifier: I'll have a look if we can change the identifier and allow rightclick addition on "legacy" tabbedPivot projects. 

Will also check on telemetry impact.

**Comment by mrlacey** [comment]
> Will also check on telemetry impact.

Telemetry seems like a really good reason for changing this as it will make it easier (possible?) to see who is still using the old and new templates .

**Comment by sibille** [comment]
Pending review from fluent design team

**Comment by sibille** [comment]
Page layouts are the same as for left navigation, which should be fine.
If we have to do adoptions for horizontal nav view, we'll open a separate issue.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.20.19022.2
Wizard version: 0.20.19022.1
