### ISSUE TITLE
Multi view fails with Mvvm Light

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2487]
### Repro steps

Create a C# or VB app with SpliView and MvvmLight
Add Main, Blank and Settings pages
Add multiview feature
Add a button in the main page with the WindowManagerService call to open the blank page in a new window.

### Expected Behavior
Blank page is opened in a new Window

### Actual Behavior
A new execution unexpected exception with message:
`Cannot create instance of type 'App75.ViewModels.ViewModelLocator' [Line: 10 Position: 35]`

## System

**W.10.1803**
**Templates version: 2.3.18212.1**
**Wizard version: 2.3.18212.1**

**Comment by mvegaca** [comment]
The problem looks that multi-view instantiate a the ViewModelLocator one more time as a resource of the applications in App.xaml when the new window is opened, working on a solution.

**Comment by mvegaca** [comment]
The problem is that when a new window is created, App.xaml resources being created and Locator should be a single instance for the application. Here is a [Bug Repro](https://github.com/Microsoft/WindowsTemplateStudio/files/2277667/BugRepro.zip).

We could think on change the ViewModelLocator instance mode to a singleton object ViewModelLocator.Current. With this approach, we can work with multiview and avoid cast the ViewModel from pages code behind to use XBind data access.

Here is a [Proof of concept](https://github.com/Microsoft/WindowsTemplateStudio/files/2277669/MultiViewLocator.zip).

It would be great if @lbugnion could give us his opinion.

**Comment by sibille** [comment]
@lbugnion, did you have the chance to look at this? @mvegaca's solution solves the problem, but this is a major change to Mvvmlight projects and we want to be sure to be following mvvmlight best practices.

**Comment by crutkas** [comment]
My suggestion here is to disable multi-view for 2.4 for MvvmLight if Laurent can't figure out a fix.  Keep this open if that is the route we take and create a new issue to reenable it once we have a fix

**Comment by lbugnion** [comment]
Hi,

Sorry for the delay. I am OK with @mvegaca 's solution. ViewModelLocator is not really part of the pattern per se and it more of a convenience object. I don't have any strong objections in making it a singleton.

Take care
Laurent

**Comment by sibille** [comment]
This is a major change to all MVVMLight pages, as they will now get the ViewModel from the ViewModelLocator singleton instead of DataContext. It works fine for new project, but if you add a new page to project created with version 2.3 or earlier, the following error will shown on the new page:
![mvvmlight2](https://user-images.githubusercontent.com/24698018/45488011-54aa7200-b760-11e8-9c14-758d57aad8be.PNG)

We should add a breaking change message to the wizard on rightclick for projects created with version 2.3 or earlier and link to a documentation that shows how to update. 
![mvvmlight3](https://user-images.githubusercontent.com/24698018/45488107-963b1d00-b760-11e8-8947-eb7228aa38f5.PNG)

**Comment by crutkas** [comment]
Is this major change going into 2.4 or 2.5?  This close to ship, I worry when I see major changes.

**Comment by sibille** [comment]
Ok, let's push it to 2.5

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18288.2
Wizard version: 0.18.18288.1
