### ISSUE TITLE
BackgroundTask trigger change not registered

### ISSUE THREAD

**Issue by Ullmie02** [Microsoft/WindowsTemplateStudio#2505]
### Repro steps

- Create a project with a BackgroundTask
- Set an initial Trigger for the BackgroundTask (for example `new TimeTrigger(15, false)`)
- Run the app for the first time that the BackgroundTask gets registered
- Change the Trigger (for example `new TimeTrigger(60, false)`)
- Run the app again
-` !BackgroundTaskRegistration.AllTasks.Any(t => t.Value.Name == taskName)` returns false => the trigger doesn't get updated to 60 minutes.

### Expected Behavior
The BackgroundTask should run every 60 minutes

### Actual Behavior
The BackgroundTask runs every 15 minutes
Even after reinstalling the app, the background task runs every 15 minutes, because the code block that registers the trigger never got executed again.

## System

* **VS Version:** 2017.8.0 (15.8.0)
* **WTS Wizard Version:** 2.3.18212.1
* **WTS Template Version:** 2.3.18212.1
* **Windows Build:** 17134

**Comment by sibille** [comment]
@Ullmie02 Thanks for your feedback. We included this check, because if a task is registered multiple times it will run more than once whenever triggered, as described [here](https://docs.microsoft.com/en-gb/windows/uwp/launch-resume/register-a-background-task).

To achieve what you want to do, you can modify the register method, to unregister, and then re-register it again. In the templates we could change the Register method a bit, to get the taskRegistration, so you can unregister easier, would that help?

```
var taskRegistration = BackgroundTaskRegistration.AllTasks.FirstOrDefault(t => t.Value.Name == taskName).Value;
if (taskRegistration == null)
```

**Comment by Ullmie02** [comment]
@sibille That would be great. Thank you

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.19.18299.1
Wizard version: 0.19.18299.1
