### ISSUE TITLE
Inconsistent Template Folder Names on VisualBasic

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2527]
While I was working on #2465 I see that VisualBasic templates use the same name that CS templates adding VB at the end of the name. We should use a dot to separate the end of the name and the VB term, to follow a logical order in an alphabetic order.

**Current Order**
Project.TabbedPivot
Project.TabbedPivot.AddTabbedPivotItems
Project.TabbedPivot.AddTabbedPivotItemsVB
Project.TabbedPivotVB

**Correct Order**
Project.TabbedPivot
Project.TabbedPivot.VB
Project.TabbedPivot.AddTabbedPivotItems
Project.TabbedPivot.AddTabbedPivotItems.VB

**Comment by mvegaca** [comment]
We've seen that using dot is not enough to follow an alphabetic order, we can use _ to get this result

![image](https://user-images.githubusercontent.com/5556784/44851744-95cf5c00-ac61-11e8-864c-3bb8c55aae06.png)

We think that is important to see togueder the same template on CS and VB languages. What do you think on this folder renames @mrlacey ?

**Comment by mrlacey** [comment]
What benefit doe the alphabetical order have?

In addition to changing this folder names, all the scripts and tests that depend on the current naming convention would also require changing and reverifying.

**Comment by mvegaca** [comment]
The benefit is to keep together c# and VB templates, when these become separated, making the folder list easier to understand.

**Comment by mrlacey** [comment]
If I recall from when I first created the naming pattern, due to the names of some other folders there would always be some cases where things wouldn't always pair up perfectly. Those folder names (in composition, probably, as that's where some of the names got very long and complicated) may have been changed since then. 
Explorer doesn't use pure ASCII order for ordering and so other code that looks at the order may not produce the same results. This shouldn't matter for existing code though, as it works with the current naming system.
If it's really important and there are no consequences elsewhere then do it.

However, as this will change ~half of the template files it can't be done at any time when any of those files are being worked on without causing merge issues.


At the same time as doing this, is it also worth reviewing all file/folder naming conventions? There are some folders which already use a combination of dot/period and underscore in dividing up the names (presumably to aid readability.) If making a big change to rename a vast number of filepaths for consistency and readability it seems sensible to me to review (and change if necessary) all of them in one go.

**Comment by mvegaca** [comment]
Ok on the renaming using [Git command](https://git-scm.com/docs/git-mv).

Regarding the folder naming, I've shown that VS Code and file explorer have different behaviors.
templateName_VB is valid to VS Code but not is valid for File Explorer.
We need to fix a order based on ASCII Table and not use [restricted characters](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file).

We think the following is the best option and it works on VSCode and File Explorer.

Sample in File Explorer
![image](https://user-images.githubusercontent.com/5556784/52123003-189b7f00-2625-11e9-9d7e-a63078d0a656.png)

Sample in VS Code
![image](https://user-images.githubusercontent.com/5556784/52123025-25b86e00-2625-11e9-9f4e-5ce12f1598d1.png)

We'll try to adapt Scripts affected by this change. Are all affected scripts on _utils folder @mrlacey ?

**Comment by mrlacey** [comment]
There is no guaranteed order for sorting ASCII file names that is used everywhere. As this rename task is to help you when viewing the directory structure, use whatever works with the apps you are using.

There are affected scripts in the `_utils` folder.

There are also tests (in Core.Test and Templates.Test) that will be affected too.

**Comment by sibille** [comment]
Done
