### ISSUE TITLE
Page Navigation - Memory Leak

### ISSUE THREAD

**Issue by Pinox** [Microsoft/WindowsTemplateStudio#2785]
Hi ,

I'm noticing that ts is using a fair amount of RAM simply navigating between pages (Views).  I'm using page navigation menu , mvvmlight and then all the sample pages.  When iterating between the pages I have observed the following RAM usage.  

![ram](https://user-images.githubusercontent.com/5297255/49426875-86086c00-f7aa-11e8-8242-46628231c8f7.PNG)

Is this buildup of memory a general issue (bug / lazy GC) with UWP or simply a case where the navigation back stack starts building up ?  Is there a way to mitigate this buildup as the template is fairly simple and with some resource heavy content on the pages I can see this becoming a big problem ?

using VS 15.9.2

![ts](https://user-images.githubusercontent.com/5297255/49427292-a5ec5f80-f7ab-11e8-94f9-34b02adb1577.PNG)

**Comment by mvegaca** [comment]
I'll have a look here, thank you @Pinox

**Comment by mvegaca** [comment]
Hi @Pinox 

We were doing a memory performance analysis with an MVVMLight app (all pages, x64, Release).

Demo steps:
 - Launch the app.
 - Navigate across all pages.
 - Navigate all pages back.
- Random navigation through the app pages.

What happens:
 - The app starts with low memory usage.
 - The app increases memory consumption while different pages are navigated.
 - When some pages with heavy content like webview or media player are left, the app releases some memory.
 - After all pages are navigated the app is consuming around 375mb in memory.
 - When all pages are navigated back, the app doesn't release memory because all pages are alive in memory, all pages are referencing the ViewModelLocator that this is a singleton instance in the app.

Memory analysis results for MVVM Light.

![image](https://user-images.githubusercontent.com/5556784/49946195-c1afde00-feee-11e8-9dca-203f5db03e4a.png)

IMO, I don't think there is a memory leak in MVVMLight design pattern apps, but these apps keep all pages and viewmodels alive in memory during runtime. @LBugnion Any thoughts on this?

**Comment by Pinox** [comment]
Thanks @mvegaca for looking into this.

I only did my initial test in Debug mode. Running it in Release mode I get the following results per 10 iterations (selecting all pages) starting from launch.

![mem1](https://user-images.githubusercontent.com/5297255/49955167-dbf7b500-ff0a-11e8-8799-d093d7417d12.PNG)
![mem2](https://user-images.githubusercontent.com/5297255/49955173-ddc17880-ff0a-11e8-8d94-acad796b89ae.PNG)
![mem3](https://user-images.githubusercontent.com/5297255/49955178-df8b3c00-ff0a-11e8-803c-13c3c9142d9e.PNG)
![mem5](https://user-images.githubusercontent.com/5297255/49955182-e0bc6900-ff0a-11e8-8f12-f725046eec70.PNG)

I managed to push the memory envelope to about 750MB.  In both instances the app crashed before I could grab a screenshot as I was pushing for 800MB.   I can see that Windows is releasing memory much more aggressively but I still see a continued escalation in memory usage until the app crashes.

No idea what to think about this as I don't have a reference to what is acceptable but starting from 17MB and growing to 750MB is either a very lazy GC or somewhere something is not right.

**Comment by crutkas** [comment]
Is your device a higher end one or are you making an assumption on how memory management should work. I would test in a VM under heavy ram constraints to see. I don’t care if an app uses my ram, I think if it can’t allocate that is an issue

**Comment by Pinox** [comment]
@cruskas good point,  using HP 12GB RAM SSD. Will check tomorrow in lower spec machine.

**Comment by mvegaca** [comment]
We did some test and we think it could be caused by the MediaPlayer page, it isn't disposing the media player source.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.20.19021.2
Wizard version: 0.20.19018.3
