### ISSUE TITLE
SuspendAndResume needs to take place in addition to ActivationService

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WindowsTemplateStudio#2814]
## For Bugs:
The current ActivationService picks the first service which can handle the activation and then completes, but there are scenarios where multiple things may be going on in an app when it activates.  For instance, if I always want to use SuspendAndResume to save/restore state for my app, then when I activate my app with a file opening, I'd want a combined result, but can't do that today.

### Repro steps

Use SuspendAndResume and FileActivation.

### Expected Behavior
Be able to restore state and open new files.

### Actual Behavior
Only restore state and ignore new files.

**Comment by sibille** [comment]
I think we'll have to look into this for Identity and forced login too.

**Comment by michael-hawker** [comment]
Actually, the activation service may be fine as is.  It may be more that the `SuspendAndResumeService` doesn't belong as part of Activation.

Your app can only be activated by one thing at a time, so you'll never both get a file handling activation and a protocol activation, so it makes sense that if you have multiple services registered to the WTS activation service, only one is needed.

However, during activation is when you'll want to restore state to your app if you had stored some during suspension.  So, maybe Suspend/Resume needs to be handled outside of the framework of the ActivationService itself as a separate mechanism.

@mrlacey @sibille thoughts?

**Comment by mrlacey** [comment]
Being able to handle multiple activation types would help with more than just Suspend&Resume.

At the moment we have things like SchemeActivationHandler which has code that always says t `CanHandle` the activation but has checks in `HandleInternalAsync` that if fail mean it runs code that is a duplication from the default handler.

I'd rather see multiple activation handlers have the possibility of being called. They'd need a way of having an order/priority defined and a way of indicating if subsequent handlers shoudl also be allowed to run.

So, S&R would have a priority of 1 and would always return that other handlers can run after it.
SchemeActivation would have a mid range priority and if it couldn't handle the activation (e.g. because of a malformed URI) it would return that other handlers can run after it and so the default handler (or any other handler) would subsequently run and mean logic is not duplicated.
The Default handler would have a priority of Int.Max.


Yes, this'd be a breaking change but so would changing the way S&R works to be separate from other activation handlers.

**Comment by sibille** [comment]
@michael-hawker we implemented the SuspendAndResumeService as ActivationHandler, because it navigates to the page the app was suspended on in case of app termination. 
In the case you mentioned: The app was terminated and gets activated from the FileActivation, the FileActivationHandler would handle the activation. What would you expect the S&R service to do, just restore the data, and leave it available for the app? 

@mrlacey I thought of a similar model, but tyhink it is quite complex, and what Michael says is true, you can only come from one activation type. If this activation fails, a DefaultActivationHandler should step in and go to the homepage.

**Comment by michael-hawker** [comment]
Yeah, I think the problem with resume 'activation' and file handling is then dependent on app architecture.  I have a multi-document app, so I'm always navigating to the same main page, and then I just load up the files as new documents and can resume back to the previous selected one.

However, someone may have a single-document app, where resuming and file opening could be in conflict, so it'd have to be up to the app developer to decide what they want to take precedence, or maybe they want to pop-open a new window, so in essence activation opens two windows one navigated to the previous state and one to the file opened.

At the root though from the app being activated on a technical perspective, it's highlander, there can always only be one entry point.

**Comment by sibille** [comment]
@michael-hawker, coming back to this issue, I think SuspendAndResumeService's place in the ActivationService is fine to handle activation after suspension, but, depending on the App, you could use the saved data elsewhere too. 
Would exposing a public method on the SuspendAndResumeService service, that allows you to get this data from elsewhere help?

**Comment by michael-hawker** [comment]
@sibille you mean like being able from the FileActivationHandler also grab the suspended data?  Possibly, but then I'd be just calling out to some other centralized thing that I have to create now to hold my re-hydration logic from each of the other handlers.

I feel like SuspendAndResume should just be it's own service outside of activation.  It could be called first, then an app gets to restore its state.  Then the activation handler gets called and it can know if there's a 'new' thing to do on top of that?

**Comment by sibille** [comment]
Not sure if I understood what your proposing. Having it implemented as an activationhandler allows the app to restore state and navigate to the page the app got suspended if there is no other activationhandler activating.
How would that be covered in your scenario?

**Comment by michael-hawker** [comment]
Yeah, I guess that's the problem. There's contention between needing to resume and get data and then either handling some new activation argument or falling back to the last known state.

But that last known state, isn't really an 'activation' it's just a restoration (if there is one, compared to the default startup behavior).

Feel like the flow should be:

1. Store `navigation_page` as 'default' (for initial start up scenario).
2. If resume data, resume state and set `navigation_page` to stored page.
3. If activation data, run through activation handler list [like it does today] (but now it knows restored data and requested page, it has the option to utilize/modify that information and the `navigation_page`).
4. Navigate to `navigation_page`

**Comment by sibille** [comment]
@mvegaca has been working on a new approach for the SuspendAndResumeService that allows to combine supend and resume with other activations. 

You can see the mockup project here: [Integrated2SuspendAndResumeMockup.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/3080585/Integrated2SuspendAndResumeMockup.zip)

It uses SuspendAndResumeService and UserActivityService (activation from timeline using deeplinking) and has two pages with two input fields that save/resume state. 

@michael-hawker, its a bit different from what you suggested, because changing the defaultnavitem (our default navigation page) would cause issues in the identity features we are building. 
Also passing the SuspendAndResumeData on the ActivationHandlers as an additional argument would be a breaking change and add more complexity to ActivationHandlers. Does this solution

**Comment by mvegaca** [comment]
The idea is starting work in templates on the following days, @michael-hawker Is this approach good for you?

**Comment by PaulaScholz** [comment]
I tried to use Windows Template Studio on an app with Graph Notifications, which uses LaunchActivatedEventArgs. 

The documentation at https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/activation.md is not adequate, the FileAssociation example is too trivial and does not completely reflect what to do with the ActivationHandler overrides, which have zero comments.

It takes too long to understand this.  People have to port code done in the old way, and the examples do not show how a clear path to do this and be compatible with your Services architecture.  

It's too complex, without a real step-by-step, end-to-end example and a sample that illustrates what to do. 

WTS has such promise, but this is a real pain point.

**Comment by crutkas** [comment]
Great feedback. Do you have any pointers on what you wish was focused on/hard the most trouble with.

**Comment by PaulaScholz** [comment]
I need to create a new service under Services to handle Graph Notifications.  I am porting older code, which uses App.OnLaunched with LaunchActivatedEventArgs and also App.OnActivated, and that needs to be reflected in your Services architecture.  Your Activation code will process LaunchActivatedEventArgs before my stuff has a chance to get it and my activation handler will never be called.  This has forced me to back out your Activation code and Suspend/Resume, and write OnLaunched and OnActivated the old-fashioned way.

What I would like are non-trivial examples that implement a real service in the chain of activation handlers, and lots of comments in the code.  WTS is useful for navigation and MVVM, but useless when trying to make older working code fit into your poorly-documented set of Features on the last page of the wizard.  I already have BackgroundServices code that works, but now I have to fit it into your Services architecture, and there is not enough information available in a timely manner to do this.

A porting guide would be helpful.  I recognize that many people don't know how to implement some or perhaps any of the Features and your wizard provides a good guide to them to even know what is available, so that's great.  The MVVM code is also very useful for beginners.

Really, what I have found to be the most useful thing is to not use the Features at all and just do things the old-fashioned way, but take advantage of the UI configuration and Navigation aspects of WTS.  Using the Features stuff is a good guide to see what is available, but since most of the existing Docs samples show how to do things the old way, I just do that because the WTS infrastructure isn't mature enough to rely on for the rest.

Not throwing stones, the WTS stuff that works is great, but I'm afraid you're just sending new people down a maze where they can never get out.

**Comment by sibille** [comment]
@PaulaScholz, thanks for your feedback. I'd love to better understand your scenario and why it didn't fit in the ActivationService + how we could adapt our code to include more complex scenarios. Could you give us more details about the activation flow you are lookin for or share a sample project?

Regarding the docs, we have issue issue #2426 open against the activation service docs, moving it to milestone 3.3 to improve documentation along with ActivationService code.

**Comment by PaulaScholz** [comment]
I would be delighted, but the sample project will have to wait until after Build.

Ideally, I would like to build a Windows Template Studio Feature service that implements Microsoft Graph Notifications (https://docs.microsoft.com/en-us/graph/notifications-concept-overview) and the current GN preview sample uses both LaunchActivatedEventArgs and IActivatedEventArgs, so it would have to be closely integrated with your Activation service to do the right things.

I believe it is important for Graph Notifications to integrate with Windows Template Studio to leverage the excellent UI configuration features of your project.  Such integration would provide a boost to implementing GN functionality in user applications and act as a multiplier for adoption.

Best,
Paula Scholz

**Comment by sibille** [comment]
Thanks @PaulaScholz, created issue #3122 for creating a Graph Notification feature, lets continue talking about what you'd need and how to integrate with the ActivationService there.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19164.1
Wizard version: 0.20.19164.1
