### ISSUE TITLE
Template10 Busy.SetBusy() conversion in WTS?

### ISSUE THREAD

**Issue by myokeeh** [Microsoft/WindowsTemplateStudio#2932]
I'd like to quickly convert an existing Template10 app to Windows Template Studio. One of the hangups I have is the `Busy.SetBusy()` feature in Template10. Is there a similar feature on WTS or is there a suggested approach that's close? I understand approaching the conversion this way may not be best practice.

**Comment by crutkas** [comment]
if this is something you feel should be included as a helpful feature, lets sync with @JerryNixon and you're more than welcome to create a Pull Request to add it in.  Right now i don't think we have concept of that.  Nothing also is stopping you from adding that from T10 to your application as well if you like it.

**Comment by mrlacey** [comment]
> I'd like to quickly convert an existing Template10 app to Windows Template Studio. 

@myokeeh There is no such thing as a "Windows Template Studio" app. WTS is a tool that works with specific frameworks to help scaffold an app that uses one of those frameworks. If you're looking to take an app created with Template10 templates and/or using Template10 libraries and enable the ability to add pages or features with WTS, this wouldn't work as WTS has no pages or features that would work with the project structure and dependencies.

If/when the Prism&T10 merger/collaboration completes, that may provide the possibility for an upgrade path.


We have previously looked at enabling support for the ability to add a page or feature to an app that wasn't initially created with WTS but little progress has been made on this due to a lack of people askign for this. If you have a good reason for needing that capability, [please add details on that issue](#663).

**Comment by myokeeh** [comment]
@mrlacey, please excuse my choice of words--and really appreciate the clarifications. A lot of this is new to me.

I only recently learned about the work Jerry put into Prism (https://twitter.com/jerrynixon/status/1100941828528824320?s=20), but unsure about what's going on with Prism ((https://twitter.com/prismlib/status/1099095031757996032?s=20))

I was already on my way to switching to use of WTS before knowing the above.

I think I have a solution to my "Busy" hang up, so I can chug along again.

Thanks!
