### ISSUE TITLE
Visual Studio WTS Extension in VS2019 defaults to Visual Basic

### ISSUE THREAD

**Issue by PaulaScholz** [Microsoft/WindowsTemplateStudio#3111]
#### Overview

When creating a new Windows Template Studio project with the project template wizard in Visual Studio 2019, the default language selected is Visual Basic.  Now, I have nothing against VB, but I'm willing to bet that only a small percentage of devs use this for UWP development.

The default should be C#.

#### Repro steps
1.  Launch VS 2019
2.  Under "Get Started", select "Create a new project"
3.  Scroll down to "Windows Template Studio (Universal Windows)

Note that the default language selection is "Visual Basic".  If you don't specifically check this, you'll get a VB project, which most people don't want.

#### Expected Behavior

The default language choice should be C#.

#### Actual Behavior

The default is Visual Basic.

### System

* **VS Version:** 2019 16.0.2
* **WTS Wizard Version:**  3.1.19092.1
* **WTS Template Version:**  How would you know?
* **Windows Build:**  10.0.17763

**Comment by crutkas** [comment]
Can you give us a screenshot of your file->new prompt?

**Comment by PaulaScholz** [comment]
![WTS_NewProject](https://user-images.githubusercontent.com/45177251/56858764-cd97bc00-6934-11e9-8e2e-921d590cbf7c.PNG)
Note the default.  If you aren't paying attention, you'll get a Visual Basic project.

**Comment by crutkas** [comment]
One above is c#. This is an artifact of the new dialog for vs2019. Maybe we need a language option too in the wizard. 😐

The VS dialog also does have a language filter

**Comment by PaulaScholz** [comment]
You do have a language option, next to the “Search for project templates” box.  It’s how I got what I really wanted, which was C#.  But, the steps I took to get to my first WTS project were to go to Platform and select UWP, and scroll all the way to the bottom, where my UWP WTS option was located.  I didn’t pay attention to the Language or Platform choices, and the default language choice provided to me was Visual Basic.

Now that I have made this mistake, I will always go through the additional step of choosing the Language with the wizard as it is now.  What I’m saying is that the default language when I only select from “Platform” for UWP should be C# and not Visual Basic.

Maybe this isn’t your problem and instead is a VS issue.  I don’t know.  But, it will cause many people to throw away their first generated WTS project.  It’s more of an annoyance than a problem, because once you understand how it works, you adapt.  But, it makes for a poor initial user experience.

Just some feedback.  😊

Best,
Paula

**Comment by mrlacey** [comment]
Putting this down to a misunderstanding with the new New Project Dialog (NPD).
Apparently, improvements are planned for the NPD and hopefully, they will avoid such confusion in the future.

**Comment by rrvenki** [comment]
In normal condition the language should default to the keyboard settings you have selected in VS\Tools\Options\Environment\Keyboard\Keyboad Mapping Scheme.  If you did not choose any and leave the keyboard to "default", the template choice will be as per available language.  If you had selected "Visual Basic 6" the default language, the template will be in VB.NET.  I continue to choose this (VB6) because I'm used to the keyboard settings of VB since quite long (1993+) and not easy to change now. So I see VB related templates and deliberately miss all other language goodies which I care least.

For sure it must not default to C# or even VB. @PaulaScholz comment of "small percentage of devs in UWP" may not be correct as per several (biased) ratings too.  It should always choose the default language selected in Tools\Options\Environment\Keyboard.

**Comment by mrlacey** [comment]
If the issue is with the default option selected in the New Project dialog, that's not something we can change as an extension provider.
If you find a problem with Visual Studio (such as it not selecting the correct default programming language) you'll get a better response by raising the issue as per https://developercommunity.visualstudio.com/content/problem/post.html?space=8
