### ISSUE TITLE
Disable mouseover styles on already added templates.

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3163]
I think that mouseover effects should be disabled on already added features.

**What is happening now**

When you move the mouse over a template that was no added the background and the border brush change and a + icon appears on the top-left corner.

![image](https://user-images.githubusercontent.com/5556784/58622974-31632b00-82cd-11e9-8e5d-6ce5367de983.png)

If you add this feature, the feature is marked as added.

![image](https://user-images.githubusercontent.com/5556784/58623079-6a9b9b00-82cd-11e9-8e3f-237fcd017994.png)

When this template is added the + icon disappears but you can still see the mouseover effects.

![image](https://user-images.githubusercontent.com/5556784/58623164-a5053800-82cd-11e9-9786-1c7f4fc1786e.png)

**What I think should happen**

The mouseover effects should disappear too.

**Like this**

![image](https://user-images.githubusercontent.com/5556784/58623251-dc73e480-82cd-11e9-90f2-c7ca55edabd3.png)

**Comment by mrlacey** [comment]
The purpose of mouse-over effects is to make it clear what control the mouse is over.
This is different from an enabled/disabled state.

As it stands, the mouse-over visual state just shows what the cursor is over, the plus sign indicates items that can be added, and the "Added + tick" text & graphic show items that have been added. 

It sounds as though you want to change the meaning of what the mouse-over state implies.

Has there been user feedback that the current functionality is confusing or otherwise problematic?


I don't see any benefit to making the proposed change here other than to meet an individuals personal preference. I'm happy to be convinced differently though.

**Comment by mvegaca** [comment]
From my point of view, if a template is a single instance and it's already added, the template should be disabled, and disable buttons should no have visual effects.

Have a look at the Issue comment box.

"Comment" button is disabled and does not have mouseover effects.

![image](https://user-images.githubusercontent.com/5556784/58627017-7475cc00-82d6-11e9-8de4-32020ca52c83.png)

But Close Issue is enabled and it has mouseover effects.

![image](https://user-images.githubusercontent.com/5556784/58627368-5f4d6d00-82d7-11e9-9b92-6daff350300d.png)

**Comment by mrlacey** [comment]
Do you have examples from elsewhere within Visual Studio?
Remembering of course that the current designs are from the Visual Studio design team.

Also, how will your proposal work with items that can be added more than once?

**Comment by mvegaca** [comment]
On VS disable options lose the mouse over effects.

![image](https://user-images.githubusercontent.com/5556784/58628786-f49e3080-82da-11e9-8f91-6668ab7b7c4b.png)

I know that wizard design was review by VS Team, I open this Issue to listen to different opinions, from my point of view, if the template is added and it loose the mouseover effects, it's more clear that this is already added. Pages that can be added multiple times never should lose the mouseover effects.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19263.1
Wizard version: 0.20.19262.1
