### ISSUE TITLE
Postaction refactor

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3256]
While working on 3.3 we found some issues with merge and search and replace postactions that should be tackled:

- SearchAndReplace postactions do not fail when they do not find the line to search and replace
- Identity templates combine SearchAndReplace Postactions and mergepostactions on some files, 
	See if we can do everything with mergepostactions
- MergePostactions are doing some adjustments to code before inserting that is only valid for cs, it is not causing problems on other languages, but we refactor this to apply only to cs files, and provide the same possibility for other languages as this might get necessary

Action plan: 
- [x] Refactor postactions 
- [x] Replace uwp search and replace postactions in templates by inline additions (except on Stylecop templates where search and replace postactions are a better fit)
- [x] Do inline additions for ignorable namespaces not added currently

**Comment by mrlacey** [comment]
> Identity templates combine SearchAndReplace Postactions and mergepostactions on some files,
See if we can do everything with mergepostactions

I think the ways multiple templates need to modify the same line makes this impossible. If I recall correctly, this was one of the reasons the Search&Replace functionality was originally added.
Without it you need to make multiple composite templates to allow for every combination and variation of user selection.

There was a reason that search&Replace originally failed quietly but I don't remember the specifics of why.
Test this thoroughly as I'd expect something to fail (or not work in the generated app) when made to cause a replacement to fail. Things may have changed since then though.

If adding reporting for s&r actions that fail, it might also be good to also add reporting for merge actions that don't change anything. I think I've seen a few of those and it might be another opportunity to remove actions that aren't needed to remove possible duplication.

**Comment by mrlacey** [comment]
> There was a reason that search&Replace originally failed quietly but I don't remember the specifics of why.

I think I've remembered (or at least hit a similar issue)
This was done to avoid the need to abstract every minor modification of a single line into separate composition templates.
This meant that fewer templates were needed overall and if a selection allowed doing something multiple times it wouldn't matter if it had already been done for another item in the selection.
This may, or may not be the best solution and other, subsequent changes may mean this isn't relevant. But, that's the background.

**Comment by sibille** [comment]
For WPF we need postactions that are able to modify the constructor of classes to inject dependencies.

The problem here is, that we do not know the rest of parameters already available on the method signature, so we cannot use the search and replace postaction, neither remove + addition statements. 

Proposed solution is introduction of a new merge directive that allows inline additions. 

They could be defined with something like this: 

```
public ShellViewModel(/*{[{*/IdentityService identityService, IUserDataService userDataService/*}]}*/)
```

The merge postaction will look split the line into Context (Start and End) and Additon. 
ContextStart is `public ShellViewModel(`
ContextEnd is `)`
Addition is `IdentityService identityService, IUserDataService userDataService` 

The postaction will look for a line starting with 
`public ShellViewModel( (ContextStart)`
and insert the content between the merge instructions before the `)` (ContextEnd).

**Comment by mrlacey** [comment]
For the new directive, will this be contained in separate files or will this be additional supported syntax in existing `*_postaction.*` files?
Also, will the merging be clever enough to include separating characters when they're needed?

e.g. could it correctly add `IdentityService identity` to both of the following existing lines?

```cs
public ViewModel1()

public ViewModel2(IDataService data)
```

---

This would also be useful for improving some of the merging that is done with appxmanifests in UWP projects. At the moment these don't include all the ignorable XML namespaces the should - because there's currently no way to update them correctly in all scenarios.

**Comment by sibille** [comment]
Yes, the idea is to have all modifications on a file (from one template) in the same *_postaction.* file. 
And yes, this will work in both scenarios, inline addition detects your inserting between parentesis and adds the comma separator if necessary. 

This should work for ignorable XML namespaces too, will have a look.

**Comment by sibille** [comment]
Regarding the Search and Replace Postaction: 
I think the postaction should report a failure if neither the search nor the replacement value is found.

**Comment by sibille** [comment]
Opened an issue on CoreTS to track the changes there, keeping this open to track template changes.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.20008.1
Wizard version: 0.20.20008.1
