### ISSUE TITLE
Feedback Hub Link not available on right click

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/WindowsTemplateStudio#3294]
The Feedback Hub Link feature is only available when creating a new project.  I think this should also be able to be added as a feature after the project has been created from the Windows Template Studio menu.

**Comment by mrlacey** [comment]
This wasn't done when the feature was added because of an issue with potential naming collision issues.
I've looked back through the notes at the time (on the [PR](https://github.com/microsoft/WindowsTemplateStudio/pull/1214) and [original issue](https://github.com/microsoft/WindowsTemplateStudio/issues/196)) and think that the original issues are no longer relevant due to other subsequent changes.
Will need thorough testing to verify this though.

**Comment by sibille** [comment]
Agree with @mrlacey, I think the original issue is no longer relevant.

**Comment by sibille** [comment]
@mvegaca, we should use global postactions for additions on the settings page here.
Also, make this available on right click for MVVMToolkit framework.

**Comment by mvegaca** [comment]
Added a new PR setting Feedback Hub Link postaction in Settings page and ViewModel as Global Postactions

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.20336.2
Wizard version: 0.22.20336.2
