### ISSUE TITLE
Feedback requested for WPF mockup (MVVMBasic + NavigationView)

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3318]
We'd love to hear your feedback on our first WPF mockup. You can find the solution at https://github.com/mvegaca/MyDotNetCoreWpfApp/blob/dev/MVVMBasic.sln

Project setup is the following: 

**ProjectType**:  
 - NavigationView (using Hamburger Menu)

**Framework:** 
- MVVMBasic

**Pages**: 
  - Blank
  - Settings

**Features**: 
  - MSIX Packaging
  - Theme Support (Dark/Light)
  - Setting Storage / Persisting app data
	
More mockups for other project types and frameworks will come soon.

**Comment by rasyidf** [comment]
**a little thought about the mockup**

1. I'm a novice programmer, but in Basic MVVM patterns, is Contracts needed, because i don't see it in the UWP template version?

2. The UI using MahApps is a great choice. and I think, would it be nice if someone could make it look more "fluent" as in the Remote Desktop Preview application (if I'm guessing it right, its WPF).

3. I have so many warning when building the project, the nuget is not restoring correct framework ( Restoring Net FX 4.8 instead of .NET Core ) , is this intentional?

last thing is, a big thanks for the team effort.

**Comment by sibille** [comment]
Thanks for your feedback! We're working on point 2 + 3. For 1:  The reason for this is we're using dependency injection for WPF as requested by community, that's why the interfaces are needed.

**Comment by LoriBru** [comment]
Why using MahApps instead of taking advantage of Windows UI?

**Comment by Kinnara** [comment]
I made a fork of the mockup that uses my library [ModernWPF](https://github.com/Kinnara/ModernWpf) to complement MahApps. It brings WinUI-like styling to the app while retaining the ability to use the advanced MahApps controls (e.g. HamburgerMenu). [Check it out](https://github.com/Kinnara/MyDotNetCoreWpfApp/tree/dev/MyDotNetCoreWpfApp) if anyone's interested.

![Screenshot](https://github.com/Kinnara/MyDotNetCoreWpfApp/raw/dev/MyDotNetCoreWpfApp/screenshot.png "Screenshot")
