### ISSUE TITLE
WPF Feature: Toast Notifications

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3614]
Add a Toast Notifications template for WPF.

Doc links:

 - [Toast Notifications Sample for Windows desktop](https://github.com/WindowsNotifications/desktop-toasts)

Action Plan:
 - [x] Create mockups
 - [x] Product team validation
 - [x] Create templates
 - [x] Add MVVMToolkit compositions
 - [x] Target to final Nuget Version
 - [x] Add docs

**Comment by mvegaca** [comment]
Working on mockups in [this repo](https://github.com/mvegaca/WPFToastNotificationsMockups).

**Comment by mvegaca** [comment]
Moved to 3.9 version as this depends on new release of ToastNotification library that removes the dependency with MSIX package for Desktop apps.

**Comment by mvegaca** [comment]
Nuget updated and added to PR #3885

**Comment by sibille** [comment]
Moved to 3.10, as we're waiting for the Windows Community Toolkit Notification NuGet package to be released

**Comment by sibille** [comment]
The ToastNotification feature requires the addition of an _isInitialized check in the ApplicationHostService to avoid double-initialization of services like ThemeSelectorService, PersistAndRestoreService and IdentityService). 

This causes a breaking change when adding a new SettingsPage (or when adding the features PersistAndRestore or  ThemeSelectorService) using Right Click on projects created prior to version 3.10.

There are two postactions that can't be executed due to this change and require manual edition: 
Current experience is: 
![image](https://user-images.githubusercontent.com/24698018/114385642-8b52fe00-9b90-11eb-8b02-5fca32ee11a5.png)

We should decide if this experience is sufficient or if we want to:
1) Add more detailed instructions on the release notes 
2) Do a breaking change message for this case

**Comment by mrlacey** [comment]
The number of people this is likely to affect is small, I don't see a problem with introducing this breaking change.

> 1. Add more detailed instructions on the release notes

Yes, definitely

> 2. Do a breaking change message for this case

Where would this message be shown?
What would it contain? (Is the plan to include a brief description of the issue or thorough documentation and explanation?)

**Comment by sibille** [comment]
> Where would this message be shown?
> What would it contain? (Is the plan to include a brief description of the issue or thorough documentation and explanation?)

It would be shown when trying to add a new page or feature to the project using WTS right-click.
The breaking change validation would inspect the user's code to see if it already includes the _isInitialized flag and would show a message similar to this one in case it doesn't. 

The message contains a link to docs with more detailed information.
![breaking_change](https://user-images.githubusercontent.com/24698018/38931740-7b90149e-4314-11e8-8b8c-4adaf6a50ef0.PNG)

**Comment by sibille** [comment]
> We should decide if this experience is sufficient or if we want to:
> 
> 1. Add more detailed instructions on the release notes
> 2. Do a breaking change message for this case

We decided to go with the first solution. The _isInitialized was added to appropriately handle ToastNotification, it's not needed if you add pages and features to an existing project.

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.22.21109.1
Wizard version: 0.22.21109.1
