### ISSUE TITLE
Feature: Share target

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#365]
Add a feature which includes the functionality to enable the app to be the target of sharing.

Split from #358

**Comment by crutkas** [comment]
@mrlacey bump both of this to 1.4, you ok with that?

**Comment by mrlacey** [comment]
bumping is good with me

**Comment by mvegaca** [comment]
PR added #1324 

MVVM Basic only, I want you can check it out in Dev Nightly to can give opnion and improvements before translate ir to other frameworks.

Feature allows to share Images (Edge) and Photos (Windows Photos) with the generated app with Share Target declaration.

Implementation includes:
- Activation from share target in App.xaml.cs
- ShareData extension file
- Model data
- DataTemplateSelector to show different layout between Web Link and Images share layout.

**Comment by mvegaca** [comment]
@crutkas @mrlacey have you look that feature on MVVM Basic? Do you have any comments or improvements?

**Comment by mrlacey** [comment]
haven't had a chance to look at it yet

**Comment by mvegaca** [comment]
Translated to MVVMLight, CodeBehind and CaliburnMicro in #1332

**Comment by mvegaca** [comment]
@nigel-sampson can you review the feature on CaliburnMicro??
I've found differences in App.xaml.cs files and I've added a different template ShareTarget.CaliburnMicro. I was having errors on ViewModels registration when App was launched from ShareTarget activation and I fixed it with a workaround on ExamplePage ViewModel creation.

**Comment by ralarcon** [comment]
You are right mrlacey, I personally asked to finish the template (even re-work needed) as it was no so much effort. We didnt't assume tacit approval.

A the same time, I have decided that, before creating a template, and in order to have better discussions arround features, we will share the approach using a PoC app.

**Comment by mrlacey** [comment]
So, having a look at the output in DevNightly (0.14.17296.1)
_Because I've been forced into reviewing this now before it's marked as complete without anyone reviewing it._

- No icon
- No short description (it's lorem ipsum)
- No detailed description (this may be a good place to link to more information, etc.)
- As per #827 this feature should not be listed under "User Interaction"
- ShareTargetExamplePage includes unnecessary using statements
- SharedContentTemplateSelector is used only by ShareTargetExamplePage but there's nothing to 
- ShareTargetExamplePage includes localized resources that will be left behind once the example page is deleted.
- The logic in `App.OnShareTargetActivated` should be in a separate class that inherits from ActivationHandler like all the other activation handling code that's generated. As a pattern has been established for handling code activation all generated code should follow it.
- Documentation in the generated code should point out that declarations have been added to the manifest for the specific types of content the example page supports but these may need to be changed/removed in the final app.
- It would be really useful to include something in the generated code to explain how to test the app as generated.
- I'd also like to see how to navigate to a page within the app shell (NavPane or TabbedPivot) and not just a standalone page.
- I'd expect that the app launched by sharing should be able to run all functions of the app and this includes doing things like starting background tasks, etc. which are handled by `ActivationService` but this isn't currently called when launched as a share target.
- The use of a template selector in the sample page seems totally unnecessary and is just adding more generated code that isn't necessary.
- Opening the share target sample page without an app entry in the taskbar can be confusing.

Some of the above may be intentional but as they're not documented I can't know.

It seems there are two share target scenarios
- open a single page to just handle what was shared.
- open the app normally and handle what was shared.

It might be worth considering these as two separate features or generating code that makes it easier for the person working with the generated code to choose which they want to use in their app.

Additionally, merging work that is obviously not complete into the main (dev) branch leaves it unclear if it is finished or not. Work should continue in a separate branch until it is finished. When this doesn't happen it's hard to tell what is finished and multiple extra issues and changes need to happen before the work is complete. It also discourages thorough testing before raising a PR as more testing can be done in the future and by someone else. (See also development of the ImageGallery page)
It's possible to review work without raising a PR and without needing it to go into the nightly build.

**Comment by mvegaca** [comment]
> No icon
> No short description (it's lorem ipsum)
> No detailed description (this may be a good place to link to more information, etc.)

I'll open different Issue with that

> As per #827 this feature should not be listed under "User Interaction"

I'm going to set App to App category

> ShareTargetExamplePage includes unnecessary using statements

I'm going to fix it.

> SharedContentTemplateSelector is used only by ShareTargetExamplePage but there's nothing to

We use it to show different layouts.

> ShareTargetExamplePage includes localized resources that will be left behind once the example page is deleted.

We always must work with localized texts, It's the same like others example pages.

> The logic in App.OnShareTargetActivated should be in a separate class that inherits from ActivationHandler like all the other activation handling code that's generated. As a pattern has been established for handling code activation all generated code should follow it.

I've created a separate method in ActivationService because ShareTarget activation is different from ToastNotifications, Cortana, LiveTile or other activations. It doesn't open the app regularly, it opens a new app instance if the app is already opened. If you compare with other apps like twitter or mail app, you can be using the app and other apps can open a new mail or new tweet window even if the app is already launched.

> Documentation in the generated code should point out that declarations have been added to the manifest for the specific types of content the example page supports but these may need to be changed/removed in the final app.

I'm going to add it.

> It would be really useful to include something in the generated code to explain how to test the app as generated.

I'm going to add it.

> I'd also like to see how to navigate to a page within the app shell (NavPane or TabbedPivot) and not just a standalone page.

It's like on mail or twitter app, if you share a URI with Twitter you only access to a tweet writing window, not to the full twitter application, this is the idea of share target, access only to the specific page that can use shared data.

> I'd expect that the app launched by sharing should be able to run all functions of the app and this includes doing things like starting background tasks, etc. which are handled by ActivationService but this isn't currently called when launched as a share target.

This feature doesn't know if a background task is already added or not, this feature adds an atomic function that it can be used or tested alone. If we want to add a more complex scenario we can discuss it but the is the minimum functionality.

> The use of a template selector in the sample page seems totally unnecessary and is just adding more generated code that isn't necessary.

We are showing how to share two different kinds of contents using a different layout for each kind of content (FlipView for images and Hyperlink for Uri).

> Opening the share target sample page without an app entry in the taskbar can be confusing.

Share Target execution is a modal window over the active app not is a regular app instance. As far as I know, this behavior is defined by default (like twitter and email).

> ShareOperationExtensions seems very specific to the example page. Is this really needed? Could it be moved/merged elsewhere?

The idea is that user can use these methods to implement his own share target page. What I'm going to do is to include the rest of data types format in the method.

**Comment by mvegaca** [comment]
Updates on share target feature on PR #1347

**Comment by mvegaca** [comment]
@crutkas can you have a final look on this just to be sure there is nothing left?

**Comment by mvegaca** [comment]
Fix checked on
Wizard: 0.14.17320.65001
Templates: 0.14.17320.1
