### ISSUE TITLE
TabView seems to be broken

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsTemplateStudio#3654]
**Describe the bug**
The binding doesn't seems to be working whilst displaying tab view data.

**To Reproduce**
1. Select Blank App
2. Select MVVM framework
3. Add TabView and remove Main page
4. Generate app

The header data is not shown, instead the object type is shown in the header. Changing the header is changing the Content. The content is not displayed. 

**Expected behavior**
The header and content are displayed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/8557046/81500808-ebee1100-9317-11ea-8255-59b5d97aaac6.png)

**Additional context**

**System**

- **VS Version:** 16.5.4
- **WinTS Wizard Version:**3.5 
- **WinTS Template Version:**3.5 
- **Windows Build:** 1803

**Comment by mrlacey** [comment]
I couldn't recreate this.
Which MVVM framework did you select?

**Comment by harvinders** [comment]
MVVMBasic

**Comment by harvinders** [comment]
@mrlacey I think the issue is in winui for 1803. Here is a screenshot of the xaml gallery in 1803. Did you verify the issue on 1803 or a different version?


![image](https://user-images.githubusercontent.com/8557046/81534930-38832c00-93ac-11ea-86a7-58927297dbca.png)
 
If I change the header it changes the content area. The xaml below still displays the content as `ABC`

```
        <winui:TabView.TabItemTemplate>
            <DataTemplate x:DataType="models:TabViewItemData">
                <winui:TabViewItem
                    Header="ABC"
                    AutomationProperties.Name="{x:Bind Header}">
                </winui:TabViewItem>
            </DataTemplate>
        </winui:TabView.TabItemTemplate>
```

**Comment by mrlacey** [comment]
The generated project has a minimum target version of 1809.
Windows Template Studio (WinTS) only supports the two most recent versions of Windows when a version is released. WinTS version 3.5 was released in November 2019 and officially supports and was tested against 1903 & 1809.
Support for only the two most recent versions (often referred to internally as 'n & n-1') as a way to balance the ability to include newer functionality but still support a wide range of install targets.
Unfortunately, this means that if you need to support older versions of Windows 10, some functionality may not work as expected. Based on [the most recent AdDuplex stats](https://blog.adduplex.com/2020/04/30/adduplex-statistics-report-for-april/) generated apps will work on >90% of Windows installations. For everything else, you will need to balance whether you support those other versions and test accordingly.

I recommend you continue to follow-up with the WinUI team for a possible fix from them, or consider using the [TabView control from the Windows Community Toolkit](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview) instead.

As this issue is with an external control in an unsupported scenario I will close this issue.


X-Ref: https://github.com/microsoft/microsoft-ui-xaml/issues/2427
