### ISSUE TITLE
Login feature makes app crash

### ISSUE THREAD

**Issue by LoriBru** [microsoft/WindowsTemplateStudio#3698]
I am using version 3.6.20139.1 and Visual Studio 16.6.1.
Creating an application with the Login feature (either forced or optional) makes the application crash at startup.

![image](https://user-images.githubusercontent.com/22811725/83603930-90f5b580-a575-11ea-8dde-61eeb734ad40.png)

**Comment by sibille** [comment]
@LoriBru, thanks for reporting!
Could you give more details on the framework/proyecttype you used to create the application and what's the exact error on app failure?

Did you change the IdentityClientId on the App.config file following the instructions from the IdentityService class ? 

        // WTS TODO: Please create a ClientID following these steps and update the app.config IdentityClientId.
        // https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app

**Comment by LoriBru** [comment]
I think you're right, that's likely to be the issue.
I think, though, that it would be better to try/catch the "PublicClientApplicationBuilder.Create" call and throw an exception directly from there. It would be a much more precise and informative hint to what is missing.

**Comment by sibille** [comment]
@LoriBru, just saw that the "WTS TODO" comment should be "TODO WTS", that's why it's not showing up in the TODO list, will fix this. 

Regarding wrapping the PublicClientApplicationBuilder.Create, I think the exception thrown from the PublicClientApplicationBuilder is already including all necesary information: 
![image](https://user-images.githubusercontent.com/24698018/83859652-84609100-a71e-11ea-8dda-a2fe75c90923.png)

**Comment by sibille** [comment]
Also opened #3709 to add a global exception handler to UWP templates

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.20160.2
Wizard version: 0.22.20160.1
