### ISSUE TITLE
The Template Studio menu items disappear from the right-click context menu

### ISSUE THREAD

**Issue by enghch** [microsoft/WindowsTemplateStudio#3782]
**Describe the bug**
As my UWP project is loading, I can right click the project item and see that the Template Studio menu item is there (but the child menu items are all disabled). But after the project is fully loaded, the menu item disappears. It is no longer in project-level context menu.

This happened after upgrading WTS to 3.7

**To Reproduce**
1. Start Visual Studio
2. Open a new solution.
(You may have to wait a second or two after the project loads)
3. Right click on the UWP project
4. See the menu item is missing 

**Expected behavior**
I expected it would be there and be functional

**System**

- **VS Version:** 16.6.4
- **WinTS Wizard Version:**  3.7
- **WinTS Template Version:** 
- **Windows Build:** 10.0.18363

**Comment by sibille** [comment]
Thanks for reporting @enghch. I was looking into this and it seems there is an issue in building the template cache from the right click menu after updating Visual Studio versions. 
While we are working on a fix, you can workaround by starting the WTS Wizard from File -> New Project -> Windows Template Studio (Universal Windows) to build the cache (you don't have to actually create the project, just open the wizard).

**Comment by enghch** [comment]
That workaround worked great! Thanks for that.

**Comment by sibille** [comment]
Glad that unblocked you. 

I was looking deeper into this and think that instead of dynamically evaluating what right click options should be available for each platform, we should have a dictionary of available options for each platform in the wizard. 

Dynamically evaluating visibility of items depending on the available templates for each platform means we have to ensure the cache is up to date and templates are extracted from vsix. 
Refreshing the cache takes only a few seconds, but extracting the templates if necessary (after a vsix update) takes longer. 

Available options do not frequently change, and having a dictionary of available options will help to speed up right click menu visiblity.

**Comment by enghch** [comment]
That would make sense to me. If I understand correctly, that would mean there is always an available list of menu options, even if the templates haven't been extracted for this particular platform yet.

**Comment by sibille** [comment]
Yes, exactly. All available right click options show up, if you select one the templates get extracted/synced if necessary when the wizard opens.

**Comment by sibille** [comment]
We'll ship a hotfix for this.

**Comment by sibille** [comment]
Fixed in version 3.7.20203.3
