### ISSUE TITLE
Payload contains two or more files with the same destination path but they are different sizes.

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3795]
**Describe the bug**
Build error when changing assets in main UWP project without changing corresponding asset in test project.

**To Reproduce**

1) Create a new UWP app using Windows Template Studio
2) Add a "Test App with MSTest" template.
3) Generate the app
4) Replace the StoreLogo in the main UWP app but not in the testing project
5) Execute the test

Build fails with the following error:
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1919,5): error APPX1111: Payload contains two or more files with the same destination path 'Assets\StoreLogo.png', but they are different sizes. Source files: 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1919,5): error APPX1111: C:\Users\ilitio\source\repos\App18\App18.Tests.MSTest\Assets\StoreLogo.png
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1919,5): error APPX1111: C:\Users\ilitio\source\repos\App18\App18\Assets\StoreLogo.png
```

**Expected behavior**
Test should run

**Additional context**
To make changing assets easier for devs, we should use linked files for the Assets in the App Test Project as suggested by @mklemarczyk in https://github.com/microsoft/WindowsTemplateStudio/pull/3794.
 
This change should be applied to the following templates: 
 - [x] Test App with MSTest - C#
 - [x] Test App with MSTest - VB
 - [x] Test App with Xunit C#
 - [x] Test App with Xunit VB

**System**
- **VS Version:**  Microsoft Visual Studio Enterprise 2019 Version 16.6.4
- **WinTS Wizard Version:** 3.7.20203.3
- **WinTS Template Version:**  3.7.20203.3
- **Windows Build:** 18363.959

**Comment by mrlacey** [comment]
To provide further details on what's happening, the build task is failing because `RemovePayloadDuplicates` in `Microsoft.Build.AppxPackage.dll` is trying to make sure that there aren't conflicting/different versions of files being added to the same package.
It seems to be based on the theory that if there are files with the same name/location coming from different projects they can only be included if they're identical. If they're different then something is likely to go wrong and so the build should fail.
This makes perfect sense for content files of referenced libraries, however, in this case, the differing images make no difference to the ability to run tests.
There are probably edge-cases where a test may need a specific version of an image (or another asset) and so it wouldn't be acceptable to ignore differences in any image or any asset file, but it would be great if exceptions could be made for the configured Visual Assets in the test project. Or if visual assets could be made optional in the test project.

**Comment by MSLukeWest** [comment]
I'm from the UWP tooling team.  Historically we've suggested that customers put the code being tested in a separate library so that the unit test project doesn't need to reference the main UWP project directly, which results in no payload files conflicts.  However, the proposed solution of linking to the main project's asset files seems like it should work fine as well.

**Comment by mvegaca** [comment]
Verified in dev-Nightly
Templates version: 0.22.20252.1
Wizard version: 0.22.20252.1
