### ISSUE TITLE
Question - How do I save data on app suspending instead of on background entering

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsTemplateStudio#3886]
**Is your feature request related to a problem? Please describe.**
I understand that `SuspendAndResume` service is to cater to saving and restoring data when the application goes to background. However, I have an application which plays audio and hence it does not make sense to save data on background entering. Rather it would make sense to save, say the playlist or currently playing audio when the app raises the suspending event. 

I am wondering if I can still use the infrastructure that is created for the `SuspendAndResume`. What modification maybe required to make it work?

```cs
        private async void App_EnteredBackground(object sender, EnteredBackgroundEventArgs e)
        {
            var deferral = e.GetDeferral();
            await Singleton<SuspendAndResumeService>.Instance.SaveStateAsync();
            deferral.Complete();
        }
```

Seems like unlike the `Enteredbackground` event, `Suspending` event handler is required to be synchronous.

Applies to the following platforms:
| UWP              | WPF              |
| :--------------- | :--------------- |
| Yes | /No |

**Comment by vmadurga** [comment]
Hi @harvinders ,

You can subscribe to the Suspending event and make the method async:

``` c#
        private async void App_Suspending(object sender, SuspendingEventArgs args)
        {
            var deferral = args.SuspendingOperation.GetDeferral();
            await Singleton<SuspendAndResumeService>.Instance.SaveStateAsync();
            deferral.Complete();
        }
```

Depending on the amount of data you have to save, it is recommended to save data prior to suspension because the Suspending event handler has only 5 seconds to complete its operation.

Here you can find an example that use lifecicle events and Suspending event: 
https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Official%20Windows%20Platform%20Sample/Input%20XAML%20user%20input%20events%20sample

Info about UWP app lifecycle:
https://docs.microsoft.com/en-gb/windows/uwp/launch-resume/app-lifecycle

Info about Application.Suspending Event:
https://docs.microsoft.com/en-gb/uwp/api/windows.ui.xaml.application.suspending
