### ISSUE TITLE
hololens and xbox design support

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#397]
xbox  and HoloLens targeted uwp apps have device specific design. It will be great if template studio can support those tailored design as well by default

**Comment by crutkas** [comment]
@touseefbsb this is pretty vague, what needs to be done?

**Comment by mrlacey** [comment]
At the moment the aim is to provide an app that works everywhere. Got any specific for what should be different for Xbox and/or HoloLens?

**Comment by touseefbsb** [comment]
I meant on xbox the controls with gamepad. Also the navigation menu on xbox and hololens might be a little different style rather than Desktop design. And what about platform specific extensions for UWP? you can add option of adding those extensions in the templates and then generate separate xaml files for tailored design of each platform maybe. This way the developer can easily create separate designs for each platform with already scafolded files and folders for his need.

**Comment by mrlacey** [comment]
@touseefbsb yes there are many, many things we *can* do, but it really helps us plan and decided which things we do do based on actual, specific needs and requests.
Regards XBox, yes we can add gamepad navigation instead of the mouse cursor, but if you want that for the app you may also want other controller-specific functionality. It didn't seem worth adding a feature that would add one line of code to the template and then leaving the developer to add lots more specialist code. What XBox specific features would you like to see?
 We could add references to platform-specific extensions but without doing anything specific with them it doesn't seem like we'd only be doing half of a task that we don't know the other half of. What platforms and specific functionality do you think we should support? 
Instead of providing platform-specific variants of each page we have taken the of providing simple, adaptive pages. If someone wants to add a variant for a specific page but it's probably not a good solution for all pages in an app to have per platform/family variants to every page as that would lead to duplication. Having platform-specific versions of each page also hides issues like windowed desktop apps made small like on mobile or mobile apps run through continuum where a desktop-like experience is preferable.
Do you have any specific examples of pages that more readily suit having platform-specific variants?

**Comment by crutkas** [comment]
@touseefbsb I hear what you're saying but not how is what is being generated not meeting that bar.  That is what is unclear.  Right now this isn't actionable due to vagueness.

You as an end developer can adjust stuff as you see fit.  We're a strong starting point, not a finished application.  We can't do everything nor is that our intent.  We want to do enough to enable but not so much where people have to remove tons of code.  

If something doesn't work, 100%, let's get that item fixed.  Right now, it is unclear what is broke.

**Comment by crutkas** [comment]
closing this out as we haven't heard back.  Will reopen if community member responds

**Comment by touseefbsb** [comment]
https://docs.microsoft.com/en-us/windows/uwp/design/layout/layouts-with-xaml#tailored-layouts
@crutkas Actually this is what I was trying to say before, we can have a new feature known as **Tailored Design** and with that we can generate folders with device specific views, and for each device the recommended design guidelines will already be implemented on each view ( both xaml and cs ) . This will obviously be an optional feature which the developer can choose in the wizard.
examples for device specific tailoring are following

**Desktop** adjust the view with Visual States to react to changing of window size change.
**Mobile** any design guidelines regarding linear view of a page.
**xbox** remove the cursor pointer, make sure focus navigation  works. guidlines about the safe area, tv safe color pallete etc.
****
**surface hub** recommend the use of surface dial, and design the screen with big screen in mind.

the basic and generic code for all these platform specific stuff can be written on page by default, and other recommendations can be given by documentation within the files with comments, and todos. and also link to further design guidlines for that specific platform can be given in comments as well

**Comment by crutkas** [comment]
If items have issues, why not create individual issues against them?

**Comment by touseefbsb** [comment]
items dont have issues this is supposed to be a feature request, do you want me to open a new issue with all the details?
