### ISSUE TITLE
PopUp not open in the appwindow in UWP

### ISSUE THREAD

**Issue by sampathnarine** [microsoft/WindowsTemplateStudio#4177]
**Describe the bug**
I have updated the uwp build version 19401 and I have a button in the window and by click i have opened new appwindow. Now i have another button in the AppWindow to open the popup. Here comes the issue. 

PopUp opens in the primary window and it not shown on the secondary window. Please refer the below gif

### Note :
This issue do not occurs when opened in the normal window. And this issue occurs only in the AppWindow

**To Reproduce**
1. Run the sample
2. Click the OpenNewWindow Button
3. New window opens and click the button open the popup.

**Observed behavior**

Popup opens in the primary window.

**Expected behavior**
Popup Should open in the window where the button is clicked.

**Screenshots**

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/63052528/112823195-998c1f00-90a6-11eb-9952-bf0eada83482.gif)

Applies to the following platforms:

This issue occurs in the UWP platforms.

**System**

- **VS Version:** 

![image](https://user-images.githubusercontent.com/63052528/112824000-9cd3da80-90a7-11eb-94da-6412a4043e65.png)

**TargetVersion:**

![image](https://user-images.githubusercontent.com/63052528/112824149-cc82e280-90a7-11eb-9522-e619cc521356.png)

Please refer the below sample
[UwpAppWindowSample.zip](https://github.com/microsoft/WindowsTemplateStudio/files/6221094/UwpAppWindowSample.zip)

**Comment by mrlacey** [comment]
This isn't an issue with WinTS, this is an issue with the code you have added.

The underlying problem is that the `Popup` you have created isn't parented and so assumes the parent of the main window of the application.

You can easily resolve this by adding the popup to an element in the extra window. For example.
- Give the Grid in `AppWindowPage.xaml` a name. e.g. `<Grid x:Name="GridOnSecondPage">`
- Put the popup in this grid before it's shown. e.g. 
```cs
    GridOnSecondPage.Children.Add(mypop);
    mypop.IsOpen = true;
```

**Comment by sibille** [comment]
@sampathnarine did this fix your issue?
