### ISSUE TITLE
Add test templates to OneByOne-Tests

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4186]
We should add the test templates corresponding to the tested item to the OneByOne-Tests to ensure test compositions work correctly.

_Originally posted by @sibille in https://github.com/microsoft/WindowsTemplateStudio/issues/4015#issuecomment-746179694_

**Comment by mrlacey** [comment]
Can you expand on what's needed here? I don't understand what you want to do.

**Comment by sibille** [comment]
My suggestion here was to add the app testing templates from the testing category to the generated app. 
For example for the WPF add the "Test App with MSTest", "Test App with NUnit", "Test App with xUnit". 
This would allow finding issues like https://github.com/microsoft/WindowsTemplateStudio/issues/4015 where the composition filter for adding tests for the DataGrid was pointing to the ContentGrid templates.

**Comment by mrlacey** [comment]
This sounds like it would essentially double the number of "one by one" tests that are run. 
The OneByOne tests are already one of the biggest groups of tests and include thousands of tests. Doubling them would add hours to the overall execution time.

It seems that the goal here is to try and catch any issues due to composition templates not being defined correctly. 
Given that handling all composition combinations involves too many options that it is not practical, we've previously relied on testing "everything" together and each thing in isolation. This has been sufficient for 4 years, until the issue you reference. Is adding a third category of generic tests the best way to catch similar issues in future?

My concerns are that 
1.  adding this will have a massive impact on test execution time (& when tests take longer to run they are run less frequently)
2.  it sets a precedent for adding tests for more composition combinations and this will also affect point 1.

Is adding many thousand more tests to the templates related to adding tests to the generated app the best solution here?
What other options are available or have been considered?


Are you just proposing doing this for WPF as that's where the trigger issue for this change was found?

With the increased focus on WinUI templates and not on WPF & UWP templates, should new test scenarios intended to catch issues with template authoring, only be added when new templates are added? (i.e. is there any point in adding this for the UWP & WPF templates?)

**Comment by sibille** [comment]
My intent was not to double the number of tests but to add the test templates to the existing set of tests. 
Agree that this is low priority right now, hence closing this issue.
