### ISSUE TITLE
New application crash on resume

### ISSUE THREAD

**Issue by pekspro** [Microsoft/WindowsTemplateStudio#422]
I created a new projected with **Navigation Pane** and **Mvvm Light**. I added a **Blank** and a **Settings** page, and **Suspend and Resume** support.

Now when I debug this in Visual Studio, selects Suspend and Shutdown, and then debug the application again the application crashes with a null reference exception. This happens in the class **SuspendAndResumeService**, method **RestoreStateAsync** on the following line:

    navigationService.Navigate(saveState.Target.FullName, saveState.SuspensionState);

Because **saveState.Target** is null.

**Comment by mvegaca** [comment]
The problem was the activation didn't verify if there was a valid state saved.
The PR #431 address this issue, so it will be fixed in the next nightly build.
Since you are using the suspend and resume feature, remember to save the page state on Page.xaml.cs file OnNavigatedTo (PageViewModel on MVVMLight).
Added to Backlog create a SuspendAndResume app sample. #432

**Comment by pekspro** [comment]
Thank you! I’m looking forward to updates and samples :-)
