### ISSUE TITLE
What is a good way to add a top toolbar (along with left navbar) to a page or to all pages?

### ISSUE THREAD

**Issue by dragansr** [Microsoft/WindowsTemplateStudio#425]
Adding CommandBar element in Page.TopAppBar works on individual pages, but it hides main "hamburger menu"

Is there any sample project where a toolbar is integrated in the templates? 

Eventually it would be nice to have option for a toolbar / CommandBar in the wizard also.

**Comment by mrlacey** [comment]
@dragansr despite its name `Page.TopAppBar` puts the `CommandBar` at the top of the window, not the `Page` that declares it. Because the NavigationPanel works by putting a page within the ShellPage this is why the CommandBar appears over the hamburger control.
You can avoid this by creating the creating the CommandBar inline (within the content of the page) and then it won't appear over controls in the ShellPage. See the code at the bottom for an example.

At the moment there's nothing in the generated templates that uses a CommandBar.
The CommandBar is a very broadly used control, integrating it with the WTS templates raises lots of potential questions:
- How should this be included?
- Does it need a special page type or to be added to existing pages? 
- If existing pages, should it be any/all or just some?
- If just some, which?
- Add to the top, bottom, both, or inline? Or should it vary based on page, project type, and/or device family?
- Include primary and/or secondary items?
- Just regular buttons or also include toggle buttons, separators, or anything else? (context menus?)

Having lots of options is bad for templates as it typically means adding something that won't be exactly what everyone needs and so they have to remove it. Or it means providing a lot of configurable options which can be hard for people to understand and know how to use. This is particularly important for a tool like WTS as I don't expect it to be used lots (very few people build lots of apps regularly) and so usage and options need to be very clear.
This doesn't mean ruling it out, just that need to be very careful with what's added and why.

&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
The code below shows an inline CommandBar added to a Blank page.
```
<Page
    x:Class="App52.Views.BlankPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
    <Grid
        x:Name="ContentArea"
        Margin="12,0,12,0">

        <Grid.RowDefinitions>
            <RowDefinition x:Name="TitleRow" Height="48"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <StackPanel>
        <CommandBar>
            <CommandBar.PrimaryCommands>
                <AppBarButton Label="one" >
                    <AppBarButton.Icon>
                        <SymbolIcon Symbol="Admin" />
                    </AppBarButton.Icon>
                </AppBarButton>
            </CommandBar.PrimaryCommands>
        </CommandBar>
        <TextBlock
            x:Name="TitlePage"
            x:Uid="Blank_Title"
            FontSize="28" FontWeight="SemiLight" TextTrimming="CharacterEllipsis" TextWrapping="NoWrap" VerticalAlignment="Center"
            Margin="0,0,12,7"/>
        </StackPanel>
        <Grid 
            Grid.Row="1" 
            Background="{ThemeResource SystemControlPageBackgroundChromeLowBrush}">
            <!--The SystemControlPageBackgroundChromeLowBrush background represents where you should place your content. 
                Place your content here.-->
        </Grid>
    
        <!--  Adaptive triggers  -->
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="WindowStates">
                <VisualState x:Name="WideState">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="640"/>
                    </VisualState.StateTriggers>
                </VisualState>
                <VisualState x:Name="NarrowState">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="0"/>
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Target="TitlePage.Margin" Value="48,0,12,7"/>
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>
    </Grid>
</Page>
```

**Comment by crutkas** [comment]
Page in our docs vs adding it in?  I am with you @mrlacey for the issues raised with the permutations and what is a good spot for placement on different project types / pages and what not.

**Comment by gcaughey** [comment]
Page in docs works for me. It's hard to know where to stop adding useful things in, but I think this is one of those.

**Comment by dragansr** [comment]
Thank you very much, @mrlacey !
My objective was to quickly add back/forth navigation buttons to WebView, so this may be a use-case to consider in your template, maybe as a part of WebView page. Example in documentation would be useful, but number of people that read detailed documentation is usually much less that who just try wizard. 
The more good practical ready-to-run templates are provided, the more apps in the app store will be, I think. WTS is a huge improvement for UWP.

**Comment by mrlacey** [comment]
@dragansr your specific example of adding back and forward buttons to the webview is built into the next version of the templates. You'll see it in the nightly builds or when v1.1 is released.
It also does refresh, open in browser, loading indicator, and retry on error.
I doesn't use a CommandBar but should be easy to change to one if you wish.

**Comment by mrlacey** [comment]
Things to include in the doc:

- [ ] Issues with using Page.TopAppBar and a NavPanel project
- [ ] How to add a commandbar to a single page within the NavPanel
- [ ] Adding a single Commandbar to every page in a NavPanel app
- [ ] Adding a Commandbar to a single page in a Pivot&Tabs app
- [ ] Adding a single Commandbar to every page in a Pivot&Tabsapp

**Comment by mrlacey** [comment]
Removing myself as assignee as don't want to block others from moving this forward.

**Comment by mvegaca** [comment]
Could we close this issue in favor of issue #1099? Feature: Application CommandBar

**Comment by mrlacey** [comment]
No. do not close this. 
You can't close a request for documentation because at some point in the future there may be a new feature added that does some of the things the requested documentation will cover.

**Comment by mrlacey** [comment]
Merged to dev so now closing.
