### ISSUE TITLE
Assisticant template

### ISSUE THREAD

**Issue by michaellperry** [Microsoft/WindowsTemplateStudio#440]
I created a dependency tracking data binding library called [Assisticant](http://assisticant.net). Dependency tracking removes a bunch of boilerplate and enables a surprising array of view model interactions. I'd like to create two Assisticant templates: view model locator, and view model first.

**Comment by mrlacey** [comment]
Maybe start with one before jumping in and doing both.

**Comment by michaellperry** [comment]
View model locator is by far the more popular pattern. I'll start there.

**Comment by crutkas** [comment]
@michaellperry can you explain a bit more on how you think this would work from a larger aspect of the WTS system?  What would be the end user's [the developer] perspective?

**Comment by crutkas** [comment]
@michaellperry i had a look at this and syncing with multiple people on this topic today, i think this isn't really a good fit right now. My belief here is any dev would easily be able to adjust the code generated then to support this.  This would be treated no different than our default data model.  Ultimately due to this, I think this is one of those doing too much items.

Everyone has their favorite utility and this could be one of countless that could be added in.  It will add a lot of complexity to the templates as every template then would need to be adapted for this and is an opt-in item, not an included item.  It adds a bit more obfuscation and complexity and tracking down issues becomes much more time consuming.

I'm open to revisiting in a few months when we have a few more frameworks, pages, and features online and seeing how this fits in.

**Comment by michaellperry** [comment]
Currently, I ship a NuGet package that gets you started (Assisticant.App). I think templates are a much better tool for this.

I'll write up a guide to modifying the WTS generated code to use Assisticant for those who care to go that route, and post it on my site.

Thanks.

**Comment by crutkas** [comment]
if you want to use WTS engine as your base, by all means, please fork.
