### ISSUE TITLE
Reordering / Home page

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#445]
why is the home page not just the top item in the list?  I can't move the 2nd item to the first item.

My proposal is to only have the top item be the "home" page minus settings page

**Comment by mrlacey** [comment]
Related to this are things like login pages #291 and extended splash screen #293 as these will take over being the first "page" opened but aren't "home" page in the traditional sense. What should happen to these in the list?
Extended Splash Screen could be a feature rather than a page, but could this also work for login? It would seem weird for login pages to not be in the pages list but it can't be the "home" page.

What would be wrong with having the settings page as the homepage? While that would be highly unconventional for a NavPanel structure it might be desirable in a "blank" project type.

I'd be concerned if we ended up needing different rules for ordering and setting home pages based on project type.

**Comment by mvegaca** [comment]
Working on:

- Add drag and drop elements in summary to reorder pages and features.
- Remove arrows to reorder elements in summary.
- Set page as Home when a page is dragged to the first position in summary.

In addition, we need to think about lock the position of SettingsPage at the bottom, because this limitation will depend on the project type. This logic maybe a part of project type layout.

**Comment by mvegaca** [comment]
Added implementation on the following Branch..

- [issue445-reordering](https://github.com/Microsoft/WindowsTemplateStudio/tree/issue445-reordering)

**Comment by crutkas** [comment]
this is awesome

- Settings should always be last and cannot be reordered.
- "made by " should be dropped in right hand summary else it causes a wrapping issue.  This could be removed in the left side as well, tighter and cleaner.

**Comment by mvegaca** [comment]
Icons added in the following Pull Request
[Issue445 reordering](https://github.com/Microsoft/WindowsTemplateStudio/pull/464)

This is already on dev branch.

**Comment by ralarcon** [comment]
Verified in v0.14.17172.65001; templates v0.14.17172.1
