### ISSUE TITLE
Add Template10 as a Framework

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#446]
This is a common request that has been mentioned multiple times  We've synced with @JerryNixon and figuring out what the game plan is. If you are interested in what Template10 is, see https://github.com/Windows-XAML/Template10/

**Comment by mrlacey** [comment]
Moving to Open Community Questions to see if there's demand for this

**Comment by mrlacey** [comment]
[Template10 is changing to be based on Prism](https://github.com/Windows-XAML/Template10/issues/1620). 

In light of this, it will not make sense to add it as a separate framework option. Because of this, I am closing this issue.

In the future, it may be appropriate to add Prism framework specific feature options to include Template10 specific functionality (such as the Tempalte10.Extras library.) If/when that's the case, new issues should be raised.
