### ISSUE TITLE
Cohesive Template for Login, Authorization, Authentication, SSO for Microsoft's first-party services/techs

### ISSUE THREAD

**Issue by myokeeh** [Microsoft/WindowsTemplateStudio#458]
This may be very general, but see how WTS could be in the forefront in promoting correct usage, best practice for implementing login, SSO, authorization, authentication, etc. especially for Microsoft's first-party services and technologies.

Here goes:

So we have client-side, server-side, Microsoft account, Azure AD, Windows Hello, and I'm sure there's plenty more topics, and one key thing that I see missed are really good examples, up-to-date examples, and ones that promote good user experience.

I was astounded to find out how difficult it is to implement Windows Hello to log-in with my Microsoft account in a UWP app that has an Azure Mobile App backend. As of today, I haven't seen an example that shows this--or at least starts to talk about it.

As a side-note, I just found out that my UWP that has the Azure Mobile App backend will have worse UX because version 4.0.0. of `Microsoft.Azure.Mobile.Client` will open a separate browser for users to log-in. https://github.com/Azure/azure-mobile-apps-net-client/pull/326

**Comment by crutkas** [comment]
would you say #292 is the same ask?

**Comment by mrlacey** [comment]
I think #292 covers part of this, #130 & #331 potentially cover more.
Windows Hello support is a new request and so have added #462 to track that separately.
Am going to close this as it's very broad and so hard to keep track of what is and isn't progressing. 
If anything isn't specifically covered by any of the linked issues please add individual issues for specific features. We wouldn't implement a single feature that does every kind of authentication at once because that wouldn't make sense for a single app.

**Comment by myokeeh** [comment]
I find this particularly hard to point out, and understand why this was picked apart, but the operative word is cohesive.

There's too much of:
If this, login this way using this documentation,
else, login this way using this documentation,
else, login this way, etc.

I've seen the many rabbit holes--don't understand why that's the norm.

**Comment by crutkas** [comment]
@myokeeh cause everything operates differently so doing a single page may be very hard.  It also can be overwhelming to an end developer to see 15 auth systems in a single page.  We will take a step back and look at what is best.  I would rather look at the individual tech requests people are asking for and see how we can do this the best.

If you want to help out here, 100% lets start spec'ing something out.

**Comment by myokeeh** [comment]
@crutkas perhaps what I have in my head is beyond WTS--meaning it's not WTS's job to fix why there are so many ways to login to a Microsoft account. I honestly don't know where to direct that piece of feedback.

So to scope it back a bit, let's just talk MS tech/services. In particular client-side login (Windows Hello, OS default app login UI) with Azure App Service.

- Use Windows Hello if available
- Default to login UI similar to Windows Store app if Windows Hello is not available
- Not open a separate browser for login
- Support MSA, AAD and any other MS-based auth
- Work with Azure App Service authentication/authorization/token refresh

To me, this is something that should just work given they're all MS tech. For a hobby developer like me, something like this is gold.

**Comment by mrlacey** [comment]
For third-party data sign in, for security, and subject to availability this should really be done as OAUTH rather than XAUTH. This means embedded webview rather direct capture of credentials. I agree that external browser should be avoided if possible.

For your Azure app service scenario, isn't that covered by #462 & #292?  
Yes, for a specific scenario isn't nice when it can be a single checkbox but when that scenario is composed of multiple items and each of those items is potentially useful on its own then it's better for WTS to provide separate parts that can be combined as different developers need.

I hope/expect we'll eventually be able to get to the point where we can generate everything you describe in your scenario. Anything you can contribute will help it happen faster.
