### ISSUE TITLE
Can remove settingsstorage although settings page is added

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#595]
1) add settings page
2) remove settings storage feature (added as dependency of the first)

-> this should not be posible

**Comment by crutkas** [comment]
can we have a unit test against this?

**Comment by mvegaca** [comment]
Fixed on following [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/628)

**Comment by crutkas** [comment]
Do we have a unit test against this?

**Comment by ralarcon** [comment]
We have tests where dependencies are verified considering that the dependencies are solved at engine generation level (that is, if I'm generating the templat A which have a dependency on B then ensure that the dependency is solved before generate).

In practice, we can remove the setting from the list, it is just the representaton, at the end both templates are going to be generated. And is because of this we are enforcing this at UI level. Anyway we can review the way the composition is solved to look for other strategy.

**Comment by crutkas** [comment]
@ralarcon if that is case, this bug should never have been introduced because it would have failed the unit test

**Comment by ralarcon** [comment]
Let me double check it but if I'm not wrong, once you generate, even if you have removed the dependency,  that dependency is solved and generated. The "remove" only is possible at UI layer.

**Comment by ralarcon** [comment]
After reviewed we will add some unit testing to ensure the dependencies never are removed. Following up in #644
