### ISSUE TITLE
Right click new with non-wts project

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#623]
- Is this for WTS projects only?
- if so, why are we in the right click menu then?
- if so, do we have a POR for being able to do this for non-wts generated apps

![image](https://user-images.githubusercontent.com/1462282/27887377-5098e54c-6195-11e7-8bbc-4a92177b2a7c.png)

**Comment by ralarcon** [comment]
Initially it is limited to WTS projects. The behavior you found is a bug.

It is possible to work in any UWP project, but in order to do so we will need to "setup the project" with the dependencies required by our page and feature templates (ActivationService, NavigationService, ShellPage, etc.). If needed, we can create a different issue to support adding pages and features to non WTS projects.

**Comment by crutkas** [comment]
Should we include an issue to have right click add for non-WTS issues.

**Comment by ralarcon** [comment]
I think so, anyway we need to evalutate the risk of manipulating the developer project.

**Comment by sibille** [comment]
I had an approach for this in the poc_rightclick branch. 
If the project is non-WTS you can choose the projectType and framework and then an "incrementproject" template was generated that contains all the things that would have been added if you created your project with wts without creating a new project (ActivationSerivce, NavigationService). 
I had an issue with adding nuget references in the .csproj file as we use an anchor () for this.

**Comment by mrlacey** [comment]
Created a new issue to discuss adding to an existing project and leave this as an issue for tracking the menu being displayed in projects that it shouldn't.
