### ISSUE TITLE
Process: How do we know what files need to be relocalized

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#646]
If someone goes in and edits a resx, md, or json file, how do we track this so we know it needs to be relocalized

**Comment by ralarcon** [comment]
In my previous experience we always send all files to the localization service in english (with all resources) and them get back translated. This is something we need to check with the translation service. 

As part of the infrastructure, we have created a tool to help extract all the resources suitable to be translated, using the same structure as the source code... maybe we can improve the tool to add an option to just grab files which have been changed (wonder to try to get advantage of the Github rest API)....

**Comment by crutkas** [comment]
why send all the files over to be retranslated if we only diff 4

**Comment by ralarcon** [comment]
I agree, but I guess that considering it is not easy to know which files has been changed to sent to the localization process, send all was the approach. 

We can explore the github API to try to determine which files has been modified since certain day and extract only those (it should be possible).

**Comment by dgomezc** [comment]
The localization file export tool has been modified to get files by commit SHA or tag name. 
Obtains the files that need localization and those modified since the date of that commit SHA or tag name.

The tag name or commit SHA will be passed as arguments.

Example:

`EXT "C:\Projects\wts" "C:\MyFolder\Extracted" -c "f988be4c0878b2b51976e84ce827fce19cf294bf"`
or
`EXT "C:\Projects\wts" "C:\MyFolder\Extracted" -t "v1.0"`

**Comment by mrlacey** [comment]
Is this use of the tool documented somewhere other than here?

**Comment by ralarcon** [comment]
The tool have help it self and it is not thought to be used externally by the moment. It is true we don't have a documentation for localization requirements and process and we should. I've opened a new issue for that.

x-ref: #1205
