### ISSUE TITLE
VS Right Click add menu: Should it be inside the "add" category

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#737]
Right now we're inside our own menu.  As a dev, i go to "add" for new stuff, should we be submembers inside that?

**Comment by ralarcon** [comment]
I personally like the idea of having a Menu for our tool. I think we can place the same command in more than one place. Would it make sense to have "New feature" and "New page" directly under the "Add"?

**Comment by mrlacey** [comment]
My preference would be to keep everything under the WTS menu.
We're, potentially, doing a lot more than just adding a file (what with all the merging) and I think having it as separate from the standard menu "Add" shows that it's different. 
Having it separate makes it an intentional decision to do more than just add a file to a project, WTS allows you to integrate new functionality deep into an existing project.
