### ISSUE TITLE
NewItem.MD conflicting statement

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#753]
Failed merge and conflicting all have statements that can be overlapping and it isn't clear when each use case would be hit.

**failed merge**
`The file was found, but has changed. In this case, please study the shown code blocks and see how to integrate them in your file.`

**conflicting**
`Files that were generated as part of the new feature/page but are already part of your project but are different.`

Conflicting then says we won't copy our version to the temp folder but that person must review the changed?  how do that do that then?

**Comment by sibille** [comment]
A failed merge is the consequence of a failing postaction, f. ex. you create a new page and the postaction that adds the page to the ShellViewModel fails because the ShellViewModel was renamed. 

A conflicting file is a file that was generated by the new item but is already there in your project and both files are different. For example you add a SettiungsStorage Feature but already have a class that's named Json.cs. You have to review the differences between the file in the project and the temporary folder, because I can't tell if what's in your Json.cs file is valid for the SettingsStorage or not.

I'll try to make the text explain the difference between the two better in the doc.

**Comment by sibille** [comment]
Verified in nightly build Wizard Version 0.14.17194.65002, Templates Version 0.14.17194.3
