### ISSUE TITLE
Right click command does not differ between local vsix and nightly

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#798]
Infer name in build as with templates.

**Comment by ralarcon** [comment]
This would lead to side by side execution issues if more than one extension (local / dev) is installed in the same Visual Studio. 

I have added a way to change the identifications of the VS command package during the build. Using that way we know exactly which deployment we are about to use thru the rightclick (local, nigthly, pre).

We need to review the isolation of each extension because running more than one version in the same visual studio session would lead to unexpected behaviours (related to #497 where having isolation would allow to run all instances side by side)

**Comment by mrlacey** [comment]
Side note: I'll probably have questions about this when it comes to VB support.
