### ISSUE TITLE
Redesign UX on adding item to "shopping cart"

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#875]
As part of #669 to unifying controls, i think we should also rethink maybe the metaphor for interaction on adding stuff.

Why:

- Multiple times i've seen really smart people in file->new click the box without confirming only to be annoyed when the items they wanted aren't there.
- Right-click add and file->new have different interaction models
- Right-click add and file->new renaming are in different places
- Pages/background tasks versus features in file->new act differently

I think we should think about this now and do it for 1.4.

**Comment by mrlacey** [comment]
&ast;cough&ast; Original design had the text boxes (for entering page names, etc.) always visible so there wasn't an inconsistency with some items needing a single tap to add and some needing two. &ast;cough&ast;

**Comment by mvegaca** [comment]
Move it to 1.4?

**Comment by crutkas** [comment]
agreed.  Lets sync next week on this when I'm in Madrid.

**Comment by ralarcon** [comment]
@crutkas, does this should wait until the UI redesing?

**Comment by crutkas** [comment]
yes

**Comment by mvegaca** [comment]
These are the new wizard redesign Tasks (Done / In progress / TODO).
In order to track the status of the development progress I'll keep updated this list during the new wizard development.

**Done**
Wizard steps
- Buttons management
- Navigation
- Project type and framework list views with visual styles
- Pages and features list views with visual styles
- Project details combobox selection
- Project details pages and features textbox with icons
- Temples repository initialization
- Visual Studio colors, font sizes and font family

**In progress**
- Alert system

**TODO**
- Template Detail view using markdown
- Add pages and features from template layout
- Close wizard generation cycle
- Reorder with Drag and drop
- Remove selected templates
- Template naming validations
- Template updating cycle
- Lock single instance template when selected.
- Loading feedback
- Error handling
- Unit testing

This new wizard redesign can be checked out in [this branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by mrlacey** [comment]
With larger pieces of work (like this or Xamarin support) would it make sense to use a [project board](https://help.github.com/articles/about-project-boards/) to track progress?
Thoughts? @ralarcon ? @crutkas ?

**Comment by mvegaca** [comment]
Raúl and I were talking this morning about that Issue, we decided to split these working areas on different Issues adding "Wizard" before the Issue title.

**Comment by ralarcon** [comment]
By the way, we can try to use the project board if consider it is interesting (just to know what is in progress and what is left).

**Comment by mvegaca** [comment]
These are the Issues that I've created for completing Wizard development tasks.
I'll assign to me the Issues that I will be working on and labeling that issues as In-progress.
Closing this Issue in favor of new Issues created.

![image](https://user-images.githubusercontent.com/5556784/34573710-57aee4d8-f175-11e7-9a5f-2e5142d3ced5.png)

**Comment by mrlacey** [comment]
Yesterday (above) you said you'd track progress on each item in the list you've created but now you've closed this issue. Does that mean you won't be tracking anything there now?

Do you **_really_** need a prefix on the title names when things are tagged with the same?

**Comment by ralarcon** [comment]
My understanding is that this needs to be open while one or more related issues are open, as well as the other issues must reference this.

**Comment by mvegaca** [comment]
List of Issues for Tasks in the wizard redesign:

- Wizard: Complete generation cycle #1641
- Wizard: Reorder with Drag and drop #1642
- Wizard: Remove selected template #1643
- Wizard: Complete Template naming validations #1644
- Wizard: Template updating #1645
- Wizard: Templates adding #1646
- Wizard: Loading feedback #1647
- Wizard: Error handling #1648
- Wizard: Right Click Design #1649
- Wizard: Integrate Dev branch Sync infrastructure #1650
- Wizard: Consolidate New wizard removing old code. #1651
- Wizard: Add Windows Template Studio Colors to Visual Studio #1652

**Comment by mrlacey** [comment]
moving out of backlog as v2.0 is basically this.

**Comment by sibille** [comment]
Done
