### ISSUE TITLE
when multiple WTS installed - Right click add will error depending on which you pick

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#881]
### Repro steps

RTM version and pre-release both have this issue when you have the dev version installed.

On a valid project, right click add into a project.  You'll see the error below.

### Actual Behavior

![image](https://user-images.githubusercontent.com/1462282/28556503-a2bf4d54-70bb-11e7-8e2b-b024d44f5501.png)

### work around

Only one version of the extension can be installed

## System

wizard: 17198.1
template: 17202.1

**Comment by crutkas** [comment]
marking this as backlog, this only affects core dev team members I think as we tend to have multiple versions installed, low priority IMO

**Comment by ralarcon** [comment]
After some investigation this issue is related to the fact that in WPF there is no way to set the strong name for the resources location. There is no official / easy way to set an strong name to the resource as you can see [here](https://connect.microsoft.com/VisualStudio/feedback/details/668914/xaml-generated-code-uses-resource-uri-without-assembly-strong-name). 

I've found a [tricky work arround](https://stackoverflow.com/questions/1453107/how-to-force-wpf-to-use-resource-uris-that-use-assembly-strong-name-argh) to set the strong name but I don't think is worthy considering: 
* applying the workarround I've unlocked the first exception but got other different later
* the real impact is small (as it only affect developers / people with more than one version installed side by side)
* there is a workaround to test / use a certain version: disable the others.

With this, I think we can close this issue.

**Comment by ralarcon** [comment]
Closing as it can't be solved.
