### ISSUE TITLE
Navigation Template Back Button Doesn't Restore Storyboard State

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/WindowsTemplateStudio#885]
### Repro steps

1) Create a Project with a Navigation Pane and a Couple of Pages.
2) Run the project and click on a couple of pages.
3) Now click the back button in the top-left.

Note: Previous page still has a highlight bar to it's left:

![image](https://user-images.githubusercontent.com/24302614/28596484-98dbcbcc-714d-11e7-8dbc-7431c5ec7cb4.png)

App does seem to switch page and think the current one is selected, but there's some lingering visual state remaining.

### Expected Behavior

Expect Previously Selected Highlight bar on left to disappear.

### Actual Behavior

What really happened

## System

* **VS Version:** 2017 15.2 26430.16
* **WTS Wizard Version:** 1.2.17198.1
* **WTS Template Version:** Not sure where to get this?
* **Windows Build:** 15063

**Comment by mrlacey** [comment]
This feels very familiar and like something I addressed before when changing the styling of the navigation menu items.
Possibly a regression when switching to the updated community toolkit control.
investigating....

**Comment by mrlacey** [comment]
Yes, it all comes back to me now.
It's a bug in the HamburgerMenu control. Although [they say it's not a bug](https://github.com/Microsoft/UWPCommunityToolkit/issues/969#issuecomment-281396945).
The control includes an indicator of the selected item (internally it's even called `SelectionIndicator`) but it doesn't handle the back button. (I guess they don't count this as "selection".)
The reason that two items appeared to be selected is that one was being correctly indicated by us and the other was incorrectly being indicated by the control. Normally our control appears over the top of theirs but when they're out of sync you see two.
I think it's their bug as they are showing an indicator which we can't control and works most of the time but when it doesn't they say we're "responsible for selection synchronization" but we don't use the underlying selection system as it's not appropriate and doesn't work when we have two lists (like we do).
Anyway...

**workaround**

Add a background to the Grid in the DataTemplate at the top of ShellPage.xaml. Like this:

```xml
<Page.Resources>
  <DataTemplate x:Key="NavigationMenuItemDataTemplate" x:DataType="vm:ShellNavigationItem">
    <Grid Width="320" Height="40" Background="{ThemeResource SystemControlBackgroundAltHighBrush}">
```

This hides the indicator that they show and so the only one that's ever seen is ours, which we know is always correct because it's synchronized with what's displayed on the main part of the view and also reflects the text color highlighting.

@crutkas does this warrant a hotfix? The indication of the selected item in the NavigationView is broken if you use the back button. I think this is pretty bad.

**Comment by crutkas** [comment]
Let's hot fix.  I trust your gut

Do we want the fix for #622 in as well?

**Comment by mrlacey** [comment]
PR #930 raised against master for hotfix.
include #622 if you've verified no side-effects

**Comment by mrlacey** [comment]
Will also need to reapply this fix against dev once the hotfix is released. (Could just update dev from master rather than make another PR request.)

**Comment by mrlacey** [comment]
Correct PR is #931

**Comment by mrlacey** [comment]
verified in dev-nightly
wizardVersion="0.14.17228.65001"
templatesVersion="0.14.17228.1"

**Comment by limefrogyank** [comment]
FYI, this hack kills all the VisualState effects.  I just submitted a pull request to add an ItemContainerStyle dependency property to the HamburgerMenu so that you can just leave out the built-in indicator using a modified version of their own built-in style.

[https://github.com/Microsoft/UWPCommunityToolkit/pull/1496](url)
