### ISSUE TITLE
White bar appears on top on dark theme on mobile.

### ISSUE THREAD

**Issue by qbss** [Microsoft/WindowsTemplateStudio#903]
## For new Features:

* **Overview:** What you'd think should be added with scenarios
* **Links:**

### Repro steps

What did you do? How can someone else reproduce this?

### Expected Behavior

What was expected to happen
(include screenshots if a visual issue)

### Actual Behavior

What really happened

## System

* **VS Version:** 2017 Ver. 15.2
* **WTS Wizard Version:** 1.2  (public, release preview, & latest nightly builds)
* **WTS Template Version:**
* **Windows Build:** 15063.502

**Comment by qbss** [comment]
![darkthemewhitebar](https://user-images.githubusercontent.com/24708922/28905668-1c97b1e0-77e0-11e7-9c1e-40ded5f07428.png)

**Comment by qbss** [comment]
Screenshot from the emulator with the black theme enabled.

**Comment by qbss** [comment]
This looks to be getting resolved soon by the updated code in "App mode Light/Dark/Windows default #350" .

**Comment by crutkas** [comment]
I think we still need to look at this just in case.  I'm focusing on a very targetted item

**Comment by crutkas** [comment]
Ok, just looked at this.  I know why this is happening.  It is actually behaving properly.  What you're seeing is actually the mobile status bar.  Because to handle this we would have to add the mobile extension to all solutions, we wouldn't add this by default.

What we could do is add in a comment and point to a documentation page if enough people request it.

To hide it, do two steps.

1. Add mobile extension to project references
2. in `app.xaml.cs` on `OnLaunched` add this:

```
if (Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.UI.ViewManagement.StatusBar"))
{
    var statusBar = Windows.UI.ViewManagement.StatusBar.GetForCurrentView();
    await statusBar.HideAsync();
}
```
