### ISSUE TITLE
Reinstate all unit tests for project generation

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#957]
For #946, we disabled large sums of tests.

We disabled

- GenerateAllPagesAndFeatures
- GenerateProjectWithIsolatedItems
- GenerateEmptyProject

**Comment by ralarcon** [comment]
Moving this 1.3 as part of the CI / Deploy builds enhancenments.
Reviewing the approach for integration tests for generation:
* I will split the testing using Traits / Collections to allow to execute just Generation tests (quick run) and build the generated content (slow due to the build process it self).
* Generation tests will be part of the CI which will ensure that, at least, the generation works fine
* Building the generated projects (slow and time consuming) will be executed every time we commit code (lets try to do it just when the templates are modified -not sure if possible). This build test will run in a dedicated build server to avoid blocking developers.

**Comment by mrlacey** [comment]
Can changes made here be done in connection with #831 so that it becomes clear on the impact of adding new tests in different places? And even the consequences of adding new test projects.

**Comment by ralarcon** [comment]
No are working in CI / Integration builds
