### ISSUE TITLE
Page: Ink page for loading and annotating a picture.

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#971]
Load image, annotate, save picture w/ ink, save & load ink

**Comment by crutkas** [comment]
xref #799

**Comment by sibille** [comment]
After speaking to the ink team we added functionality to the ink pages. 
Functionality in this page:
- Load image
- Export image + ink as png
- Zoom

Also, instead of using a control, the inkcanvas and toolbar are in the page, and we use a series of services to provide common ink functionality to the three ink pages.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18187.1
Wizard version: 0.18.18187.1
@nigel-sampson, could you have a look at the caliburn implementation?

**Comment by nigel-sampson** [comment]
LGTM

**Comment by sibille** [comment]
thanks @nigel-sampson

**Comment by sibille** [comment]
@LeeParrishMSFT or @milazzom, could you have a look at the Prism implementation?

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.18.18212.2
Wizard version: 0.18.18212.1
