### ISSUE TITLE
Page: Ink canvas page with drawing

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#972]
Have a page with Ink Canvas and ability to draw ink, dry it, and draw more.  Select / move ink w/ custom dry

**Comment by crutkas** [comment]
xref #799

**Comment by dgomezc** [comment]
See [https://github.com/dgomezc/inkpoc](https://github.com/dgomezc/inkpoc) for ink poc, this poc includes all ink pages relying on a common ink control, page "Draw" has funcionality mentioned this issue.
 
This page contain a inkCanvas to draw and extend inkTool with these options:
 - Selection ink strokes
 - Enable disable touch inking
 - Cut/Copy/Paste selected ink strokes
 - Undo/Redo
 - Zoom in / Zoom out
 - Load / Save ink strokes in a file
 - Export ink strokes to png image
 - Clear all canvas (strokes, selection, undo/redo stack, etc)
 
We have doubts about whether the cut/copy/paste options are useful in this case, since, we have not developed functionality to move the strokes. Even so, the paste function has two parameters (int xPosition, int andPosition) in which we can indicate the coordinates where to paste the strokes on the canvas.

**Comment by sibille** [comment]
After speaking to the ink team we added functionality to the ink pages. 
Functionality in this page:
- Load/save ink
- Lasso selection
- Move selected strokes
- Copy/Paste strokes
- Undo/redo
- Export as png
- Zoom	
Also, instead of using a control, the inkcanvas and toolbar are in the page, and we use a series of services to provide common ink functionality to the three ink pages.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18187.1
Wizard version: 0.18.18187.1
@nigel-sampson, could you have a look at the caliburn implementation?

**Comment by nigel-sampson** [comment]
LGTM

**Comment by sibille** [comment]
Thanks @nigel-sampson

**Comment by sibille** [comment]
@LeeParrishMSFT or @milazzom, could you have a look at the Prism implementation?

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.18.18212.2
Wizard version: 0.18.18212.1
