### ISSUE TITLE
Page: Smart Canvas

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#973]
A page with a Ink canvas that automatic conversion to shape and hand writing to objects

**Comment by crutkas** [comment]
xref #799

**Comment by dgomezc** [comment]
@crutkas just to be sure we understand this correctly, with "hand writing to objects" do you refer to text recognition or just shapes recognition?

**Comment by dgomezc** [comment]
See [https://github.com/dgomezc/inkpoc](https://github.com/dgomezc/inkpoc) for ink poc, this poc includes all ink pages relying on a common ink control, page SmartCanvas has funcionality mentioned this issue.
 
This page contains a inkCanvas to draw shapes or text and extend inkTool with these options:
 - Recognize shapes.
 - Recognize text.
 
It also contains in bottom part of the page an example of how to detect the text from outside the inkControl.

**Comment by sibille** [comment]
After speaking to the ink team we added functionality to the ink pages. 

Functionality in this page:
- Load/save ink
- Lasso selection
- Node selection using inkAnalyzer
- Move selected strokes
- Undo/redo
- Transform to shape/text using inkAnalyzer
	
Also, instead of using a control, the inkcanvas and toolbar are in the page, and we use a series of services to provide common ink functionality to the three ink pages.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18187.1
Wizard version: 0.18.18187.1
@nigel-sampson, could you have a look at the caliburn implementation?

**Comment by sibille** [comment]
Thanks @nigel-sampson

**Comment by sibille** [comment]
@LeeParrishMSFT or @milazzom, could you have a look at the Prism implementation?

**Comment by milazzom** [comment]
@sibille Prism implementation of the inking pages look good.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.18.18212.2
Wizard version: 0.18.18212.1
